### ISSUE TITLE
Double diacritics+CGJ mechanism potentially broken

### ISSUE THREAD

**Issue by roozbehp** [behdad/harfbuzz#101]
Unicode has a double diacritic+CGJ mechanism for rendering a diacritic over or under a double diacritic. For example, the sequence u͡͏́i (u + combining double inverted breve + CGJ + combining acute + i) should result in the acute accent rendered above the double breve.

As this doesn't seem to work in HarfBuzz with any of the Windows fonts, Roboto, Noto, or DejaVu, I'm assuming it's a HarfBuzz bug.

Here's the text of the Unicode standard, from Unicode 7.0 (http://www.unicode.org/versions/Unicode7.0.0/ch07.pdf), page 325 and 326:

![image](https://cloud.githubusercontent.com/assets/302255/7313519/77aa7588-ea0f-11e4-86c2-d0b55c8cd147.png)

![image](https://cloud.githubusercontent.com/assets/302255/7313525/a21b27ae-ea0f-11e4-83be-386aba96043d.png)

**Comment by roozbehp** [comment]
Here's the rendering from Segoe UI. It looks the same with all other fonts:
![segoeui](https://cloud.githubusercontent.com/assets/302255/7313562/1423b0be-ea10-11e4-8c14-68a7dda28118.png)

**Comment by behdad** [comment]
Same thing happens with Uniscribe.

This is one of those things where no one has decided how the Unicode behavior is to be implemented in OpenType.

It occurs to me that a well-constructed mkmk feature (that skips the GCJ glyph; though HarfBuzz should work without that as well) can attach the combining mark to the double-mark just fine.  I'm guessing that the fonts didn't bother.

Care to try creating the feature using ttx?

**Comment by behdad** [comment]
It's a font bug.  The font doesn't have mkmk support to attach the acute (or possibly anything) on top of the double-mark.  We manually modified a subset font to add that, and assigned the double-mark the same mark attachment class as the acute, and it started working with HarfBuzz as is.  Please report to Noto.
