### ISSUE TITLE
hb-view alignment option?

### ISSUE THREAD

**Issue by deepflame** [behdad/harfbuzz#113]
Hi there!

hb-view is really great to render beautiful text as svg for usage on the web.
It is also possible to use a text file for multiline input.

Now I was wondering if it is possible to align the text to the right or to center it with hb-view.

Any help is highly appreciated.

Thanks
Andreas

**Comment by behdad** [comment]
Currently we don't support alignment.  It would be easy to add.  Lets see if anyone wants to contribute that.

**Comment by deepflame** [comment]
I see, thanks for the reply.

Well, I would love to contribute but I am not a very skilled C programmer.
Maybe you could point me in the direction in the code where this should be added?

Or is there another command line tool out there that can render text to SVG with correct kerning?

**Comment by behdad** [comment]
> Well, I would love to contribute but I am not a very skilled C programmer.
> Maybe you could point me in the direction in the code where this should be added?

If you do a grep for margin in harfbuzz/util, you get enough pointers of the places that need to be touched.

> Or is there another command line tool out there that can render text to SVG with correct kerning?

pango-view.

**Comment by deepflame** [comment]
Thanks for the input Behdad.

`pango-view` does not render SVGs correctly as it seems. PNGs are not a problem.
I run 

    pango-view --text=Hello --output=test.svg -q

and get a distorted image. However the SVG source looks promising.


Would you have an idea how to fix it?

Otherwise I may try to implement the text alignment into hb-view or use separate images for each line and align them in html (not the best, I know).

**Comment by twardoch** [comment]
I would say it's not such a bad idea (to have one SVG per line). In fact, it's exactly how it worked in metal typesetting: you'd get lines of text, and you'd then be free to arrange them as you want. If you use CSS to align the lines, you're much more flexible — you can easily left-align, center or right-align them, and you can even make some optical margin adjustments. :)

**Comment by deepflame** [comment]
@twardoch you are right. My concern were just the amount of HTTP requests to the server. But maybe I can just inline the SVGs in the HTML...
Thanks for the comment :)
