### ISSUE TITLE
Backward compatible issue with pango1.0-1.36.3

### ISSUE THREAD

**Issue by kojiishi** [behdad/harfbuzz#115]
When we tried to use up-to-date harfbuzz-ng with pango 1.36.3, we've got a crash case. The detailed stack traces are reported at [crbug.com/503858](http://crbug.com/503858) and [a comment in a patch review](https://codereview.chromium.org/1201253004/#msg5).

As far as I looked at the stack traces, this one seems to be offending:
```
0x00007ffff67c92b0 in hb_shape (font=0x32719220ab0, buffer=0x327191e4620, 
features=0x7fffffffcc80, num_features=0)
at ../../third_party/harfbuzz-ng/src/hb-shape.cc:386
```
So Pango calls hb_shape with invalid `features` (probably only if `num_features` == 0) and the current harfbuzz-ng does not like this.

Is it possible not to read `features` if `num_features` == 0?

**Comment by behdad** [comment]
> When we tried to use up-to-date harfbuzz-ng with pango 1.36.3, we've got a crash case. The detailed stack traces are reported at crbug.com/503858 and a comment in a patch review.

I saw that, but nothing pops out to my mind why that might be crashing :(.

There are two very different crashes there.  It makes me think that objects created using one harfbuzz are being passed to the other.
 
> As far as I looked at the stack traces, this one seems to be offending:
> 
> 0x00007ffff67c92b0 in hb_shape (font=0x32719220ab0, buffer=0x327191e4620, 
> features=0x7fffffffcc80, num_features=0)
> at ../../third_party/harfbuzz-ng/src/hb-shape.cc:386
> 
> So Pango calls hb_shape with invalid features (probably only if num_features == 0) and the current harfbuzz-ng does not like this.
> 
> Is it possible not to read features if num_features == 0?

We definitely don't touch features if num_features is zero.  And that features array is valid.  It points to an array on the stack.

**Comment by kojiishi** [comment]
You're right, too new to Linux, sorry for bothering.

**Comment by behdad** [comment]
No worries.  Thanks for taking care of it.
