### ISSUE TITLE
Why reorder U+0E3A (Thai Nighahit)?

### ISSUE THREAD

**Issue by sungsit** [behdad/harfbuzz#118]
Hi. Could please inform me why HarfBuzz always reorder U+0E3A (Thai Nighahit) to the lowest stack?

I can't find any particular reason why it should do that for Thai national language. Moreover, it is not desired behavior for some minority languages which use Thai script.

![nikahit](https://cloud.githubusercontent.com/assets/3959487/8508593/056c608c-2266-11e5-83e9-fa21d74328fd.png)

The screenshot above, I input Thai consonants & U+0E3A before other low vowels but HarfBuzz still displays it at the lowest position (the first 2 are actual words from Melayu-Pattani, the last one is just for testing `mkmk`). Compared to FontForge, it should be like a screenshot below - the font with `mkmk` feature can be found here https://github.com/BoonUni/boonjot).

![nikahit-fontforge](https://cloud.githubusercontent.com/assets/3959487/8508663/7c6178e2-2268-11e5-9ec3-459c23ce1134.png)

**Comment by behdad** [comment]
Basically because Windows does that.  Is that a good-enough answer?

**Comment by sungsit** [comment]
I just found out that Harfbuzz & Uniscribe override Phinthu (U+0E3A) combining class (sorry, I previously mentioned it as Nighahit) and this problem has been discussed before but I still don't know why Windows does that.

So in case someone needs to create OpenType feature to workaround this problem, there is Theppitak's guideline [here](http://thep.blogspot.com/2015/08/patani-malay-support-in-fonts-tlwg-with.html) (in Thai).

Thank you for creating Harfbuzz anyway, it helps doing Thai & Lao fonts a lot easier for GNU/Linux and the web!
