### ISSUE TITLE
Strange behavior with ccmp lookup & marks

### ISSUE THREAD

**Issue by Pecita** [behdad/harfbuzz#121]
Hello.
It is not very important but I am curious to understand ...
In this minimal font the latin dz digraph is transform to a d followed by a z using a ccmp lookup.
Applying an accent to the digraph then it moves it to the first letter ignoring (for GPOS mark) the separation done by the ccmp lookup.
http:pecita.eu/ccmpDigraph/ccmpDigraph.tar.bz2

**Comment by behdad** [comment]
Right.  We have found that this is the behavior that Uniscribe exposes, at least in the Arabic shaper, so we have implemented it that way.  I understand it might not be desirable...

**Comment by behdad** [comment]
Or does Windows expose a different behavior in your testing?

**Comment by Pecita** [comment]
Behdad, thank you for the explanation.
In my view and for LCG scripts this is wrong. It's useful only for digraphs and for digraphs diacritics applies always to the second letter (try switching the sample text to a classic ttf font).
I only have Linux computers for testing.

**Comment by behdad** [comment]
Thanks.  I'll test and reconsider.

**Comment by jfkthame** [comment]
I think this mostly serves to illustrate the fact that it's a bad idea to use the digraph characters in general, at least in conjunction with combining marks. Given a digraph <xy> followed by a combining accent such as <acute>, it's unclear in principle whether the accent is expected to appear on the first component of the digraph, on the second component, centered over the digraph as a whole, or perhaps even duplicated and rendered on both components.

(FWIW, I suspect the latter would be the most appropriate thing to do in Dutch if presented with the text sequence <U+0133, U+0301>, for example: it's wrong to write either  iȷ́  or  íj, the correct presentation is  íȷ́ .... which is i-acute j-acute, in case it doesn't render well for you. But this isn't up to an engine like harfbuzz; if anything, it'd be up to the 'locl' feature to decide which rendering to implement.)

**Comment by Pecita** [comment]
I agrees that this case is very marginal and the digraphs are a silliness.
I think only in terms of consistency. If we want to make a clean typeface we must have tools that work with logic.

**Comment by behdad** [comment]
I double checked that Uniscribe does the same.  Closing as such.
