### ISSUE TITLE
`set_use_properties` in hb-ot-shape-complex-use.cc is unused

### ISSUE THREAD

**Issue by nico** [behdad/harfbuzz#126]
clang complains:

    ..\..\third_party\harfbuzz-ng\src\hb-ot-shape-complex-use.cc(242,1) :  warning(clang): unused function 'set_use_properties' [-Werror,-Wunused-function]
    set_use_properties (hb_glyph_info_t &info)
    ^

**Comment by behdad** [comment]
Removed.  Thanks.
