### ISSUE TITLE
Support Old Italic languages

### ISSUE THREAD

**Issue by brawer** [behdad/harfbuzz#132]
As described in [Unicode Technical Note 40](http://www.unicode.org/notes/tn40/old-italic-glyph-variation.pdf), some Old Italic languages use different glyph variants than others for the same Unicode codepoint. For example, U+1031A has an 8-shaped glyph in Umbrian but an ↑-shaped glyph in Faliscan. To support UTN40, Microsoft has recently registered the following OpenType language tags (screenshot taken from a personal e-mail thread with Microsoft):

![a87afeec-4763-11e5-9e49-07f9e2d274db](https://cloud.githubusercontent.com/assets/1527880/9655707/6c6c1e1a-5233-11e5-84a8-fcff935ab43d.png)

HarfBuzz can easily support these language tags. I'll make the change.

**Comment by brawer** [comment]
Hm, just noticing that Microsoft hasn't updated the [registry](http://www.microsoft.com/typography/otspec/languagetags.htm) yet. Checking back with them; once they confirm, I'll make a pull request for https://github.com/brawer/harfbuzz/commit/fc3bb9706cd620080ad908e38fc4bdad5d0588ef.

**Comment by behdad** [comment]
What's the status here?

**Comment by behdad** [comment]
Please reopen if there's work to do.
