### ISSUE TITLE
isntallation error!

### ISSUE THREAD

**Issue by mnameghi** [behdad/harfbuzz#133]
Hi
While I tried to install harfbuzz on linux, I got this error:

checking for CTFontRef... no
checking for CTFontRef... (cached) no
configure: error: CoreText support requested but libcoretext not found

Please help me.

**Comment by khaledhosny** [comment]
What options did you pass to the configure script?

**Comment by mnameghi** [comment]
I installed it with brew.
just type: brew install harfbuzz

**Comment by khaledhosny** [comment]
That is a packaging issue, but try `brew edit harfbuzz` and replace `--with-coretext=yes` with `--with-coretext=auto`, and report the issue to them.
