### ISSUE TITLE
Build for windows

### ISSUE THREAD

**Issue by mrsaleh** [behdad/harfbuzz#135]
Hi
How can I build harfbuzz for windows?

**Comment by tamaskenez** [comment]
You can try https://github.com/tamaskenez/harfbuzz-cmake. Let me know how it goes or if you need help with cmake.

I guess there's also the usual mingw/cygwin way if that fits your needs better but I'm not informed in those.

**Comment by mrsaleh** [comment]
Hi 
The following error occurred in CMake:

CMake Error at cmake/CloneAndInstall.cmake:136 (message):
  Failed to install
  D:/ZGE/ZGE/libraries/harfbuzz-cmake-master/binaries/ragel-build
Call Stack (most recent call first):
  CMakeLists.txt:8 (clone_and_install)

**Comment by tamaskenez** [comment]
The actual error occurs before the first line of your log. Could you send me the entire log? Also, could youu share the command line you started cmake with? Did you use something like:

    cmake -H. -Bbuild -G "Visual Studio 12" -DCMAKE_INSTALL_PREFIX=$PWD/out

or in case of windows shell

    cmake -H. -Bbuild -G "Visual Studio 12" -DCMAKE_INSTALL_PREFIX=%CD%\out

?

**Comment by mrsaleh** [comment]
You were right, I checked again everything , and I found the cause of the error , you may laugh at me.
I didn't run cmake as administrator and when I did so , as cmake told me it may be the reason error occured , everything worked well. (cmake were trying to make a folder in program files that windows didn't let it ,so error occured , is this really neccessory to make such a folder ? I don't have any idea.)
Thank you so much tamaskenez.

**Comment by tamaskenez** [comment]
cmake tries to install the harfbuzz libs under "Program Files" which is the default install location on Windows.
Instead of running cmake in admin mode, you need to set the CMAKE_INSTALL_PREFIX variable to a more convenient location like I did above.

**Comment by mrsaleh** [comment]
Ahhh, yeah , you're right again , thank you
