### ISSUE TITLE
mark-attachment mishandling as in overline marks in Coptic

### ISSUE THREAD

**Issue by jungshik** [behdad/harfbuzz#137]
In an email thread, @kmansourMT wrote that:

 "The latest case is related to the use of overline marks in Coptic. I suspect HB is not handling mark-attachment correctly".

@kmansourMT, can you upload a minimal test case along with the image of what you believed to be a correct behavior (by other shaping engines)?

**Comment by behdad** [comment]
Kamal and I sorted out that issue back in August.
