### ISSUE TITLE
Use Docker infrastructure of Travis CI

### ISSUE THREAD

**Issue by ebraminio** [behdad/harfbuzz#138]
As just a possible to do thing, we can use [Docker infra](http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/) for Travis CI, [sample change](https://github.com/antiagainst/shaderc/commit/31ea2d8380b31b72a74574f80cc8ea58a5b44466). Main advantage of it is quicker CI checks and the disadvantage I see is the no longer apt-get on Travis CI config file that maybe(?) some people used to learn about compile dependencies of harfbuzz. Also `libgraphite2-dev` is not yet available on their [whitelist](https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise) which will be resolved soon I guess.

**Comment by behdad** [comment]
I'm fine with that.
Re list of deps. I list those on harfbuzz.org.  But people don't read there.  Can you move those to our README or INSTALL or BUILD or some other prominent place?  Also, we should add list for homebrew as well.  I hear that's more common than MacPorts these days.

Thanks!

**Comment by behdad** [comment]
It's not too much work to pull down and build graphite ourselves.

**Comment by ebraminio** [comment]
Thank you. #147 and #148
