### ISSUE TITLE
Backtrack sequence in chaining contexts format 3

### ISSUE THREAD

**Issue by johanmattssonm** [behdad/harfbuzz#140]
Hi
I looks like Harbuzz reads backtrack sequences defined in chaining contexts in the other direction for latin scripts (subtable format 3, lookup type 6). The sequence should be in writing direction but is applied in the other direction. Input and lookahead sequences seems to be in the writing direction.

Here is a test:
hb-view Test.ttf "thisisatest sihtisatest" > chaining_context.png
![chaining_context](https://cloud.githubusercontent.com/assets/350392/10430181/09b3859e-70fe-11e5-8e53-06b27b2e104a.png)

The font:
http://birdfont.org/misc/Test.ttf

The substitution:
backtrack: this
input: isa
lookahead: test

The backtrack sequence "this" matches siht instead of "this".

Cheers
Johan

**Comment by johanmattssonm** [comment]
Sorry. It looks like backtrack should be written this way.

**Comment by jfkthame** [comment]
Right. See http://www.microsoft.com/typography/otspec/gsub.htm#CCF1, and note in particular how the indexing of the backtrack sequence is reversed (i.e. the index in the backtrack sequence increases as we move further away from the beginning of the input sequence).
