### ISSUE TITLE
Syriac Abbreviation Mark rendering

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [behdad/harfbuzz#141]
The Syriac block have a control character “Syriac Abbreviation Mark” (U+070F), as Unicode Standard, this mark should be used for generating a special overline on all subsequent Syriac script letters, until the first character which is not a Syriac letter or diacritic.

I copied the text “ܐ܏ܒܓܕ” from a [Wikipedia article](https://en.wikipedia.org/wiki/Syriac_Abbreviation_Mark), when I paste into [BabelPad](http://www.babelstone.co.uk/Software/BabelPad.html) (this is using Uniscribe), I can see this overline, this line has a point at each edge and a point in the middle, but before I copy this text, I can see just a substitution glyph between the letters. I’m using Firefox, which using your text shaping engine on all platforms. So how can I see this overline?

**Comment by behdad** [comment]
We like to implement that but haven't done so far.

**Comment by behdad** [comment]
cc @jfkthame

**Comment by KrasnayaPloshchad** [comment]
cc @khaledhosny

**Comment by jfkthame** [comment]
It's not clear to me what harfbuzz can/should do about this. It's not a shaping issue; it needs to be handled during drawing of the shaped text. Is there anything to be done in HB that would facilitate that for clients?

**Comment by khaledhosny** [comment]
MS introduced a new feature for this, http://www.microsoft.com/typography/otspec/features_pt.htm#stch and https://www.microsoft.com/typography/OpenTypeDev/syriac/intro.htm#features, so probably HarfBuzz can support it. Segoe UI Historic from Windows 10 seems to include it.

**Comment by khaledhosny** [comment]
Here the result of `hb-shape` with the string above:
````
$ hb-shape seguihis.ttf 'ܐ܏ܒܓܕ'
[gid2404=4+723|gid2399=3+1589|gid2395=2+956|gid2334=1+41|gid2335=0+1524]
hb-shape seguihis.ttf 'ܐ܏ܒܓܕ' --features="+stch"
[gid2404=4+723|gid2399=3+1589|gid2395=2+956|gid2486=1+0|gid2487=1+0|gid2488=1+0|gid2487=1+0|gid2489=1+0|gid2335=0+1524]
````

So HarfBuzz is doing the substitution (the feature is implementing as a contextual substitution applying a one to many lookup), but it obviously does not handle the special positioning and does not enable it by default.

**Comment by KrasnayaPloshchad** [comment]
@khaledhosny Yes, I’m using Windows 10, these sequences works for me in BabelPad due to Segoe UI Historic font.

**Comment by jfkthame** [comment]
Oh, right - I was forgetting about the 'stch' feature. Yes, I suppose we can do that in HB, so it does become part of shaping after all.

**Comment by KrasnayaPloshchad** [comment]
I can also reproduce this issue in Firefox. First, I open this page in Firefox, click “HTML” button:
http://wymeditor.github.io/wymeditor/dist/examples/01-basic.html
Then I input following code:
```
<p style="font-family:Segoe UI Historic; font-feature-settings:'stch'">ܐ܏ܒܓܕ</p>
<p style="font-family:Segoe UI Historic; font-feature-settings:'stch' 0">ܐ܏ܒܓܕ</p>
```
The result for me is:
If 'stch' feature is closed, only substitution glyph appearing.
If 'stch' feature is opened, a short overline appearing at the position of SAM, with a dot in the middle.

**Comment by behdad** [comment]
I'll give it a try soon...

Can someone with hb-uniscribe on Win 8+ send me expected hb-shape results for a few sequences?

**Comment by behdad** [comment]
Implementing it is not that hard actually.  Working on it.

**Comment by behdad** [comment]
I also wonder if the mark should be skipped for other GSUB/GPOS processing.

**Comment by behdad** [comment]
Also, what does windows do if the mark i at the end of the word?

**Comment by khaledhosny** [comment]
Seeing that the it is contextual substitution, for this particular font I think it will not happen unless the mark if followed by at least one Syriac character, but I don’t know what it will do in case of a simple substitution (no Windows 10 here to test, and one needs to craft a special font any way).

**Comment by behdad** [comment]
Next question is to know, are zero instances of the repeating elements inserted if space is tight, or at least one?

**Comment by behdad** [comment]
Fixed.  For now, I insert at least one of each element.  Can be fixed later.

**Comment by behdad** [comment]
![abbreviation-mark](https://cloud.githubusercontent.com/assets/142891/10987139/494b7942-83e5-11e5-9e7f-579116d11b50.png)

**Comment by KrasnayaPloshchad** [comment]
OK, this is fixed, I hope the proper SAM rendering will be available in Firefox in the future.

**Comment by behdad** [comment]
Khaled, if you want to experiment with using this for Arabic subtending marks (U+0600, ...), feel free to create a font and send my way.  It would need more work since those happen in LTR context of digits, but I can give it a try.

**Comment by khaledhosny** [comment]
I was thinking exactly about this :) Will see what I can do.

**Comment by KrasnayaPloshchad** [comment]
I sent this issue into their Bugzilla.
https://bugzilla.mozilla.org/show_bug.cgi?id=560963
