### ISSUE TITLE
Add function for texts that can be annotated via interlinear annotation characters?

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [behdad/harfbuzz#142]
As Wikipedia article “[Ruby character](https://en.wikipedia.org/wiki/Ruby_character)” mentioned, there is another way of ruby annotation, which based on three interlinear annotation characters. These ad hoc characters encoded in U+FFF9, U+FFFA, U+FFFB. 

Not sure whether this Unicode based ruby annotation was implemented in HarfBuzz, and how useful it is. What does everyone think?

**Comment by behdad** [comment]
How would this work?

**Comment by jfkthame** [comment]
I think this is completely out of scope for a text-shaping engine like harfbuzz. It belongs at a higher level of layout, as it would require font-size changes as well as glyph positioning.

Whether it's worth implementing at all is another matter. Maybe the most useful "implementation", if there's actually any data being created in that form, would be a simple filter that converts such a character stream into HTML ruby markup. :)

**Comment by behdad** [comment]
Agreed.  Initially I wasn't even understanding what the chars mean.
