### ISSUE TITLE
Missing FT_LOAD_NO_HINTING causes crashes

### ISSUE THREAD

**Issue by heftig** [behdad/harfbuzz#143]
Users are seeing crashes in FreeType 2.6.1 since HarfBuzz 1.0.5:
https://bbs.archlinux.org/viewtopic.php?pid=1570725

Backtrace of such a crash (Firefox on http://chess24.com):
http://pkgbuild.com/~heftig/backtrace.tar.xz

Adding `FT_LOAD_NO_HINTING` to the default `load_flags` solves the problem:
```diff
diff --git i/src/hb-ft.cc w/src/hb-ft.cc
index b695f81..2b11882 100644
--- i/src/hb-ft.cc
+++ w/src/hb-ft.cc
@@ -84,7 +84,7 @@ _hb_ft_font_create (FT_Face ft_face, bool unref)
   ft_font->ft_face = ft_face;
   ft_font->unref = unref;
 
-  ft_font->load_flags = FT_LOAD_DEFAULT;
+  ft_font->load_flags = FT_LOAD_DEFAULT | FT_LOAD_NO_HINTING;
 
   return ft_font;
 }
```

**Comment by behdad** [comment]
Ok ok, I'm reverting that change and making a release...

**Comment by behdad** [comment]
Released 1.0.6.

**Comment by vobloeb** [comment]
May we have another try to get rid of `FT_LOAD_NO_HINTING` ? FreeType has evolved a lot and probably won't crash.

That `FT_LOAD_NO_HINTING` causes ugly visual artifacts, e.g note the space inside the word "over":

<img width="408" height="574" alt="Image" src="https://github.com/user-attachments/assets/a47b0c2b-a705-4af2-9adf-5c0523cdec55" />

**Comment by behdad** [comment]
> May we have another try to get rid of `FT_LOAD_NO_HINTING` ?

Have you seen `hb_ft_font_set_load_flags()`?

**Comment by vobloeb** [comment]
> Have you seen `hb_ft_font_set_load_flags()`?

Yes, that `hb_ft_font_set_load_flags(FT_LOAD_DEFAULT)` is exactly what fixes the spacing and that is how I found this weird default value.

but many programs -- like XFCE's dialog above -- do not set `hb_ft_font_set_load_flags(FT_LOAD_DEFAULT)`, they do not expect that the default is `FT_LOAD_NO_HINTING` and that `hb_ft_font_set_load_flags(FT_LOAD_DEFAULT)` must be set explicitly every time.

may it be better to have the sane default in harfbuzz than request every (legacy) program to work around it?

especially, the crashes it addresses to fix may be gone years ago

**Comment by behdad** [comment]
It's too late to change the default I'm afraid. I'm open to suggestions. I think filing issue with XFCE to always call this API right after creating the font is your best chance.

**Comment by behdad** [comment]
Plus, there are different hinting modes that change the advance width, so we can't properly set it anyway.

**Comment by vobloeb** [comment]
> It's too late to change the default I'm afraid.

seems so.
The recently created fonts e.g. "Noto Color Emoji" work better with `FT_LOAD_NO_HINTING`
