### ISSUE TITLE
Space kerning is not rendered properly

### ISSUE THREAD

**Issue by arifharoon** [behdad/harfbuzz#145]
Hi, Behdad!
I am the lead developer of Jameel Noori Nastaleeq font, which is the most commonly used Urdu font on  the web and desktop applications. The font is at least 7 years old and is rendered quite well in Firefox which uses Harfbuzz as text shaper.
Just recently, we did a major upgrade by implementing 'ligature kerning' feature that allows for the font's 24000+ ligatures to kern against each other with or without space. Space kerning is a required feature for Nastaliq script, as you may well be aware of it being the developer of Noto Nastaliq yourself.

This new feature is rendered as expected in Internet Explorer and Microsoft Edge. It works fine in Firefox as well but for some reason, the text is clipped from the beginning of lines. I have filed a bug report at Bugzilla here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1212668

As per discussion on bugzilla, it came to my knowledge that you worked on a major space kerning bug that was fixed two years ago:
https://bugzilla.mozilla.org/show_bug.cgi?id=761442

It seems that it could be the one that's causing regression here. With your expertise in text shaping for Web, we really need your help solving this bug. I am not exactly sure if it's directly related to Harfbuzz or some other layout rendering issue in Firefox. But at least take a look at above links and give feedback. Thank you!

**Comment by behdad** [comment]
This is a Firefox issue, and Jonathan and John are in best position to figure it out.

**Comment by behdad** [comment]
BTW, the font seems to break with this sequence:
بهبد

**Comment by khaledhosny** [comment]
Should this be closed now? The Firefox issue is already fixed.

**Comment by behdad** [comment]
Looks like it.
