### ISSUE TITLE
[util] Add --unicodes for easier entering of unicode codes

### ISSUE THREAD

**Issue by behdad** [behdad/harfbuzz#154]

**Comment by jungshik** [comment]
I was about to file a request for similar feature in hb-view/hb-shape.   At the moment, I write a file with '\uhhhh' and '\Uhhhhhh' and convert them to UTF-8 with a script before feeding the result to hb-view/hb-shape. 

If hb-* can understands '\uhhhh' and '\Uhhhhhh', it'd be handy. In that case, no new option would be necessary.

**Comment by behdad** [comment]
The --text definitely will continue accepting text only.  But the free parameter (ie, without --text), can definitely be changed...  Let me think about it.

**Comment by behdad** [comment]
Anyone feel like submitting a patch for this?
