### ISSUE TITLE
Travis seems to always pass?

### ISSUE THREAD

**Issue by behdad** [behdad/harfbuzz#171]
See eg:
https://travis-ci.org/behdad/harfbuzz/jobs/91946684

Looks like we broke our .travis.yml?  Also, I don't know what else I need to fully enable coverity.

@khaledhosny, @ebraminio, can one of you check please if you know?

**Comment by ebraminio** [comment]
The fact it silently fails made me feel really bad 😐 I have no idea yet why such error don't set errorlevel yet but fortunately it is [not like](https://travis-ci.org/behdad/harfbuzz/pull_requests) it is always passing falsely. It seems the first change made this happen was [this](https://github.com/behdad/harfbuzz/commit/ff16ef3379e06afe44b5e78b8893aeae0cee2b5b).

**Comment by behdad** [comment]
Looks to me like coverity is down or something... I can't load https://scan.coverity.com/faq#frequency

At any rate, I'm going to change travis config to NOT coverity-scan master.  Essentially disabling coverity for now.
