### ISSUE TITLE
aa7044de0cea breaks mac compilation on OS X 10.10

### ISSUE THREAD

**Issue by drott** [behdad/harfbuzz#175]
First error 

```
In file included from hb-coretext.cc:33:
In file included from ./hb-coretext.h:37:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:23:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:23:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AE.h:20:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/CarbonCore.h:155:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/UnicodeUtilities.h:304:35: error: 
      expression is not an integral constant expression
  kUCCollateStandardOptions     = kUCCollateComposeInsensitiveMask | kUCCollateWidthInsensitiveMask
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/UnicodeUtilities.h:304:35: note: 
      non-constexpr function 'operator|<(anonymous enum at
      /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/UnicodeUtilities.h:292:1)>'
      cannot be used in a constant expression
```

**Comment by behdad** [comment]
Humm, ok, let me fix this up...

**Comment by behdad** [comment]
Let me know if this fixes it.  I'll make a release soon.

**Comment by drott** [comment]
Yes, fixed with this commit, thank you! Perhaps some CI bots would help avoiding this in the future?

**Comment by behdad** [comment]
Yes, we should find CI solutions for Windows and OS X.  For Windows, we can set up Appveyor after we integrate the MSVC build system (soon).  For OS X, back when I set up TravisCI, they didn't allow both a Linux build and an OS X.  Might have changed.

cc @ebraminio

**Comment by springmeyer** [comment]
>  For OS X, back when I set up TravisCI, they didn't allow both a Linux build and an OS X

This was enabled upon request for a while but it is now public and can be enabled without request: https://docs.travis-ci.com/user/multi-os/

**Comment by behdad** [comment]
> For OS X, back when I set up TravisCI, they didn't allow both a Linux build and an OS X
> 
> This was enabled upon request for a while but it is now public and can be enabled without request: https://docs.travis-ci.com/user/multi-os/

Great.  Thanks.

**Comment by ebraminio** [comment]
@behdad Sorry my desktop machine is broken  😕 @khaledhosny Wonderful, you did the Mac one even. Would you please do the appveyor one just like OTS? My unsuccessful tries in a nutshell, are [here](https://github.com/behdad/harfbuzz/pull/112#issuecomment-132286369). I don't know if you like the use of msys2 but now it is preinstalled on appveyor despite the fact it probably not binary compatible with CCCL.

**Comment by khaledhosny** [comment]
I need to do an initial build locally as doing it by trial and error with appveyor is too slow, but I don’t have a Windows machine with a build setup right now to try building HarfBuzz on it. I’ll see if I can give it a try later.
