### ISSUE TITLE
left-vowel (e.g. U+1B3E) in Noto Sans Balinese is positioned incorrectly w.r.t. a consonant cluster 

### ISSUE THREAD

**Issue by jungshik** [behdad/harfbuzz#180]
Spun off from googlei18n/noto-fonts#572. 

U+1B3E and U+1B3F are positioned incorrectly w.r.t. a consonant cluster. U+1B3[EF] should be positioned to the left of a consonant or a consonant cluster. With a single consonant, they're positioned correctly, but w.r.t. a consonant cluster / a conjunct, they're NOT. USE on Win 10 handles them as expected. 

For instance, hb positions the glyph for U+1B3E to the right of a consonant cluster 'ka - virama - ga' in the 4th syllable in line 4a in the 1st screenshot below ( ```<U+1B13, U+1B44, U+1B15, U+1B3E>```).  It should be to the left of the consonant cluster as is shaped by USE. 

The screenshots below are taken with Edge on Windows 10 (left) and Chrome with harfbuzz (right). hb-view gave the same result as Chrome. The test page is at http://jungshik.github.io/noto/balinese/test.html and the code sequences can be easily extracted from the html source. (Noto Sans Balinese can be downloaded from there, too). 

* All three syllables in line 5 and the 4th in line 4a have this issue
![screen shot 2015-11-20 at 4 34 15 pm](https://cloud.githubusercontent.com/assets/8578343/11315302/96d1728c-8fa4-11e5-9ad1-15c2b2d7818c.png)

* 2nd syllable has this issue in the screenshot below. 
![screen shot 2015-11-20 at 4 37 18 pm](https://cloud.githubusercontent.com/assets/8578343/11315339/06781d70-8fa5-11e5-9aa4-8c42a35b91ad.png)

**Comment by jungshik** [comment]
The following case may have the same root cause as the above two cases even though both USE and harfbuzz give unexpected results but they're different from each other. (left: Edge on WIn 10, right: Chrome / hb).  This could be a bug in the font, but it's not clear. 

![screen shot 2015-11-20 at 5 16 50 pm](https://cloud.githubusercontent.com/assets/8578343/11315658/93512d9a-8faa-11e5-92da-3748e0df6a3c.png)

http://jungshik.github.io/noto/balinese/Bal_VOLT_reorder-final3.PNG 
Two syllables are ka-virama-sa-taling (<U+1B13, U+1B44, U+1B32, U+1B3E>) and ka-virama-sasak-taling (<U+1B13, U+1B44, U+1B4A, U+1B3E>). This might be the same issue as behdad/harfbuzz#180.

**Comment by NorbertLindenberg** [comment]
Jungshik, I assume wherever you said "Javanese" in this issue you really meant Balinese?

**Comment by jungshik** [comment]
Oops. Corrected. Thanks @NorbertLindenberg

**Comment by jungshik** [comment]
@behdad : have you had a chance to take a look at this ?

**Comment by behdad** [comment]
cc @jfkthame 

Would be nice to hae truly minimal test case, but guess we can go from here.

**Comment by jungshik** [comment]
My test page has a collection of minimal cases (separated by a space). Extracting each one of them from the collection should be trivial and I'm sure you know that.  

I also explicitly gave one example in the report : ```<U+1B13, U+1B44, U+1B15, U+1B3E>```  (4th one in line 4a). 

So, I'm not sure what you're looking for. Anyway, Bellos is the list of syllables that I talked about in 
https://github.com/behdad/harfbuzz/issues/180#issue-118156815 and https://github.com/behdad/harfbuzz/issues/180#issuecomment-158571616


Line 5 has 

```
<U+1b13,U+1b44,U+1b27,U+1b3e>
<U+1b13,U+1b44,U+1b28,U+1b3f> 
<U+1b13,U+1b44,U+1b31,U+1b3e>
```

The 2nd 'syllable' in line 7 is ```<U+1b1b,U+1b44,U+1b13,U+1b3e>```. 

Line 6 has ```<U+1b13,U+1b44,U+1b32,U+1b3e>  <U+1b13,U+1b44,U+1b4a,U+1b3e>```

**Comment by jungshik** [comment]
Thanks. I've just confirmed that all the cases mentioned work correctly with HB's USE. 
(4th syllable in line 4a, all three in line 5, 2nd syllable in line 7, and both syllables in line 6).
