### ISSUE TITLE
Build for iOS (armv7, arm64, i386 architecture)

### ISSUE THREAD

**Issue by dhthong92** [behdad/harfbuzz#186]
I have built lib harfbuzz on Mac OS successfully, but it only supported x86_64 architecture. Is there any way I can build it for iphoneos(armv7, armv64) or iphone simulator(i386) arch? I need it to compile Mapnik on iOS. Thanks in advance

**Comment by dhthong92** [comment]
Do I post this question in a wrong place?

**Comment by behdad** [comment]
Yes.  I have no idea how to do what you want.

**Comment by schriftgestalt** [comment]
this is how it works for freetype:
```
./configure CFLAGS="-arch x86_64 -arch arm64"
```
but it doesn't do it for harfbuzz. And I don't understand the meson settings.

**Comment by khaledhosny** [comment]
That is not how cross-compiling is done with autotools (FreeType has a special build system AFAIK), the official way is described in the documentation:
https://www.gnu.org/software/automake/manual/html_node/Cross_002dCompilation.html

For meson:
https://mesonbuild.com/Cross-compilation.html
