### ISSUE TITLE
Bad y_offset from hb_buffer_get_glyph_positions (1.1.0 regression)

### ISSUE THREAD

**Issue by tasn** [behdad/harfbuzz#187]
Hey,

There seems to be a regression with Harfbuzz 1.1.0. After updating to 1.1.0 users of Terminology (an EFL based terminal emulator) have been experiencing weird character offsets. We've narrowed down the problem to the y_offset returned by hb_buffer_get_glyph_positions.
For example, for one glyph in the 6x13 bitmap font shipped with my system, I used to get 0 as the y_offset, and now I get -1056 (16px in my case).
There's more info in the original terminology ticket ( https://phab.enlightenment.org/T2865 ), but according to one account, the cause is 44f82750807475aa5b16099ccccd917d488df703. I personally don't see how that one might be related, but it is.

This break leads to a completely unusable application.

Let me know if you need any other information.

Thanks,
Tom.

**Comment by herdz** [comment]
Please check `get_glyph_origin_for_direction` in `hb-font-private.hh`

```c
if (!get_glyph_h_origin (glyph, x, y) &&
    get_glyph_v_origin (glyph, x, y))
      {
	    hb_position_t dx, dy;
	    guess_v_origin_minus_h_origin (glyph, &dx, &dy);
	    *x -= dx; *y -= dy;
      }
```
After 44f8275 the path goes through `get_glyph_v_origin` instead of the removed `get_glyph_h_origin`. For some reason the y (`y_offset`) value comes out wrong here.

Danny.

**Comment by behdad** [comment]
Oops.  My bad.  Will fix.

**Comment by tasn** [comment]
@behdad, thanks!
Please also do a bug fixing release. We have a lot of sad terminology users at the moment. :)

**Comment by herdz** [comment]
Thanks =)

**Comment by behdad** [comment]
On it.  I created a slight mess.  Will have a fix by the time my flight lands on the other side.

**Comment by behdad** [comment]
I'm curious.  In hb_shape, I have these lines:
```

    if (c->font->has_glyph_h_origin_func ())
      for (unsigned int i = 0; i < count; i++)
	c->font->add_glyph_h_origin (info[i].codepoint,
				     &pos[i].x_offset,
				     &pos[i].y_offset);

```

ie. if glyph_h_origin_func is NOT set, it doesn't do anything.  I'm curious why you see a different behavior.

**Comment by behdad** [comment]
> ie. if glyph_h_origin_func is NOT set, it doesn't do anything. I'm curious why you see a different behavior.

The downstream bug has the answer:

```
Still not sure, but textgrid differs from textblock in shaping. It passes EVAS_TEXT_PROPS_MODE_NONE, while textblock passes EVAS_TEXT_PROPS_MODE_SHAPE. One uses the "fallback" shaper, while the other uses the "ot" shaper.
```

**Comment by behdad** [comment]
Release coming.

**Comment by behdad** [comment]
Released 1.1.2.

**Comment by tasn** [comment]
Thanks man.

**Comment by gregkh** [comment]
Fixes the issue for me, many thanks for the quick response.
