### ISSUE TITLE
Interplay of -DHB_NO_MT and "Port ft font funcs to allocated object"

### ISSUE THREAD

**Issue by springmeyer** [behdad/harfbuzz#190]
I've been building harfbuzz with `-DHB_NO_MT` since the v0.9.x series without any recognizable problems. But I'm seeing consistent and predictable crashes when built with `-DHB_NO_MT` after https://github.com/behdad/harfbuzz/commit/7918c261efd283e0428ce7836e9e42768a6aa05c that can be avoided by not adding `-DHB_NO_MT`.

In my case the calling application is Mapnik and [this code](https://github.com/mapnik/mapnik/blob/8e6e74dfa25f8444ad122a76375fcfb7bed78a98/include/mapnik/text/harfbuzz_shaper.hpp#L67-L188) is invoked within one or more threads at the same time.

So, I presume this crash is happening because:

 1) Mapnik's usage of harbuzz requires MT support because multiple threads are calling harfbuzz functions
 2) Therefore setting `-DHB_NO_MT` was incorrect
 3) And this incorrect usage should have been crashing all along.

Sound right? The fact that I did not start to see crashes until https://github.com/behdad/harfbuzz/commit/7918c261efd283e0428ce7836e9e42768a6aa05c is curious. But perhaps that is because Mapnik's usage is not depending on atomics elsewhere because the harfbuzz API usage is minimal?

**Comment by behdad** [comment]
> I've been building harfbuzz with -DHB_NO_MT since the v0.9.x series without any recognizable problems. But I'm seeing consistent and predictable crashes when built with -DHB_NO_MT after 7918c26 that can be avoided by not adding -DHB_NO_MT.
> 
> In my case the calling application is Mapnik and this code is invoked within one or more threads at the same time.
> 
> So, I presume this crash is happening because:
> 
> 1) Mapnik's usage of harbuzz requires MT support because multiple threads are calling harfbuzz functions
> 2) Therefore setting -DHB_NO_MT was incorrect
> 3) And this incorrect usage should have been crashing all along.

Correct.


> Sound right? The fact that I did not start to see crashes until 7918c26 is curious. But perhaps that is because Mapnik's usage is not depending on atomics elsewhere because the harfbuzz API usage is minimal?

Again, correct.

**Comment by springmeyer** [comment]
Thank you @behdad!
