### ISSUE TITLE
Syriac Abbrevation Mark doesn’t cover all Syriac letters sometimes

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [behdad/harfbuzz#191]
I found HarfBuzz having a small problem for Syriac Abbrevation Mark implemetation.

I made a small test in Firefox 45 Nightly, which included HarfBuzz 1.1.0. When SAM is followed by many Syriac letters, the length of abbrevation seems shorter then the length of subsequent letters sometimes.
![screenshot_2015-12-05-20-13-47](https://cloud.githubusercontent.com/assets/10364351/11607842/0ebb5cec-9b92-11e5-9d3a-2d4dd55c5164.png)
Where LibreOffice for Windows performanced:
![default](https://cloud.githubusercontent.com/assets/10364351/11607848/386adde2-9b92-11e5-9484-5c9cd8c086df.PNG)
In this case SAM looks covering all subsequent letters all the time, and the end of overline seems aligned with a vertical line.

**Comment by jfkthame** [comment]
This happens because harfbuzz extends the SAM by adding copies of the "repeating" element, and that has a fixed width; so the line grows by discrete increments. I've just proposed a change (PR #192) that aims to make it more precise, by adjusting the spacing of the repeated elements when necessary.

**Comment by jfkthame** [comment]
BTW, there's a test build of Firefox (Nightly) including the PR #192 patch available at http://archive.mozilla.org/pub/firefox/try-builds/jkew@mozilla.com-1266a32702efb8e8e083012f815a65806d44dfd0/ if you want to try it and see the effect.

**Comment by KrasnayaPloshchad** [comment]
> BTW, there's a test build of Firefox (Nightly) including the PR #192 patch available at http://archive.mozilla.org/pub/firefox/try-builds/jkew@mozilla.com-1266a32702efb8e8e083012f815a65806d44dfd0/ if you want to try it and see the effect.

OK, this build performanced better. BTW I also tested in a virtual machine which installed Windows 7, these sequentes works only after installing Segoe UI Historic font, the Estrangelo Edessa font is ceased to work, that’s odd.

**Comment by jfkthame** [comment]
Check the version of the Estrangelo Edessa font. It's probably an older version that doesn't support the SAM.

**Comment by KrasnayaPloshchad** [comment]
> Check the version of the Estrangelo Edessa font. It's probably an older version that doesn't support the SAM.

The version number is 5.0, this version seems works with IE.

**Comment by jfkthame** [comment]
If it's the same as the "version 5.0" I have looked at, it doesn't have the 'stch' feature; that first appears in version 6.0, which does work in harfbuzz/firefox.

So if it's indeed working with IE, I suppose IE must be using some other ad hoc mechanism to render the abbreviation mark.

**Comment by KrasnayaPloshchad** [comment]
> If it's the same as the "version 5.0" I have looked at, it doesn't have the 'stch' feature; that first appears in version 6.0, which does work in harfbuzz/firefox.
>
> So if it's indeed working with IE, I suppose IE must be using some other ad hoc mechanism to render the abbreviation mark.

Oh, I understand. I rembered Estrangelo Edessa 6.0 is shipped in Windows 8+, but I have no Windows 8 for test.

**Comment by jfkthame** [comment]
If you want to test more versions, you can get a range of VMs from Microsoft[1] with various versions of Windows and IE (and of course you can also download Firefox builds to them for testing).

But I think we can safely say that the SAM works in harfbuzz if (and only if) the font supports it via the 'stch' feature. In general, that will only be the case for reasonably up-to-date font versions.

[1] https://dev.windows.com/en-us/microsoft-edge/tools/vms

**Comment by KrasnayaPloshchad** [comment]
Sure, I think the SAM implementation in HarfBuzz would be better if PR #192 is adopted.

**Comment by KrasnayaPloshchad** [comment]
👍

**Comment by KrasnayaPloshchad** [comment]
Seems fixed. Thank you Behdad. 👍
