### ISSUE TITLE
New Tai Lue vowel reordering

### ISSUE THREAD

**Issue by mhosken** [behdad/harfbuzz#193]
Unicode 8 changed the way New Tai Lue works. It was switched from logical ordering (as per Indic) to visual ordering (as per Thai). This seems to be reflected in the USE tables in harfbuzz, but not in the indic tables (where (M, L) should become (M, R), I think). Users are being impacted by this, so a quick fix would be appreciated.
Of course another approach for New Tai Lue is to say: if there is no GDEF or GSUB then don't do anything, given the net result of this change to the ordering is that no shaping is needed any longer.

**Comment by behdad** [comment]
> This seems to be reflected in the USE tables in harfbuzz, but not in the indic tables (where (M, L) should become (M, R), I think). Users are being impacted by this, so a quick fix would be appreciated.

This doesn't make sense.  After this commit:
```
commit 3704628d1f124234324b5f2bdd5fdd61c14c7801
Merge: 1aaa7d6 5eb939d
Author: Behdad Esfahbod <behdad@behdad.org>
Date:   Mon Jan 19 16:15:00 2015 -0800

    Merge pull request #77 from roozbehp/master
    
    Change New Tai Lue shaping engine from SEA to default
```

New Tai Lue goes through the generic shaper.  So what the Indic table has is irrelevant.  The Indic table will be fixed when we update it to Unicode 8.0, but there is not user-visible bug.
