### ISSUE TITLE
Port test suite to use hb-ot-font (needs implementing glyph names in hb-ot-font)

### ISSUE THREAD

**Issue by srl295** [behdad/harfbuzz#197]
see: https://gist.github.com/srl295/18a99527c8fd8e11b83b
- AIX 7.1, xlC

**Comment by khaledhosny** [comment]
Most of the failing tests seem to be from missing glyph names, which probably indicates that you are building without HarfBuzz support, since the internal font functions don’t yet support glyph names.

**Comment by khaledhosny** [comment]
The difference in `cluster.tests` seems to be due fallback positioning, I’m not sure why the internal font function make a difference here, but I can reproduce the difference even with cluster level 0:
````
hb-unicode-encode U+0078,U+030A,U+0058,U+030A | hb-shape fonts/sha1sum/6466d38c62e73a39202435a4f73bf5d6acbb73c0.ttf --font-funcs=ft
[gid2=0+1083|gid4=0@-555,-8+0|gid1=2+1200|gid4=2@-614,349+0]
hb-unicode-encode U+0078,U+030A,U+0058,U+030A | hb-shape fonts/sha1sum/6466d38c62e73a39202435a4f73bf5d6acbb73c0.ttf --font-funcs=ot
[gid2=0+1083|gid4=0@-542,-8+0|gid1=2+1200|gid4=2@-601,349+0]
````

**Comment by behdad** [comment]
> Most of the failing tests seem to be from missing glyph names, which probably indicates that you are building without HarfBuzz support, since the internal font functions don’t yet support glyph names.

Khaled meant: "you are building without FreeType support".

I'll take a look at implementing glyphnames in hb-ot as well as switching test suite to run against hb-ot by default.

I'll check the cluster differences soon.

**Comment by khaledhosny** [comment]
All those 8-letter, CamleCase, type-related library names are confusing 😄.

**Comment by srl295** [comment]
Thanks to you both for taking a look at this, I really had no idea where to start. I should be building with freetype but I will go back and check the logs.

**Comment by srl295** [comment]
```
…
Requested 'freetype2 >= 12.0.6' but version of FreeType 2 is 9.20.3
…
$ rpm -q freetype2-devel
freetype2-devel-2.3.9-1
```

**Comment by srl295** [comment]
So that did it… everything passed with freetype2 finally detected. Only these skips (below).

```
SKIP: check-defs.sh
SKIP: check-libstdc++.sh
SKIP: check-static-inits.sh
SKIP: check-symbols.sh
```

So…  maybe the bug here is that those test cases should be "SKIP if no freetype2" instead of "FAIL"?

**Comment by behdad** [comment]
> So… maybe the bug here is that those test cases should be "SKIP if no freetype2" instead of "FAIL"?

At some point we'll get the shaping tests pass with or without freetype.  So, not marking them SKIP for now...  Sorry about the confusion though.

**Comment by srl295** [comment]
Ok. So, close this issue or repurpose it?

**Comment by ebraminio** [comment]
Adding a search keyword: hb_font_get_glyph_name
