### ISSUE TITLE
Chakma Script not supported on Firefox browser yet

### ISSUE THREAD

**Issue by Bivuti** [behdad/harfbuzz#200]
Hi,
I attached some example by using webfont with two browser (Firefox and Chrome). I attached also webfont (SuzMorz) for your kind necessary action please.

I would be happy if you need any information about SuzMoriz font.

I look forward your next feedback.

Best Wishes
Bivuti Chakma

[I found some new problem on browser.zip](https://github.com/behdad/harfbuzz/files/67352/I.found.some.new.problem.on.browser.zip)

**Comment by behdad** [comment]
We looked into this.  It's a bug in the font.  The font has a 'cakm' script system in the GSUB table which has bogus features.  Remove that and it should work.
