### ISSUE TITLE
Build issue with 1.1.3 in Chromium

### ISSUE THREAD

**Issue by drott** [behdad/harfbuzz#212]
../../third_party/harfbuzz-ng/src/hb-ot-tag.cc:931:1: error: unused function 'test_langs_sorted' [-Werror,-Wunused-function]
test_langs_sorted (void)
^

Would you have a #define for test-compilation or something that we can use here?

**Comment by behdad** [comment]
Humm.  So, "static inline" functions in header files are ignored, but not .cc files?  Ok, I guarded it.
