### ISSUE TITLE
hb-ft doesn't scale glyph extents

### ISSUE THREAD

**Issue by mhosken** [behdad/harfbuzz#215]
Looking at hb_ft_get_glyph_extents, I don't see that the results are scaled at all as compared with hb_ft_get_glyph_h_advance.

The reason I flag this is that in the fallback shaper, I am seeing that a dumb font is having some of its over striking diacritics that are considered marks by Unicode, shifted from their default dumb position. This is happening in all kinds of applications. I tracked it down to hb-ot-shape-fallback where position_mark is not getting a zero y_offset adjustment for BELOW diacritics from the line:

````
pos.y_offset = base_extents.y_bearing + base_extents.height - mark_extents.y_bearing
````

This is odd since if the value were 0 then the scaling wouldn't matter, but the value isn't 0 and therefore the scaling becomes significant (y_offset ends up at ~8000 with the base having an advance of ~40000). I am leary of this line. It seems to be trying to attach the diacritic to the bottom of the base character, regardless of how much gap the font is designed with. Is there some way for a font to say: I know what I'm doing, even if I'm dumb, please just lay me out in sequence with 0 offsets and simple advances?

**Comment by khaledhosny** [comment]
> Is there some way for a font to say: I know what I'm doing, even if I'm dumb, please just lay me out in sequence with 0 offsets and simple advances?

A GPOS table (even an empty one), should do that, no?

**Comment by mhosken** [comment]
Yes it does. Although I'm still not sure I like the attempt at automatic placement. But I have no better ideas at the moment.

**Comment by khaledhosny** [comment]
I think the non-scaling of glyph extents is still a bug.

**Comment by behdad** [comment]
What scaling are you talking about?!  I'm sure this code is tested.  The shift you see in advance func is because those are returned in 16.16, whereas extents are returned in 26.6.

**Comment by behdad** [comment]
@mhosken Can we close this now?

**Comment by mhosken** [comment]
Yup fine.
