### ISSUE TITLE
Several scripts are misbehaviored on Firefox

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [behdad/harfbuzz#219]
Recently I found Brahmi, and ZWJ for Syriac were reported misbehaviored on Firefox. These bugs repored at:
https://bugzilla.mozilla.org/show_bug.cgi?id=1148266
https://bugzilla.mozilla.org/show_bug.cgi?id=561605
I don’t know they are affacted by Firefox itself or HarfBuzz.

**Comment by behdad** [comment]
> I don’t know they are affacted by Firefox itself or HarfBuzz.

If you don't, either figure out (by testing with hb-view), or let downstream developers debug.  Thanks.
