### ISSUE TITLE
Automatic ABI compliance checker in CI

### ISSUE THREAD

**Issue by ebraminio** [behdad/harfbuzz#221]
This is just an idea that I don't know even is it feasible or done already or not, there is an stress that harfbuzz development wouldn't break its ABI compatibility so maybe it would not be a bad idea to use this tool, [ABICC](http://ispras.linuxbase.org/index.php/ABI_compliance_checker), somehow in the CI to check if it is not happened accidentially.

**Comment by behdad** [comment]
That would be nice indeed, if someone wants to set it up.
