### ISSUE TITLE
Safe-to-break API

### ISSUE THREAD

**Issue by behdad** [behdad/harfbuzz#224]
Moving from:
https://bugs.freedesktop.org/show_bug.cgi?id=71443

We like to add bits to the buffer to return "safe-to-break-here", which means, if you break text here and shape the two sides separately, you get the same result as shaping together.  This is useful for performant line-breaking.

Starting sketch here:
https://gist.github.com/behdad/149ae8947c11afddc560

**Comment by behdad** [comment]
Work-in-progress branch here: https://github.com/behdad/harfbuzz/commits/wip-unsafe-to-break

**Comment by behdad** [comment]
Sample run:
```sh
$ ./hb-shape Lobster.ttf Lobster  --show-flags [L=0+776|o=1+899|b_s=2+1636#2|t=4+547#2|e=5+786#2|r=6+770#2]
```

**Comment by behdad** [comment]
cc @khaledhosny @simoncozens

**Comment by khaledhosny** [comment]
Thanks Behdad, I’ll have a look. I’m just wondering, does this help with breaking inside ligatures anyhow? I assume it will be a unsafe-to-break place, but then I’ll just need to reshape, no other shortcut? I’ve been trying to address breaking inside ligatures in Scribus (https://github.com/HOST-Oman/scribus/issues/144) and all we did so far is to just disallow line breaking there.

**Comment by behdad** [comment]
Yeah, breaking inside a cluster needs reshape.  Breaking inside a Unicode grapheme also needs reshape.  This API identifies additional places that need a reshape.

**Comment by kelvin13** [comment]
any updates on this? if this doesn't work what is everyone using for linebreaking currently then

**Comment by eaenet** [comment]
Hi Behdad, do you expend to get back to working at this in the near term? Anything I can do to help? We'd like to start using this for line breaking in Blink.
Thanks!

**Comment by behdad** [comment]
> Hi Behdad, do you expend to get back to working at this in the near term? Anything I can do to help? We'd like to start using this for line breaking in Blink.

Yes, I like to.  Wasn't high-priority. Will try to have something testable this quarter.

**Comment by behdad** [comment]
Reopening, to fix GPOS, and non-Arabic complex shapers.

**Comment by behdad** [comment]
Fixed all:
    [unsafe-to-break] Flag in Thai PUA shaping
    [unsafe-to-break] Flag in Hangul shaper
    [unsafe-to-break] Flag during mark attachment
    [unsafe-to-break] Flag during cursive positioning
    [unsafe-to-break] Flag during kerning
    [unsafe-to-break] Flag during fallback positioning
    [unsafe-to-break] Be careful with flag propagation when merging clusters
    [unsafe-to-break] Mark Indic-like clusters as unsafe-to-break

Not tested.  Adding a verification step to test suite and possibly hb-shape to verify safe-to-break points.

**Comment by khaledhosny** [comment]
I’m wondering, can this flag be used for letter-spacing as well as it seems to handle cursive and mark attachment, or do one still need to check Unicode grapheme clusters boundaries?

**Comment by behdad** [comment]
> I’m wondering, can this flag be used for letter-spacing as well as it seems to handle cursive and mark attachment, or do one still need to check Unicode grapheme clusters boundaries?

I have another message in my drafts folder for exposing Arabic and cursive joining.  This flag is much more broad.  A long chain-context match marks the entire match range as unsafe-to-break.

**Comment by eaenet** [comment]
Thanks so much Behdad, looks great and works like a charm!

One small suggestion:
Having the hb_glyph_info_t mask field hold the flags post-shape is a little weird from an API perspective but makes sense on the implementation side.
How about changing it to be a union, thereby making the API more explicit?

union {
  hb_mask_t mask;
  hb_glyph_flags_t flags
}

**Comment by behdad** [comment]
> Thanks so much Behdad, looks great and works like a charm!

Great to hear!

> One small suggestion:
> Having the hb_glyph_info_t mask field hold the flags post-shape is a little weird from an API perspective but makes sense on the implementation side.

Previously mask was unused publicly.  The fact that hb_mask_t was even exposed is a mistake in retrospect.  So I'm fine trying to repurpose it to the extent possible.

> How about changing it to be a union, thereby making the API more explicit?
> 
> union {
> hb_mask_t mask;
> hb_glyph_flags_t flags
> }

Humm. The question would be whether all compilers we care about allow unnamed unions...  Another hesitation I have is, we might not want to allocate all 32 bits of the mask to glyph flags at this time...  Anyway.  I'll think about it.

One alternative would be to add accessor function with a duplicate macro implementation, like `hb_glyph_info_get_glyph_flags()` that does the access and cast.

**Comment by eaenet** [comment]
An assessor might be the easiest, either way it's not a big deal. Love the functionality!

**Comment by behdad** [comment]
This is all fixed now. :)
