### ISSUE TITLE
Add harfbuzz to Travis apt-package-whitelist

### ISSUE THREAD

**Issue by brawer** [behdad/harfbuzz#225]
If harfbuzz was in the [travis apt-package-whitelist](https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise), clients of harfbuzz could simply declare harfbuzz as one of their build dependencies. Currently, clients need to check out and re-build harfbuzz from scratch, which takes a bit of time for each and every change.

The whitelisting process of Travis is described in their [README file](https://github.com/travis-ci/apt-package-whitelist/blob/master/README.md).

**Comment by brawer** [comment]
Filed https://github.com/travis-ci/apt-package-whitelist/issues/2402.

**Comment by behdad** [comment]
But such pulled-in HarfBuzz will be rather old.  Fine for many font projects though.

**Comment by behdad** [comment]
Closing here.  Thanks for the filing with travis.
