### ISSUE TITLE
wrong justify with marks in libre office

### ISSUE THREAD

**Issue by hubaishan** [behdad/harfbuzz#226]
wrong justify with marks in libre office
![2016-02-13 17_36_09-](https://cloud.githubusercontent.com/assets/2285457/13028187/63a018ca-d278-11e5-9a74-e20bb90d0614.png)

**Comment by khaledhosny** [comment]
That is a bug in LibreOffice and should be reported there. LibreOffice (utterly broken) justification code is independent of HarfBuzz.
