### ISSUE TITLE
hb-blob.cc:107: Undefined Behaviour ?

### ISSUE THREAD

**Issue by dcb314** [behdad/harfbuzz#227]
[hb-blob.cc:107]: (warning) Invalid test for overflow 'data+length<data'. Condition is always false unless there is overflow, and overflow is Undefined Behaviour.

  data + length < data /* overflows */ ||

**Comment by behdad** [comment]
Good point.  Thanks.  Is unsigned-int overflow undefined as well?  Do you have suggested replacement?  How about:

  (uintptr_t)-1 - data > length

**Comment by dcb314** [comment]
>Is unsigned-int overflow undefined as well? 

No. See 

http://stackoverflow.com/questions/18195715/why-is-unsigned-integer-overflow-defined-behavior-but-signed-integer-overflow-is

>Do you have suggested replacement? 

The test for overflow looks mostly pointless to me. Suggest remove.

**Comment by behdad** [comment]
> The test for overflow looks mostly pointless to me. Suggest remove.

Good point.  The input must be valid.  However, this was NOT the case in one incident, and that's how the code was introduced.  But I believe the 2GB check handles that already. See:

https://github.com/behdad/harfbuzz/commit/7d5e7613ced3dd39d05df83ca7e8952cbecd68f6
