### ISSUE TITLE
Cantarell glyphs with mark-to-mark anchor are made zero-width

### ISSUE THREAD

**Issue by madig** [behdad/harfbuzz#228]
A few users on 1.2.0 reported that Cantarell (https://git.gnome.org/browse/cantarell-fonts/tree/otf) is broken, glyphs that have a mkmk anchor like 'Ü', 'ü' and /aring are made zero-width. I saw #211 and tried to order `mkmk` after `mark`, but that didn't help... what do I have to do?

**Comment by behdad** [comment]
I got this report as well but have not got to look into it yet.  The change we made was to zero mark advances by GDEF rather than Unicode properties.  So, if those glyphs have GDEF glyph class 3, then it's definitely a font bug.

**Comment by behdad** [comment]
Just checked.  Definitely faulty Cantarell.
https://bugs.freedesktop.org/show_bug.cgi?id=94228
What versions of the font are affected?

cc @dcrossland

**Comment by behdad** [comment]
Upstreamed: https://bugzilla.gnome.org/enter_bug.cgi?product=cantarell-fonts

**Comment by madig** [comment]
Okay, I think I found the problem. FontForge tries to determine the glyph class automatically by default, and I copied some mark-to-mark base anchors to glyphs like 'Ü' because FF isn't clever enough to search base glyphs/marks for anchors when using the compose-glyph-function. My intent was that e.g. 'Ǖ' can be composed from 'Ü' and macron with correct diacritics placement. Apparently that makes FF think 'Ü' is a mark.

Should mkmk anchors *only ever* be used on marks? Fira Sans and Source Sans Pro don't seem to put any mkmk anchors on non-marks. But then how would a shaping engine compose 'Ǖ' from 'Ü' and macron?

**Comment by jfkthame** [comment]
On 21/2/16 16:07, Nikolaus Waxweiler wrote:
> Okay, I think I found the problem. FontForge tries to determine the
> glyph class automatically by default, and I copied some mark-to-mark
> base anchors to glyphs like 'Ü' because FF isn't clever enough to search
> base glyphs/marks for anchors when using the compose-glyph-function. My
> intent was that e.g. 'Ǖ' can be composed from 'Ü' and macron with
> correct diacritics placement. Apparently that makes FF think 'Ü' is a mark.
>
> Should mkmk anchors /only ever/ be used on marks? Fira Sans and Source
> Sans Pro don't seem to put any mkmk anchors on non-marks. But then how
> would a shaping engine compose 'Ǖ' from 'Ü' and macron?

Where Ü is a single (precomposed) glyph, placing macron over it would be 
a job for 'mark', not 'mkmk'; in this scenario, Ü is serving as the base.

Ǖ only involves 'mkmk' if you're composing it from the base glyph U + 
the dieresis (using 'mark') and then macron (using 'mkmk').

JK

**Comment by madig** [comment]
Ah, so I'm simply going to replace the `mkmk` anchors in the precomposed base glyphs with `mark` :) Thanks!

**Comment by khaledhosny** [comment]
Also in FontForge you can explicitly set glyph classes, which is what I always do, you never know what surprising results a heuristic can give.

**Comment by rhertzog** [comment]
@madig What was the first version of cantarell that had this bug?

**Comment by madig** [comment]
No idea. But it was introduced after I started working on it ;)
