### ISSUE TITLE
Incorrect display of 'å' character

### ISSUE THREAD

**Issue by Daerandin** [behdad/harfbuzz#229]
With harfbuzz 1.2 on Arch Linux, I am seeing incorrect display of the 'å' character within several gtk applications. It affects both uppercase and lowercase, Å and å.

Specifically, the letter seems to render with zero width. I can seemingly type infinite 'å' in one spot. I have seen this behaviour in Thunar, Pidgin, File selector in Firefox and Thunderbird.

It seems to be specifically related to harfbuzz 1.2 as the issue is gone when I downgrade to version 1.1.3 without touching any other installed packages.

So far I have not seen this behaviour with any other character.

**Comment by khaledhosny** [comment]
Duplicate of #228.
