### ISSUE TITLE
attachment calculation error

### ISSUE THREAD

**Issue by mhosken** [behdad/harfbuzz#233]
Consider the following sequence U+1014 U+1037 U+103A. If rendered using the DFLT shaper in uniscribe, we get:
> [u1014=0+609|u1037=1@24,0+0|u103A=2@-26,0+0]

and in harfbuzz:

> [u1014=0+609|u1037=0@24,0+0|u103A=0@-81,0+0]

Both U+1037 and U+103A are attached using mark attachment to the base U+1014. Notice the difference of 55 in the final glyph offset. This is the width of the u1037. I think what is happening is that the final offsets are calculated (absolute positions are turned into offsets from current advance) in uniscribe after the marks are zeroed, and before in harfbuzz.

I don't think this is necessarily, an issue with marks being zeroed early in DFLT in uniscribe or anything.

And yet, for further evidence and confusion, consider the sequence U+1000 U+103C U+102D. 103C and 102D are marks and the results are, for uniscribe:
> [u103C.alt.wide=0+0|u1000=1@172,0+1174|u102D=2@-54,0+0]

and for harfbuzz:
> [u103C.alt.wide=0+0|u1000=0@172,0+1174|u102D=0@118,0+0]

The sequence involves attaching the 102D to the 1000 at a position of -54 to the advance of U+1000, and then kerning (shift + advance) of +172 to move the U+1000 away from the zero widthed U+103C. Here the relative position of the 102D to the 1000 is being preserved by uniscribe in that as the U+1000 is shifted right, the 102D naturally goes with it. OTOH the harfbuzz position seems to move the U+102D doubly further right. This seems to imply that the offset calculation is being done late rather than early and that a correction is being applied as well, whereas the uniscribe case seems to imply offset calculation is done early. All very confusing!

Here's my guess: attachment in uniscribe is stored either in terms of distance from the advance edge of the base or from the base's origin, rather than as absolute positions; and then final offsets are calculated late, after marks are zeroed.

**Comment by behdad** [comment]
Which HB version exactly?  I had broken this in the work week with you, and then fixed it last week.  Please test with master.

**Comment by mhosken** [comment]
> Which HB version exactly?  I had broken this in the work week with you, and then fixed it last week.  Please test with master.

Ahh. Great. Glad it was so easy to fix :) Yes it seems to be fine now.

**Comment by behdad** [comment]
BTW, this is relevant to what you reported today on the mailing list...
