### ISSUE TITLE
Add support for the OpenType MATH table

### ISSUE THREAD

**Issue by fred-wang** [behdad/harfbuzz#235]
cc'ing @khaledhosny @alexgcastro

This was raised again on https://github.com/khaledhosny/libmathview/issues/22, so I'm just opening it for the record...

Besides TeX engines and LibreOffice, I'm particularly interested in using it for math layout in Web engines. We already have code to parse the MATH table in Gecko & WebKit which I'd like to get rid of and I don't want to duplicate it again when we try and port the MathML layout code to Blink ;-)

**Harfbuzz's work in progress:** https://github.com/behdad/harfbuzz/pull/241
**Blog post:** http://frederic-wang.fr/opentype-math-in-harfbuzz.html

Gecko's implementation:
http://hg.mozilla.org/mozilla-central/file/tip/gfx/thebes/MathTableStructures.h
http://hg.mozilla.org/mozilla-central/file/tip/gfx/thebes/gfxMathTable.cpp
http://hg.mozilla.org/mozilla-central/file/tip/gfx/thebes/gfxMathTable.h

WebKit's implementation:
http://trac.webkit.org/browser/trunk/Source/WebCore/platform/graphics/opentype/OpenTypeMathData.h
http://trac.webkit.org/browser/trunk/Source/WebCore/platform/graphics/opentype/OpenTypeMathData.cpp

XeTeX's implementation:
https://sourceforge.net/p/xetex/code/ci/master/tree/source/texk/web2c/xetexdir/MathTable.h
https://sourceforge.net/p/xetex/code/ci/master/tree/source/texk/web2c/xetexdir/XeTeXOTMath.h
https://sourceforge.net/p/xetex/code/ci/master/tree/source/texk/web2c/xetexdir/XeTeXOTMath.cpp

libmathview's implementation:
https://github.com/khaledhosny/libmathview/blob/master/src/backend/MathFont.cc

Old messages from the mailing list:
https://lists.freedesktop.org/archives/harfbuzz/2012-December/002741.html
https://lists.freedesktop.org/archives/harfbuzz/2015-March/004740.html

**Comment by KrasnayaPloshchad** [comment]
I am strongly agree with you. Since OT specification has introduced math related typesrttings, MATH table should become part of shaping.
https://www.microsoft.com/typography/otspec/math.htm

**Comment by fred-wang** [comment]
Just to avoid duplicate efforts: I started to look at the harfbuzz code this morning and I will try to submit a first proposal for this soon.

**Comment by fred-wang** [comment]
I just pushed a first commit with the basic structures in a688ff16300c40aea71faa74545d20e8c58e10c5
Feedback welcome.

**Comment by twardoch** [comment]
Do I understand correctly that MATH support in Harfbuzz would utilize a somewhat separate API that would require some more modular shaping process? I mean, I haven’t read Murray Sargent’s [“Unicode Nearly Plain-Text Encoding of Mathematics”](http://unicode.org/notes/tn28/UTN28-PlainTextMath-v3.pdf) in its entirety, but even the title suggests that it’s “nearly” plain text i.e. does require some formatting commands. Also, this notation does require some mathematically-aware parsing which is clearly on a higher level than what Harfbuzz typically does. And there are tons of other notations (several MathML flavors, TeX and its subsets implemented in projects such as [KaTeX](https://github.com/Khan/KaTeX) or [MathJax](https://www.mathjax.org/) etc.). 

So I imagine that using a MATH implementation in HB wouldn’t be as simple as feeding in some plain-text series of Unicodes plus some lightweight indicators of OT features but would require a more programmatic approach where you explicitly keep calling some functions at the right moments, but you generally need to “know what you’re doing” — right?

**Comment by twardoch** [comment]
Just for the sake of completeness, I'm also including a related [blog post by Murray Sargent](https://blogs.msdn.microsoft.com/murrays/2010/08/30/linear-format-notations-for-mathematics/). 

And, to rephrase my question — do I understand correctly that, at least initially, parsing notations such as Murray’s proposed nearly-plain-text one, or other ones, would — at least initially — be out of scope for the MATH integration in Harfbuzz and that such external parsers would need to utilize some Harfbuzz API specific to MATH in order to perform the shaping?

**Comment by khaledhosny** [comment]
HarfBuzz will be providing API to query MATH table, the math layout will be done by higher layers.

**Comment by fred-wang** [comment]
> HarfBuzz will be providing API to query MATH table, the math layout will be done by higher layers.

Yes, my personal plan is to allow Harfbuzz to parse/sanitize the MATH table and expose its data through a simple API so we do not need to duplicate that logic in Gecko/WebKit/Blink. It seems that Khaled has a similar need for libmathview (https://github.com/khaledhosny/libmathview/issues/22#issuecomment-199886225) and probably the code could be reused for TeX engines, LibreOffice and other math applications that rely on Harfbuzz.

But actually contrary to what I said above, I ended up importing WebKit's OpenType MATH code to my Blink branch for now so I'm not sure I'll actively continue working on this in the short term (probably I should have already done that when implementing MATH support in Gecko/WebKit, but anyway...)

For the record, a somewhat higher-level API that could be useful: 1) given a glyph index for a stretchy character and some target size select/measure/draw the appropriate stretched version using the MathVariants subtable 2) similarly, given a glyph index for a big operator character select/measure/draw the appropriate displaystyle version using the MathVariants table and the DisplayOperatorMinHeight constant.

**Comment by KrasnayaPloshchad** [comment]
This would be helpful if application or library need required glyphs for mathmantical typesetting.

**Comment by KrasnayaPloshchad** [comment]
For some higher-level layouts, these can be develop as individual library or develop within text render engine as Pango, but after HarfBuzz got basic support for MATH table, these libraries can be develop directly based/rely on corresponding API of HarfBuzz.

**Comment by behdad** [comment]
> For the record, a somewhat higher-level API that could be useful: 1) given a glyph index for a stretchy character and some target size select/measure/draw the appropriate stretched version using the MathVariants subtable 2) similarly, given a glyph index for a big operator character select/measure/draw the appropriate displaystyle version using the MathVariants table and the DisplayOperatorMinHeight constant.

Can you possibly sketch the API?

**Comment by fred-wang** [comment]
I just updated my harfbuzz MATH branch against version 1.2.5 and provided a very low-level API to access the desired properties. It is still not tested at all, but you can always find the latest update at https://github.com/fred-wang/harfbuzz/compare/master...fred-wang:MATH

In the OpenType MATH spec, it is indicated when offsets may be NULL but never indicated when they must not be NULL. I think this was discussed in the past for OTS and @behdad was in favor of assuming all offsets can potentially be NULL, so that's why I introduced many has_* and get_* functions.

Here is my initial proposal for a slightly higher level API. I'll try and start working on it, but feedback are welcome:

1) A way to know whether a font has a MATH table:

  HB_EXTERN hb_bool_t hb_ot_layout_has_math_data (hb_face_t *face)

2) A way to retrieve MATH constants.

Probably move the OT::MathConstants::Names enum into an hb_ot_layout_math_constants_t. Just like OT::MathConstants::get_value, there would be two versions: one that returns a float (for percent constants) and one that returns a hb_position_t value (for all the other constants). If MathConstants is absent, the return value is null.

  HB_EXTERN hb_position_t hb_ot_layout_get_math_constant (hb_font_t *font, OT::MathConstants::Names name)
  HB_EXTERN float hb_ot_layout_get_math_constant (hb_face_t *face, OT::MathConstants::Names name)

3) A way to retrieve italic correction and top accent attachment for a glyph, with fallback value zero:

  HB_EXTERN hb_position_t hb_ot_layout_get_math_italic_correction (hb_font_t *font, GlyphID glyph_id)
  HB_EXTERN hb_position_t hb_ot_layout_get_math_top_accent_attachment (hb_font_t *font, GlyphID glyph_id)

4) A way to retrieve math kernings. I have not really thought about that and I'll probably not consider it for now (It's currently not used by Gecko/WebKit and the XeTeX implementation seemed weird last time I read it).

We should have either a way to know if a kerning is absent or provide a zero fallback value (not sure which option is best). Just like OT::MathKern::get_value, I've used hb_position_t for correction heights but I wonder whether it's better to base the search on the MathValueRecord::value SHORT.

  enum hb_ot_layout_math_kern_type_t {
     HB_OT_LAYOUT_MATH_KERN_TYPE_TOP_RIGHT,
     HB_OT_LAYOUT_MATH_KERN_TYPE_TOP_LEFT,
     HB_OT_LAYOUT_MATH_KERN_TYPE_BOTTOM_RIGHT,
     HB_OT_LAYOUT_MATH_KERN_TYPE_BOTTOM_LEFT
  };
  HB_EXTERN hb_position_t hb_ot_layout_get_math_kerning (hb_font_t *font, GlyphID glyph_id, hb_ot_layout_math_kern_type_t kern_type, hb_position_t correction_height)

I also wonder whether it could be helpful to instead have an API to shape some basic scriped expressions like A^B, A_B, A^B_C where base A and scripts B, C are just simple glyphs... In that case a way to retrieve the maximum advances would be helpful for Web engines (see 8).

5) A way to get a display operator glyph.

It will be up to the higher-level math engine to know whether the list of glyphs that can potentially have a display operator before calling this funcion. These are essentially the glyphs of characters listed as "largeop" operators on https://www.w3.org/TR/MathML3/appendixc.html as well as their mirrored glyphs obtained by character-level or glyph-level mirroring. Maybe an optional boolean "mirrored" can be passed to ask harfbuzz to calculate the mirrored form of the provided glyph to make this more convienient for the caller.

The basic idea is to check the array of OT::MathGlyphVariantRecord the vertical OT::MathGlyphConstruction associated to the base glyph and continue until we find one that has height larger than OT::MathConstants::DisplayOperatorMinHeight.

The best fallback value is probably the glyph with the largest height found and at worse the base glyph (some fonts include the base glyph in the array of OT::MathGlyphVariantRecord, other do not).

The definition of height is not clear. The MATH spec often uses this word for glyph ascent, it could also be OT::MathGlyphVariantRecord::advanceMeasurement and finally for Gecko/WebKit I've used the glyph ascent + glyph descent...

From my experience, the result obtained with the help of OT::MathConstants::DisplayOperatorMinHeight was poor (not sure whether it's a bug in the math fonts or a bad undestanding of the MATH spec but mail exchange with Murray Sargent did not clear my doubts). So it could be convenient to have an optional min_height_factor parameter to ensure that display operator height is at least min_height_factor times larger than the base glyph. Gecko uses min_height_factor = 2.0 for integrals (a sublist of the "largeop" operators) and √2 for other operators ; WebKit uses √2 and I think XeTeX has something like 3/2.

  HB_EXTERN GlyphID hb_ot_layout_get_math_display_operator (hb_font_t *font, GlyphID base_glyph_id, float min_height_factor = 1.0, hb_bool_t mirrored = false)

6) A way to get a glyph variant.

This is the same as 5) but with parameters to specify the stretch direction (vertical or horizontal) and the target size (which is generally a minimal size but Gecko also has had some parameters to interpret it as being as close as possible).

  HB_EXTERN GlyphID hb_ot_layout_get_math_glyph_variant (hb_font_t *font, GlyphID base_glyph_id, hb_bool_t horizontal, hb_position_t target_size, hb_bool_t mirrored = false)

7) A way to handle glyph assembly.

For 5) and 6) we can measure & paint the display operator glyph or glyph variant once we retrieved its glyph id. For glyph assembly we could either expose the list of glyphs and let the higher-level math engine do that job (what is currently done by Gecko/WebKit) or (probably better) let Harfbuzz measure/shape a glyph assembly. I'm not exactly sure what would fit in Harfbuzz's design but the caller would pass the same parameters as 6) and would obtain:

  a) whether a glyph assembly actually exists for this base glyph.
  b) the actual height and width of the assembly.
  c) the italic correction of the assembly (not used by Gecko/WebKit at the moment)
  d) ability to paint the glyph assembly.

There is a performance warning to be aware, here. In practice, glyph assembly only have at most 3 parts + 1 extender (which the limited case supported by Gecko/WebKit) and the taget size are smalls. However, if the target size is very large (which an "attacker" could easily obtain by using MathML/TeX spacing element/command) you have to repeat extender glyphs to cover the whole size. The algorithm proposed in the MATH spec seems to be linear with respect to the number of glyphs (or target size). Maybe we can find some clever glyph caching algorithm to improve that or otherwise just forbid excessive size.

8) A way to measure maximum metrics (more details below) that could be obtained in 6) and 7).

This is probably only for Web rendering engines where you need to approximate the preferred widths (for linebreaking purpose and so on) before doing the actual layout. The parameters would essentially be the same as for 6) and 7) without the target size.

For vertical operators, we will browse the list of glyph variants + the glyph assembly and return the maximum of all the advance width.

For horizontal operators, one can just call 6) and 7) with a (preferred) target size to obtain the preferred width or even just use the (preferred) target size as an approximation of the preferred width. So in theory, nothing is needed here but see 9).

9) Someone mentioned that in the Mongolian language it's possible to write math equations vertically (see https://bugzilla.mozilla.org/show_bug.cgi?id=1077525 for screeshots). I'm not aware of any math rendering engines that support that but it's definitely something to consider in the future. This would mean extending 7) and 8) (and the potential shaping of basic scripts mentioned in 4) to invert the role of width and height and have a parameter to decide writing-mode (horizontal-tb, sideways-rl, sideways-lr).

**Comment by khaledhosny** [comment]
On Tue, Apr 05, 2016 at 01:33:14AM -0700, Frédéric Wang wrote:
> >From my experience, the result obtained with the help of OT::MathConstants::DisplayOperatorMinHeight was poor (not sure whether it's a bug in the math fonts or a bad undestanding of the MATH spec but mail exchange with Murray Sargent did not clear my doubts). So it could be convenient to have an optional min_height_factor parameter to ensure that display operator height is at least min_height_factor times larger than the base glyph. Gecko uses min_height_factor = 2.0 for integrals (a sublist of the "largeop" operators) and √2 for other operators ; WebKit uses √2 and I think XeTeX has something like 3/2.
> 
>   HB_EXTERN GlyphID hb_ot_layout_get_math_display_operator (hb_font_t *font, GlyphID base_glyph_id, float min_height_factor = 1.0, hb_bool_t mirrored = false)

I think get_math_glyph_variant is enough, and the client should handle
possible complications (or not at all). Also I don’t think we need to
handle mirroring at the level of this API as it can be handled during
the initial shaping to get the glyph IDs.

**Comment by fred-wang** [comment]
> I think get_math_glyph_variant is enough, and the client should handle possible complications (or not at all). Also I don’t think we need to handle mirroring at the level of this API as it can be handled during the initial shaping to get the glyph IDs.

Right, that sounds good to me.

**Comment by fred-wang** [comment]
So I've implemented the API to access math constants and glyph information. I'm still trying to figure out how to expose the MathVariants table. Here is my revised proposal:

      HB_EXTERN hb_bool_t
      hb_ot_layout_has_math_data (hb_face_t *face);
      
      HB_EXTERN hb_position_t
      hb_ot_layout_get_math_constant (hb_font_t *font,
                                      hb_ot_math_constant_t constant);
      
      HB_EXTERN float
      hb_ot_layout_get_math_percent (hb_face_t *face,
                                     hb_ot_math_constant_t constant);
      
      HB_EXTERN hb_position_t
      hb_ot_layout_get_math_italic_correction (hb_font_t *font,
                                               hb_codepoint_t glyph);
      
      HB_EXTERN hb_position_t
      hb_ot_layout_get_math_top_accent_attachment (hb_font_t *font,
                                                   hb_codepoint_t glyph);
      
      HB_EXTERN hb_bool_t
      hb_ot_layout_is_math_extended_shape (hb_face_t *face,
                                           hb_codepoint_t glyph);
      
      HB_EXTERN hb_position_t
      hb_ot_layout_get_math_kerning (hb_font_t *font,
                                     hb_codepoint_t glyph,
                                     hb_ot_math_kern_t kern,
                                     hb_position_t correction_height);
      
For the shaping of MathVariants we could do

      HB_EXTERN void
      hb_shape_math_stretchy (hb_font_t      *font,
                              hb_buffer_t    *buffer,
                              hb_bool_t      horizontal
                              hb_codepoint_t target_size);

where buffer initially contains a stretchy character (e.g. a brace) and after shaping it contains one of

1) the glyph of the stretchy character
2) a glyph from OT::MathGlyphVariantRecord
3) the glyphs from the OT::GlyphPartRecord's (e.g. top, middle, bottom and extenders of the brace)

that is enough to cover the target size (and we fallback to the largest option if we can not reach that size). I don't know if buffer can initially contains an arbitrary glyph or just a unicode character. In the latter case, we would need a way to ask for mirroring the base glyph.

After shaping, we can actually deduce the extent occupied by the shaped text and so a way to access detailed MathVariants data may not be necessary. However, we still need the italic correction of the streched character. Perhaps hb_shape_math_stretchy can also return the width, height and italic correction of the streched character?

For web rendering engines, we also need a way to determine the maximum width of vertical stretchy operators before we know the target size (and similarly for vertical math layout we may need the maximum height of horizontal stretchy operator). So maybe something like:

      HB_EXTERN hb_position_t
      hb_layout_math_stretchy_max_extent_in_orthogonal_direction (hb_font_t *font,
                                                                  hb_codepoint_t glyph,
                                                                  hb_bool_t      horizontal);

**Comment by khaledhosny** [comment]
`hb_shape_math_stretchy` sounds fine, it should probably allow for the client to do an initial `hb_shape(_full)` call that would do the character to glyph mapping an apply any other requested features like mirroring. Returning the italic correction should be fine as well, but can’t we calculate the width and height from the buffer glyphs?

**Comment by fred-wang** [comment]
> it should probably allow for the client to do an initial hb_shape(_full) call that would do the character to glyph mapping an apply any other requested features like mirroring

That sounds good. However, I'm not familiar enough with Harfbuzz's design to know if it's correct to take arbitrary glyphs as input. Reading quickly the doc in the source, I understood that only a string of unicode characters is accepted. Maybe @behdad can comment on this.

> but can’t we calculate the width and height from the buffer glyphs?

Just like for other points, I'm hesitating between making things more convenient for the caller or minimizing the Harfbuff API. But I think you're right, we can ignore width/height. BTW, we can actually also get the italic correction except for glyph assembly. However, we can just have the following function currently implemented in my branch:

    HB_EXTERN hb_bool_t
    hb_ot_layout_get_math_glyph_assembly_italic_correction (hb_font_t *font,
                                                            hb_codepoint_t base_glyph,
                                                            hb_bool_t horizontal);

**Comment by behdad** [comment]
I hope to get to participate in this discussion in two to three weeks time.

**Comment by fred-wang** [comment]
> I hope to get to participate in this discussion in two to three weeks time.

@behdad Thanks. Hopefully, I'll have done more experiments on the MathVariants table and stretchy math shaping since them. If you have feedback to provide in the meantime, please read directly my MATH branch because I keep improving it (I updated https://github.com/behdad/harfbuzz/issues/235#issue-142158005 to point to this work in progress and also added references to XeTeX / libmathview)

BTW, I started adding some unit tests for the proposed API yesterday and I verified that MathConstants & MathGlyphInfo work as expected.

**Comment by fred-wang** [comment]
For those who are interested, I just opened https://github.com/behdad/harfbuzz/pull/241

**Comment by fred-wang** [comment]
For the record, the changes to expose math data is now available in master. The next thing we have to think about later is the shaping API. The original commit was d776da2f678e1895ac61ed9dfba10efc6d1c82ee but it would need to be rebased to use the new code. I also had a demo in https://github.com/fred-wang/harfbuzz-tutorial and a blog post at http://frederic-wang.fr/opentype-math-in-harfbuzz.html

My latest proposal was something like

    HB_EXTERN hb_bool_t
    hb_ot_shape_math_stretchy (hb_font_t*               font,
                               hb_buffer_t*             buffer,
                               hb_direction_t           direction,
                               hb_position_t            target_size,
                               hb_math_glyph_variant_t* variants,
                               unsigned int             variants_count,
                               hb_math_glyph_part_t*    parts,
                               unsigned int             parts_count);

That allows to stretch a single glyph using MathVariants data and allows to specify fallback stretch data.

**Comment by khaledhosny** [comment]
@fred-wang Just a thought, can `hb_ot_shape_math_stretchy()` be re-implemented using on the current public API or does it still need any internal ones?

**Comment by fred-wang** [comment]
@behdad @khaledhosny My plan was to try and reimplement it using the public API and I believe it would be possible, although I have not checked the details. This has been pending because of lack of time, because web engines still continue to read the MathVariants data directly for now and because I was not sure whether we wanted it in HarfBuzz at the end (or to reuse code in HarfBuzz with similar logic). I hope I'll be able to re-work on this, maybe it could be a small math operator helper library on top of HarfBuzz that can be shared by math engines. Or I can add a math example in HarfBuzz tutorial, so that other projects can just reuse the code.

**Comment by behdad** [comment]
We did the basics of this already.
