### ISSUE TITLE
Several Tibetan shorthand contractions misbehaviored with Microsoft Himalaya 5.21

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [behdad/harfbuzz#237]
The following [Tibetan shorthand contractions](http://www.babelstone.co.uk/Tibetan/Contractions.html) works with IE, Edge, BabelPad and LibreOffice for Windows, but not works with current versions of Firefox and Chrome, using Microsoft Himalaya 5.21 on Windows 10.

ཀེུན་ཀོུབ༹་ཀེུས་ཀླེུབས་ཀློུག་སྐྱེུ་ཁོུས༹་ཁྱོུག་ཁྲེུད་ཁྲེུད་ཁྲོུད་གོུག་གྱིུག་གྲིུན་གྲིུ་གྲོུན་གྲོུབ་དགེུན་དགེུགས་དངྲོུབ་དགྲོུབ་ཆྲོུལ་རྗེུན༹་ཉི༹ན་དྲིུག་གདེུན་བདོུས་འདེུད་སྡིུབ་ནོུགས་ནོུར་བློུན་བརྩོུས་རྫྲུལ་རྫེུས་ཞོུལ་

**Comment by khaledhosny** [comment]
Can you attach a screenshot of the correct (expected) rendering.

**Comment by KrasnayaPloshchad** [comment]
OK, this is what I have seen on LibreOffice for Windows, I think this is expected results.
![1](https://i.imgur.com/HacJnRI.png)
This is a screenshot copied on Firefox when I input in WYMeditor
![2](https://i.imgur.com/eDx2ESG.png)
I also take a screenshot from the original website, collect by [Andrew West](https://en.wikipedia.org/wiki/Andrew_West_%28linguist%29). 
![3](http://i.imgur.com/aHwQk8z.jpg)

**Comment by behdad** [comment]
Looks like we need to tweak a few combining classes...
