### ISSUE TITLE
http://harfbuzz.org doesn't have SSL

### ISSUE THREAD

**Issue by notwaldorf** [behdad/harfbuzz#240]
http://harfbuzz.org/ redirects to https://www.freedesktop.org/wiki/Software/HarfBuzz/, which has SSL, but the original domain doesn't :(

**Comment by behdad** [comment]
Humm.  I don't have any SSL certificates for any of my domains..  I've been thinking about moving to github.io eventually and possibly retire the harfbuzz.org domain.

**Comment by KrasnayaPloshchad** [comment]
@behdad You can try to get the certificate from [Let’s Eccrypt](https://letsencrypt.org/).
