### ISSUE TITLE
Difference between harfbuzz and uniscribe (mym2)

### ISSUE THREAD

**Issue by mhosken** [behdad/harfbuzz#242]
This is about the behaviour of adjusting the advance of a base glyph with attached mark glyphs. When the advance is adjusted, harfbuzz adjusts the positions of the attached marks, while uniscribe doesn't.

Consider a font with the following FEA rule in it:

pos u1014' 79 u1032 u1037;

which adds 79 to the advance of the first glyph in the sequence u1014 u1032 u1037:

[u1014=0+609|u1032=0@-89,-42+0|u1037=0@-55,0+0]

vs without the 1037:

[u1014=0+530|u1032=0@-10,-42+0]

But if we compare with a recent uniscribe we get:

[u1014=0+609|u1032=1@-10,-42+0|u1037=2@24,0+0]
[u1014=0+530|u1032=1@-10,-42+0]

and if we change the rule to compensate for the advance in the windows case we get:

pos u1014' 79 u1032' <-79 0 0 0> u1037;

harfbuzz gives:

[u1014=0+609|u1032=0@-168,-42+0|u1037=0@-55,0+0]
[u1014=0+530|u1032=0@-10,-42+0]

uniscribe gives:

[u1014=0+609|u1032=1@-89,-42+0|u1037=2@24,0+0]
[u1014=0+530|u1032=1@-10,-42+0]

**Comment by behdad** [comment]
Yes, this is a known difference between Uniscribe and HarfBuzz.  Microsoft recommends that mark attachments happen after all advance-width adjustments are done, in which case, the two engines match.  If that is not the case however, we decided to do it the way we do, because we believe that better matches the designer's intent.  Does that make sense?

**Comment by behdad** [comment]
(And this is not in any way limited to the Myanmar shaper.)

**Comment by mhosken** [comment]
> Yes, this is a known difference between Uniscribe and HarfBuzz. Microsoft recommends that mark attachments happen after all advance-width adjustments are done, in which case, the two engines match. If that is not the case however, we decided to do it the way we do, because we believe that better matches the designer's intent. Does that make sense?

The problem is that if the two engines differ in this respect, the poor font developer has no choice but to work around *both* approaches, if they want their font to work in all OpenType contexts (which they obviously do) and it becomes one less thing the font developer can use in their OpenType. For the font designer consistency wins out over right and wrong. This is what we ended up having to do in the Padauk font.

**Comment by behdad** [comment]
But if the recommended order is followed (all advance adjustments before all offset adjustments) then the two are the same.

I understand your point.  We might eventually change this.  But it doesn't feel right to me, and given how we merged mark and cursive attachments, we now have to go out of our way to make it act like Uniscribe. :(
