### ISSUE TITLE
Some large gaps appearing between Javanese letters

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [behdad/harfbuzz#243]
On current version of Chrome and Firefox, some of Javanese letters appearing a large gap between them when browsing texts with Javanese Text.

Case 1: Wikipedia page [Help:Multilingual support](https://en.wikipedia.org/wiki/Help:Multilingual_support#Javanese), appearing within ꦥꦺ.
![1](https://i.imgur.com/nwCV4wV.png)
Case 2: Wikipedia page [Help:Multilingual support (Indic)](https://en.wikipedia.org/wiki/Help:Multilingual_support_%28Indic%29#Check_for_existing_support), appearing within ꦧꦾꦺꦴꦂ.
![2](https://i.imgur.com/T4T0HOK.png)

**Comment by khaledhosny** [comment]
What is the font used for rendering this text?

**Comment by KrasnayaPloshchad** [comment]
I used “Javanese Text” on Windows 10.
[javatext.zip](https://github.com/behdad/harfbuzz/files/237868/javatext.zip)

**Comment by KrasnayaPloshchad** [comment]
Here is a screenshot taken from BabelPad, you can see what I have seen from there.
![1](https://i.imgur.com/Zy8Jo77.png)
