### ISSUE TITLE
Freetype bitmap fonts and advances

### ISSUE THREAD

**Issue by ollef** [behdad/harfbuzz#252]
I get a zero advance for certain bitmap glyphs in certain fonts when shaping with Harfbuzz. An example is the glyph corresponding to "😃" in Noto Color Emoji.

The FreeType function that Harfbuzz uses, `FT_Get_Advance`, does indeed seem to always return 0 for me with this font. However, if I use `FT_Load_Glyph` and look at the glyph metrics I am able to get the actual advance.

I'm not sure if this is the expected behaviour or a bug in one of the libraries. If it is the expected behaviour, I would be grateful for some guidance on how to handle this situation. My current workaround which is basically to post-process the data that Harfbuzz spits out seems like a hack.

Some possibly related discussion: http://freetype-devel.nongnu.narkive.com/f98ihs9B/ft-devel-ft-get-advance-docs

Many thanks!

**Comment by behdad** [comment]
It has to do with setting the correct bitmap size I believe.  I've had to deal with that problem myself; not sure what conclusion I reached.

**Comment by ollef** [comment]
Hey, and thanks for your reply! I'm using `FT_Select_Size` to set the size in Freetype. Is that what you were thinking of?

**Comment by behdad** [comment]
No it's a bug in HarfBuzz itself.  I'll get to fix it one day :(.

**Comment by jhs67** [comment]
I've been investigating this myself a little. As @ollef notes, `FT_Get_Advance` returns 0 for bitmap fonts. Digging into `FT_Get_Advance` it first gets the advance value from the font table and then scales it by the `font->size->metrics->x_scale` field. But `FT_Select_Size` doesn't set that value for bitmap fonts and the advance gets scaled to zero.

I tried just manually setting the `x_scale` field after calling `FT_Select_Size`:
```
FT_Select_Size(font, ...);
font->size->metrics->x_scale = 0x10000;
```
Which is tantalizingly close, but seems to only be about 1/3 of the needed advance for the fonts I've tried, including Noto Color Emoji. In fact setting the `x_scale` to `0x30000` leads to almost perfect results, but I have no explanation for why.

**Comment by jhs67** [comment]
I traced this a bit deeper. When you call `FT_Get_Advance` it loads the advance value from the 'hmtx' table which is in the units from the 'hhea' record of the font (`face->units_per_EM` for scalable fonts). This needs to get converted to the strike size of the glyph (in 26.6 format) and this conversion factor is:
```
64 * face->size->metrics.x_ppem / face->units_per_EM;
```
For Noto Color Emoji `units_per_EM` is 2048 and `face->size->metrics.x_ppem` is 94 and the result just happens to be about 3.

Unfortunately, the `units_per_EM` from the 'hhea'  record doesn't seem to be exposed by freetype for bitmap fonts. It is possible to patch freetype to calculate and store the correct scale value such that FT_Get_Advance returns valid values for bitmap fonts.

Alternatively, you could patch `hb_ft_get_glyph_h_advance` in hb-ft.cc to use `FT_Load_Glyph` and `face->glyph->metrics.horiAdvance` for bitmap fonts. This is probably the superior solution as you get the advance for the particular strike of the glyph. It is also probably slower.

**Comment by behdad** [comment]
@jhs67 Now that you mention it, I believe I dug into that function and noticed `x_scale` being zero indeed.  Was on my mental todo list to report to FreeType.  Thanks for digging.
@lemzwerg

**Comment by jhs67** [comment]
Here's the patch I came up with that seems to fix the problem. It was on my todo list to try figure out where to post it:

```
--- a/freetype/src/sfnt/ttsbit.c
+++ b/freetype/src/sfnt/ttsbit.c
@@ -323,6 +323,11 @@
                                           strike[18] + /* max_width      */
                                  (FT_Char)strike[23]   /* min_advance_SB */
                                                      ) * 64;
+
+        /* set the scale values so advances from the hmxt and vmxt table are scaled correctly */
+        metrics->x_scale = FT_MulDiv(metrics->x_ppem, 0x400000, face->header.Units_Per_EM);
+        metrics->y_scale = FT_MulDiv(metrics->y_ppem, 0x400000, face->header.Units_Per_EM);
+
         return FT_Err_Ok;
       }
```

**Comment by lemzwerg** [comment]
Well, FreeType has a bug tracker at https://savannah.nongnu.org/bugs/?group=freetype :-)

Anyway, I've applied your patch to FreeType's git repository, thanks!

**Comment by jhs67** [comment]
Great! Thanks @lemzwerg.
