### ISSUE TITLE
How to use harfbuzz (alternatively, what is harfbuzz)

### ISSUE THREAD

**Issue by kelvin13** [behdad/harfbuzz#254]
Does anyone know where I can find documentation for how to use this library, if any exists? Apparently other developers [have this problem too](http://stackoverflow.com/questions/21317181/harfbuzz-getting-started). Cute how the readme is [blank](https://github.com/behdad/harfbuzz/blob/master/README.md).

Where can I get the python bindings for this library? Does it preserve the mapping between the shaped glyphs and the input text (so I know where to display the cursor)? How do I use line breaking and hyphenation with harfbuzz?

This library’s name comes up a lot but nobody wants to explains what it even does…

**Comment by khaledhosny** [comment]
Check the manual http://behdad.github.io/harfbuzz/. It helps if you already know how text layout is usually done in modern world, too many basic questions to be answered.

**Comment by khaledhosny** [comment]
For Python bindings you need to build with `--enable-introspection=yes`.

**Comment by kelvin13** [comment]
> Check the manual http://behdad.github.io/harfbuzz/.

@khaledhosny it is blank after http://behdad.github.io/harfbuzz/setting-buffer-properties.html

> It helps if you already know how text layout is usually done in modern world, too many basic questions to be answered.

aight someone wanna be the first to spill the beans then?

**Comment by kelvin13** [comment]
can you please answer at least these basic questions then

1. What do I put into HB and what comes out?
2. How do I get back to my original input?
3. How do I tell HB when to stop? (line advance limit, line break)
3. What's the python API functions to do that?

because I cannot even find out this basic info
> The Python API will change.  Let us know on the mailing list if you are
using it, and send lots of feedback.

**Comment by kelvin13** [comment]
The reason I am asking this is because I have a python typesetting application called [Knockout](https://github.com/kelvin13/Knockout) that currently uses a sorts-wise layout engine I wrote myself but doesn’t support Opentype features so I’m trying to move it onto harfbuzz.

**Comment by kelvin13** [comment]
> For Python bindings you need to build with --enable-introspection=yes.

[build.md](https://github.com/behdad/harfbuzz/blob/master/BUILD.md) isn’t very helpful so i’m just guessing around at this point but is it bad if the autogen/configure thing says 

```
Other features:
	Documentation:		yes
	GObject bindings:	false
	Introspection:		false
```

at the end, it doesn't matter if I put the “`--enable-introspection=yes`” after it it still says false

sorry if i'm being annoying but there’s like no navigational signage here

**Comment by khaledhosny** [comment]
> it is blank starting with http://behdad.github.io/harfbuzz/setting-buffer-properties.html

Read the non-blank parts and then ask questions that are not answered by then.

**Comment by khaledhosny** [comment]
You probably need `--with-gobject=yes` as well. There is also a Python example here https://github.com/behdad/harfbuzz/blob/master/src/sample.py.

**Comment by kelvin13** [comment]
I read the non blank parts and the python example but i'm still confused. Why so many steps to create a font face? Why does the UPEM go into the `font_set_scale`? How do I turn on/off opentype features or set the language/script? And does Harfbuzz retain any mapping back to the original input text in the output glyphs? And of course, how is this used with a linebreaking algorithm?

**Comment by kelvin13** [comment]
> You probably need --with-gobject=yes as well.

```
Other features:
	Documentation:		yes
	GObject bindings:	true
	Introspection:		false
```
GObject changes to true but Introspection is still false

**Comment by twardoch** [comment]
The GObject introspection stuff is indeed wird. I always have a hard time getting it to work. 

Here's some GObject-based API docs for HarfBuzz: 
https://lazka.github.io/pgi-docs/HarfBuzz-0.0/index.html

Generally, hb-view in https://github.com/behdad/harfbuzz/tree/master/util is a good minimal example on how to use HarfBuzz.

**Comment by twardoch** [comment]
Also see:
https://github.com/lxnt/zhban
https://gist.github.com/olymk2/d5801d9e1df0459625a3

**Comment by twardoch** [comment]
And of course https://www.microsoft.com/typography/developers/opentype/ as a general intro to Unicode+OpenType text rendering.

**Comment by twardoch** [comment]
This approach: 
https://www.cairographics.org/cookbook/freetypepython/
could be extended to replicate hb-view.

**Comment by kelvin13** [comment]
> Here's some GObject-based API docs for HarfBuzz:
> https://lazka.github.io/pgi-docs/HarfBuzz-0.0/index.html

okay thanks but that's really just a list of function names with no explanations

> Generally, hb-view in https://github.com/behdad/harfbuzz/tree/master/util is a good minimal example on how to use HarfBuzz. 

if you mean shape-consumer.hh I still don't get what is happening there

> This approach:
https://www.cairographics.org/cookbook/freetypepython/
could be extended to replicate hb-view. 

Yes, I’ve seen that recipe I already use it in Knockout to create cairo font faces. Is that all hb-view does? Generate cairo images?

**Comment by ebraminio** [comment]
I think [this](https://github.com/behdad/harfbuzz-tutorial/blob/master/hello-harfbuzz.c) would help, or [mine](https://github.com/ebraminio/glcourse/blob/master/tut1.cc) which is more compact and doesn't involve cairo.

**Comment by adrientetar** [comment]
> Check the manual http://behdad.github.io/harfbuzz/

This is hard to come across tbh, neither the README nor harfbuzz.org link to it. Googling harfbuzz doesn't either.

**Comment by phunsukwangdu** [comment]
i am also suffering the same fate as @kelvin13 .I am designing a text layout engine in python.But resources are so few that only docs you have is the code itself.Maybe someone showers some light to approach the problem.I have managed to use harfbuzz in python.

**Comment by ebraminio** [comment]
I think this helps http://behdad.org/text/ tl;dr consider using pango or https://github.com/HOST-Oman/libraqm instead directly calling into harfbuzz, you should wire up lots of things, such as segmentation, bidi, font selection and fallback to make harfbuzz work properly, things provided by upper level library like the mentioned ones, but if you still like to use harfbuzz, this time you can check kelvin's work, https://github.com/kelvin13/Knockout

**Comment by phunsukwangdu** [comment]
@ebraminio i have stalked every link you have provided before only.I did pick on the hints yo provide.I want to extend the sample.py code to use it will cairo(python) .how should i do it? Thx for help and anticipation.

**Comment by ebraminio** [comment]
No idea, but I hope this helps https://gist.github.com/ebraminio/696dbf5cb67b2f87b4101073d231dc46

**Comment by phunsukwangdu** [comment]
thx ,i will try to put up a tutorial,if i find success.
