### ISSUE TITLE
Recognize fonts with deprecated language system tag DHV?

### ISSUE THREAD

**Issue by brawer** [behdad/harfbuzz#258]
The [OpenType spec](https://www.microsoft.com/typography/otspec/languagetags.htm) gives _two_ OpenType language system tags for Divehi/Dhivehi/Maldivian: the current code `DIV`, and a deprecated code `DHV`. As of OpenType 1.7, `DHV` is the only deprecated language system code.

In its languages table, HarfBuzz is correctly [mapping](https://github.com/behdad/harfbuzz/blob/264b7a728a41becfbf23ce258fc2a3af19d0cbbe/src/hb-ot-tag.cc#L320) `dv` to `DIV`. Just wondering, should there be some fallback logic that recognizes old fonts which still use `DHV` for identifying the language? I don’t know if any such fonts exist.

**Comment by behdad** [comment]
Right now in HB the BCP 47 to OT language tag mapping is many-to-one.  Until we find real cases that need many-to-many, I prefer not changing that for a theoretical case that probably has no fonts using it whatsoever.
