### ISSUE TITLE
Can’t build python bindings

### ISSUE THREAD

**Issue by kelvin13** [behdad/harfbuzz#261]
I followed all the instructions in [`/README.python`](https://github.com/behdad/harfbuzz/blob/master/README.python) but trying to import Harfbuzz still fails

````
>>> from gi.repository import HarfBuzz
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 890, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 127, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name HarfBuzz, introspection typelib not found
````

as far as I can tell it was built with introspection because the configure thing said this:

```
Other features:
	Documentation:		yes
	GObject bindings:	true
	Introspection:		true
```

**Comment by anthrotype** [comment]
the  `README.python` says you also need to set `GI_TYPELIB_PATH` env variable, pointing to the `$prefix/lib/girepository-1.0` directory where the `HarfBuzz-0.0.typelib` is located. Did you do that too?

**Comment by kelvin13** [comment]
No i didn’t I’ve never used a package that needed you to do that but thanks
