### ISSUE TITLE
question about font face creation

### ISSUE THREAD

**Issue by kelvin13** [behdad/harfbuzz#262]
the python example i could find says to make a harfbuzz font you have to do
````
fontdata = open (sys.argv[1], 'rb').read ()
blob = hb.glib_blob_create (GLib.Bytes.new (fontdata))
face = hb.face_create (blob, 0)
font = hb.font_create (face)
````
Why so many steps to make a harfbuzz font? Is [this thing](https://bugzilla.gnome.org/show_bug.cgi?id=729541) still to blame? Can I use a font file directly or use a freetype face instead?

**Comment by kelvin13** [comment]
Also the python API seems very confusing & unpythonic in general; why is the buffer not an object with member functions (“add text”, “guess properties”, etc)? Why does `hb.shape` not simply return glyph infos and positions?

**Comment by khaledhosny** [comment]
The linked bug when fixed will get rid of the first line, but you are still left with the remaining three. I don’t see what is the problem of the few extra lines, you usually create the face once for any given font file then create font instances for different sizes.

The Python bindings are auto generated from the C API with gobject introspection, so the API is bound to be unpythonic in someways. May be there are ways to improve this, if any one can look into gobject documentation and find ways to improve the bindings, I’m sure such patches will be welcomed.

**Comment by kelvin13** [comment]
Ok I understand why face and font are different things now. But is it possible to create a HB face from a freetype face or do I have no choice but import GLib

**Comment by khaledhosny** [comment]
It seems that most of hb_ft_* methods are not exported in the binding, I don’t know why but probably because it does not know how to handle FT_Face objects.

**Comment by khaledhosny** [comment]
This what I see in the build log, if someone wants to investigate it:
```
hb-ft.cc:481: Warning: HarfBuzz: hb_ft_face_create: argument ft_face: Unresolved type: 'FT_Face'
hb-ft.cc:538: Warning: HarfBuzz: hb_ft_face_create_cached: argument ft_face: Unresolved type: 'FT_Face'
hb-ft.cc:516: Warning: HarfBuzz: hb_ft_face_create_referenced: argument ft_face: Unresolved type: 'FT_Face'
hb-ft.cc:563: Warning: HarfBuzz: hb_ft_font_create: argument ft_face: Unresolved type: 'FT_Face'
hb-ft.cc:596: Warning: HarfBuzz: hb_ft_font_create_referenced: argument ft_face: Unresolved type: 'FT_Face'
hb-ft.h:111: Warning: HarfBuzz: hb_ft_font_get_face: return value: Unresolved type: 'FT_Face'
```

**Comment by behdad** [comment]
> why is the buffer not an object with member functions “add text”, “guess properties”, etc?

That's because this wasn't fixed back then:
https://bugzilla.gnome.org/show_bug.cgi?id=706898

Someone needs to work it out now that it is.

**Comment by behdad** [comment]
> That's because this wasn't fixed back then:
> https://bugzilla.gnome.org/show_bug.cgi?id=706898

See https://github.com/behdad/harfbuzz/pull/281
