### ISSUE TITLE
shaping into fixed line length

### ISSUE THREAD

**Issue by kelvin13** [behdad/harfbuzz#263]
So to do linebreaking, I’d need to be able to fit the maximum physical length of text into a given amount of space (with hyphenation) but with complex shaping you can’t just go backwards and delete glyphs until you hit a hyphenation point or a whitespace glyph (which is what my [app](https://github.com/kelvin13/Knockout) that i’m moving onto harfbuzz does currently). So I was thinking to split the text before shaping into “independent fragments” that can be shaped without affecting their neighbors, and then cramming as many of those fragments as possible into the given space, and then just iterating through hyphenation points on the last fragment & shaping each candidate until one fits in the remaining space. But that requires knowing how to fragment the string to begin with.

Apparently [this](https://github.com/behdad/harfbuzz/issues/224) seems related, did it ever work and is there a api function for it?

Also is it bad if `hb.shape` gets called on one letter at a time because i'm guessing in most cases the fragments will be one letter long so `'efficiency'` becomes `'e', 'ffi', 'c', 'i', 'e', 'n', 'c', 'y'` so `hb.shape` would be called 8 times instead of once

**Comment by kelvin13** [comment]
?

**Comment by behdad** [comment]
We don't currently support justification.
