### ISSUE TITLE
Build issues on AIX for harfbuzz-1.2.7 with IBM C++ compiler

### ISSUE THREAD

**Issue by twwlogin** [behdad/harfbuzz#265]
I am attempting to build harfbuzz-1.2.7 on AIX 7.1 with the IBM C++ compiler, xlC. I am getting the following error. Is this a bug in the compiler or something in the code?

`gmake[4]: Entering directory ``/opt/build/harfbuzz-1.2.7/src'`
`/opt/fsw/bash42/bin/bash ../libtool  --tag=CXX   --mode=compile xlC -DHAVE_CONFIG_H -I. -I..  -D_THREAD_SAFE  -I/opt/TWWfsw/gettext018/include -I/opt/TWWfsw/libglib238/include -I/opt/TWWfsw/libglib238/lib/include -I/opt/TWWfsw/libpcre833/include   -I/opt/TWWfsw/libttf24/include/freetype2 -I/opt/TWWfsw/libttf24/include       -I./hb-ucdn    -O2 -qro -qroconst -qnotempinc -qnoeh -qnotemplateregistry -qmaxmem=-1 -qarch=ppc  -c -o libharfbuzz_la-hb-blob.lo `test -f 'hb-blob.cc' || echo './'`hb-blob.cc`
`mkdir .libs`
` xlC -DHAVE_CONFIG_H -I. -I.. -D_THREAD_SAFE -I/opt/TWWfsw/gettext018/include -I/opt/TWWfsw/libglib238/include -I/opt/TWWfsw/libglib238/lib/include -I/opt/TWWfsw/libpcre833/include -I/opt/TWWfsw/libttf24/include/freetype2 -I/opt/TWWfsw/libttf24/include -I./hb-ucdn -O2 -qro -qroconst -qnotempinc -qnoeh -qnotemplateregistry -qmaxmem=-1 -qarch=ppc -c hb-blob.cc  -DPIC -o .libs/libharfbuzz_la-hb-blob.o`
`"hb-object-private.hh", line 134.3: 1540-0274 (S) The name lookup for "hb_object_init" did not find a declaration.`
`"hb-object-private.hh", line 134.3: 1540-1292 (I) Static declarations are not considered for a function call if the function is not qualified.`
`"hb-object-private.hh", line 127.21: 1540-0700 (I) The previous message was produced while processing "hb_object_create<hb_blob_t>()".`
`"hb-blob.cc", line 107.16: 1540-0700 (I) The previous message was produced while processing "hb_blob_create(const char *, unsigned int, hb_memory_mode_t, void *, hb_destroy_func_t)".
"hb-object-private.hh", line 135.3: 1540-0274 (S) The name lookup for "hb_object_trace" did not find a declaration.`
`"hb-object-private.hh", line 135.3: 1540-1292 (I) Static declarations are not considered for a function call if the function is not qualified.`
`"hb-object-private.hh", line 157.3: 1540-0274 (S) The name lookup for "hb_object_trace" did not find a declaration.`
`"hb-object-private.hh", line 157.3: 1540-1292 (I) Static declarations are not considered for a function call if the function is not qualified.`
`"hb-object-private.hh", line 155.21: 1540-0700 (I) The previous message was produced while processing "hb_object_reference<hb_blob_t>(hb_blob_t *)".`
`"hb-blob.cc", line 217.10: 1540-0700 (I) The previous message was produced while processing "hb_blob_reference(hb_blob_t *)".`
`"hb-object-private.hh", line 158.25: 1540-0274 (S) The name lookup for "hb_object_is_inert" did not find a declaration.`
`"hb-object-private.hh", line 158.25: 1540-1292 (I) Static declarations are not considered for a function call if the function is not qualified.`
`"hb-object-private.hh", line 160.11: 1540-0274 (S) The name lookup for "hb_object_is_valid" did not find a declaration.`
`"hb-object-private.hh", line 160.11: 1540-1292 (I) Static declarations are not considered for a function call if the function is not qualified.`
`"hb-object-private.hh", line 167.3: 1540-0274 (S) The name lookup for "hb_object_trace" did not find a declaration.`
`"hb-object-private.hh", line 167.3: 1540-1292 (I) Static declarations are not considered for a function call if the function is not qualified.`
`"hb-object-private.hh", line 165.20: 1540-0700 (I) The previous message was produced while processing "hb_object_destroy<hb_blob_t>(hb_blob_t *)".`
`"hb-blob.cc", line 235.8: 1540-0700 (I) The previous message was produced while processing "hb_blob_destroy(hb_blob_t *)".`
`"hb-object-private.hh", line 168.25: 1540-0274 (S) The name lookup for "hb_object_is_inert" did not find a declaration.`
`"hb-object-private.hh", line 168.25: 1540-1292 (I) Static declarations are not considered for a function call if the function is not qualified.`
`"hb-object-private.hh", line 170.11: 1540-0274 (S) The name lookup for "hb_object_is_valid" did not find a declaration.`
`"hb-object-private.hh", line 170.11: 1540-1292 (I) Static declarations are not considered for a function call if the function is not qualified.`
`"hb-object-private.hh", line 185.25: 1540-0274 (S) The name lookup for "hb_object_is_inert" did not find a declaration.`
`"hb-object-private.hh", line 185.25: 1540-1292 (I) Static declarations are not considered for a function call if the function is not qualified.`
`"hb-object-private.hh", line 179.20: 1540-0700 (I) The previous message was produced while processing "hb_object_set_user_data<hb_blob_t>(hb_blob_t *, hb_user_data_key_t *, void *, hb_destroy_func_t, hb_bool_t)".`
`"hb-blob.cc", line 261.10: 1540-0700 (I) The previous message was produced while processing "hb_blob_set_user_data(hb_blob_t *, hb_user_data_key_t *, void *, hb_destroy_func_t, hb_bool_t)".`
`"hb-object-private.hh", line 187.11: 1540-0274 (S) The name lookup for "hb_object_is_valid" did not find a declaration.`
`"hb-object-private.hh", line 187.11: 1540-1292 (I) Static declarations are not considered for a function call if the function is not qualified.`
`"hb-object-private.hh", line 195.25: 1540-0274 (S) The name lookup for "hb_object_is_inert" did not find a declaration.`
`"hb-object-private.hh", line 195.25: 1540-1292 (I) Static declarations are not considered for a function call if the function is not qualified.`
`"hb-object-private.hh", line 192.21: 1540-0700 (I) The previous message was produced while processing "hb_object_get_user_data<hb_blob_t>(hb_blob_t *, hb_user_data_key_t *)".`
`"hb-blob.cc", line 279.10: 1540-0700 (I) The previous message was produced while processing "hb_blob_get_user_data(hb_blob_t *, hb_user_data_key_t *)".`
`"hb-object-private.hh", line 197.11: 1540-0274 (S) The name lookup for "hb_object_is_valid" did not find a declaration.`
`"hb-object-private.hh", line 197.11: 1540-1292 (I) Static declarations are not considered for a function call if the function is not qualified.`
`"hb-atomic-private.hh", line 135.37: 1540-2879 (S) The built-in function "__compare_and_swaplp" requires option "-q64".`
`gmake[4]: *** [libharfbuzz_la-hb-blob.lo] Error 1`
`gmake[4]: Leaving directory `/opt/build/harfbuzz-1.2.7/src'`

**Comment by behdad** [comment]
Hi.  I have no idea.  You need to ask in a circle that knows this compiler.
