### ISSUE TITLE
Cannot use Harfbuzz with Gtk

### ISSUE THREAD

**Issue by kelvin13** [behdad/harfbuzz#272]
Why is it that python Harfbuzz import fails whenever Gtk is used in the same program?

````
Traceback (most recent call last):
  File "layout/otline.py", line 7, in <module>
    gi.require_version('HarfBuzz', '0.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace HarfBuzz not available
````

Harfbuzz works if it is imported first, and Gtk is imported second, but this is a problem that need Gtk first and Harfbuzz second

**Comment by khaledhosny** [comment]
No problem here, please post a complete example.

**Comment by kelvin13** [comment]
Here is a short program that fails:

`test.py`

````
import gi
gi.require_version('Gtk', '3.0')
gi.require_version('HarfBuzz', '0.0')

from gi.repository import Gtk

from os import environ
environ['LD_LIBRARY_PATH'] = '/home/kelvin/HB/lib/girepository-1.0'
environ['GI_TYPELIB_PATH'] = '/home/kelvin/HB/lib/girepository-1.0'


from gi.repository import HarfBuzz as hb
````

**Comment by kelvin13** [comment]
Wait nvm it looks like I needed to set the HB environment variables first. But if I installed harfbuzz in a custom directory for `environ['GI_TYPELIB_PATH']` will that mess up Gtk?

**Comment by kelvin13** [comment]
The problem still shows up though when you have two `import gi` statements, like what happens when you have harfbuzz and Gtk in different .py files:

````
import gi
gi.require_version('Gtk', '3.0')

from gi.repository import Gtk

````
````
from os import environ
environ['LD_LIBRARY_PATH'] = '/home/kelvin/HB/lib/girepository-1.0'
environ['GI_TYPELIB_PATH'] = '/home/kelvin/HB/lib/girepository-1.0'

import gi
gi.require_version('HarfBuzz', '0.0')

from gi.repository import HarfBuzz as hb
````

Removing the Gtk part will let the harfbuzz work fine

**Comment by khaledhosny** [comment]
It seems like a problem in your set up or GIR limitation, does not look like anything HarfBuzz-specific.

**Comment by kelvin13** [comment]
Is it possible to import harfbuzz alone without gi.repository?

**Comment by khaledhosny** [comment]
No.
