### ISSUE TITLE
harfbuzz only works once

### ISSUE THREAD

**Issue by kelvin13** [behdad/harfbuzz#274]
well ain’t this the weirdest thing

when I do `make install` on harfbuzz, I can use the library, but only once. Then when I use it again, every codepoint it puts out is 0 so I just get a bunch of rectangles. Every time I import it I get
````
** (kt.py:5410): WARNING **: Failed to load shared library 'libharfbuzz-gobject.so.0' referenced by the typelib: libharfbuzz-gobject.so.0: cannot open shared object file: No such file or directory
````

even the first time when harfbuzz works normally. Every time I make install it resets harfbuzz and it works one more time. I tried doing the entire sequence starting with ./autogen.sh too but it doesn’t help things

**Comment by kelvin13** [comment]
anyone know why this is happening?? Even on a basic test file it spit out zeros about every one in eight times

````
from os import environ

environ['GI_TYPELIB_PATH'] = 'HB/lib/girepository-1.0'
environ['LD_LIBRARY_PATH'] = 'libraries/HB/lib/girepository-1.0'
import gi
gi.require_version('HarfBuzz', '0.0')

from gi.repository import HarfBuzz as hb

from gi.repository.GLib import Bytes

path = 'amiri-regular.ttf'

text = 'AVefficiency Today'

with open(path, 'rb') as fi:
    fontdata = fi.read()

face = hb.face_create(hb.glib_blob_create(Bytes.new(fontdata)), 0)
font = hb.font_create(face)

upem = hb.face_get_upem(face)
hb.font_set_scale(font, upem, upem)
hb.ot_font_set_funcs(font)

buf = hb.buffer_create()
hb.buffer_add_utf8(buf, text.encode('utf-8'), 0, -1)
hb.buffer_guess_segment_properties(buf)

hb.shape(font, buf, [])

infos = hb.buffer_get_glyph_infos(buf)
positions = hb.buffer_get_glyph_positions(buf)

x = 0
y = 0
for I, P in zip(infos, positions):
    print(I.codepoint, x + P.x_offset, y + P.y_offset, I.cluster)
#    print(P.x_offset, P.y_offset)
    x += P.x_advance
    y += P.y_advance
````

output
````
** (process:3008): WARNING **: Failed to load shared library 'libharfbuzz-gobject.so.0' referenced by the typelib: libharfbuzz-gobject.so.0: cannot open shared object file: No such file or directory
0 0 0 0
0 500 0 1
0 1000 0 2
0 1500 0 3
0 2000 0 4
0 2500 0 5
0 3000 0 6
0 3500 0 7
0 4000 0 8
0 4500 0 9
0 5000 0 10
0 5500 0 11
0 6000 0 12
0 6500 0 13
0 7000 0 14
0 7500 0 15
0 8000 0 16
0 8500 0 17
````

**Comment by khaledhosny** [comment]
This strikes me as specific problem with your setup that are not related to HarfBuzz per se, why not ask on some general GObject Introspection help place?

**Comment by behdad** [comment]
What Khaled said.  While we don't mind answering user questions on our issue tracker, this is plain out of the scope of our expertise.

**Comment by kelvin13** [comment]
no what doesn’t make sense is harfbuzz works fine on one computer, but then this happens when i do the exact same thing, rebuilding on the second computer on a fresh install of ubuntu 16.04

**Comment by kelvin13** [comment]
@khaledhosny @behdad  Problem located. This issue only happens if harfbuzz is installed to a custom directory in --prefix=… when running `./configure`. If Harfbuzz is installed to its default `usr/local/lib/girepository-1.0` location, then it works fine. Apparently contrary to what [this](https://github.com/behdad/harfbuzz/blob/master/README.python) says, just setting the environment variables to point to the directory that `HarfBuzz-0.0.typelib` lives is not enough… 

i think this should be reopened bc it sounds like something is going wrong with the ./configure thing.
