### ISSUE TITLE
Centos 6 Install - Header file not included?

### ISSUE THREAD

**Issue by mcechini** [behdad/harfbuzz#275]
I followed the build/install steps without error to build Harfbuzz on a Centos 6 box.  

I am trying to compile an instance of Mapserver and it is failing because it is looking for the hb-ft.h file.  This file is in the Harfbuzz src/ directory, but not in the /usr/local/include/harfbuzz directory into which other header files are installed.

Is this an oversight, or do I just need to hack my compile flags to pick up this flag? 

Also, it would be really nice to have RPMs for Centos 6 so I can just `yum install`

**Comment by khaledhosny** [comment]
Did you build with ` --with-freetype=yes`?

**Comment by mcechini** [comment]
Nope.  Just the `./configure && make && make install` command.  Looking now for where to add the `--with-freetype=yes` directive...

**Comment by khaledhosny** [comment]
`./configure --with-freetype=yes`

**Comment by mcechini** [comment]
Build/installed freetype 2.6.3, libraries installing to /usr/local/lib.  When I run `./configure --with-freetype=yes`, I see `configure: error: FreeType support requested but libfreetype2 not found`.   Tried installing freetype to /usr, no dice there either.

**Comment by khaledhosny** [comment]
You need to install the development package for FreeType from your
distribution, like any dependency when building from source. Really,
this is just basic building from source requirements, nothing specific
to HarfBuzz here.

**Comment by behdad** [comment]
There's even instructions in the BUILD.md file.
