### ISSUE TITLE
show_version() in util/options.cc declared gboolean but does not return a value

### ISSUE THREAD

**Issue by twwlogin** [behdad/harfbuzz#290]
Why is show_version() in util/options.cc declared gboolean but does not return a value?

**Comment by twwlogin** [comment]
Ditto for list_shapers().

**Comment by behdad** [comment]
Because they are used as callbacks with GOptionEntry, which means they must have this particular signature.  I suppose I can put a return at the end, but then some compilers warn that the return line of code will be unreachable because of the exit call earlier.
