### ISSUE TITLE
CoreText backend memory leak

### ISSUE THREAD

**Issue by ebraminio** [behdad/harfbuzz#291]
CoreText backend as its use on Chrome on Mac is an important part of harfbuzz [at least till we get a native AAT implementation] so we should take seriously its possible bugs.

Continuing from [this not so good way to go patch](https://github.com/ebraminio/harfbuzz/commit/5462882e807107bcd4d7bf7844b46c7ef92c603), it seems hb-coretext suffers from memory leaks. As a proof, if you put `int t = CFGetRetainCount(data->ct_font); int g = CFGetRetainCount(data->cg_font);` in start of `_hb_coretext_shaper_face_data_destroy` you get two "3" which doesn't seem right.

My first finding is the fact `CTFontRef ct_font = CTFontCreateWithGraphicsFont (cg_font, font_size, NULL, NULL);` is adding a ref to cg_font but its release doesn't seem to cause cg_font ref count decrease and so it prevents cg_font eventual release (which is a serious issue). It seems this is a known [issue](http://stackoverflow.com/questions/37833225/how-can-i-stop-memory-being-leaked-by-ctfontcreatewithgraphicsfont) with coretext.

The main issue, however, seems lies into `_hb_coretext_shape` as if you put the same snippet, `int t = ...` on its third line and last line, you will get these pairs: (1, 2) and (3, 3). This doesn't seem right, I think logically `_hb_coretext_shape` should clean whatever reference it added to cg_font and ct_font.

**Comment by ebraminio** [comment]
Another interesting finding, `CTTypesetterCreateWithAttributedStringAndOptions` call increases ct_font cg_font ref but even releasing the result doesn't revert the situation before the call.

![image](https://cloud.githubusercontent.com/assets/833473/16782179/a5cb7802-4893-11e6-8212-d5e3e442b3a5.png)

**Comment by behdad** [comment]
I'm rather uncomfortable destructing the blob before the CGFont using it is known to be destructed.  So, let's dig deeper to see why the CGFont is not destructed.

**Comment by ebraminio** [comment]
If I put some more CFRelease it will destruct hb blob (which is biggest leak despite other ones are also worth to fix) so I am also in favor of fixing it fundamentally but now am somehow confused and failed to find the reason why these APIs are acting like these. I wonder if you would be able to invite some of OS X API gurus here perhaps from Chromium project to have a look?

**Comment by ebraminio** [comment]
Hmm, [this](http://stackoverflow.com/a/870260) explains a bit I guess.

**Comment by ebraminio** [comment]
I've put together simplest possible ingredients to repro the leaks:

```
#include <stdio.h>
#include <stdlib.h>
#include <ApplicationServices/ApplicationServices.h>

int main(int argc, char **argv) {
    FILE *f = fopen("/Library/Fonts/Tahoma.ttf", "rb");
    fseek(f, 0, SEEK_END);
    long fsize = ftell(f);
    fseek(f, 0, SEEK_SET);
    
    char* font = (char*)malloc(fsize);
    fread(font, fsize, 1, f);
    fclose(f);
    
    for (int i = 0; i < 100; ++i) {
        CGDataProviderRef provider = CGDataProviderCreateWithData(NULL, font, fsize, NULL);
        CGFontRef cg_font = CGFontCreateWithDataProvider(provider);
        CTFontRef ct_font = CTFontCreateWithGraphicsFont(cg_font, 36., NULL, NULL);
        
        printf(" Before:\nct_font: %d\ncg_font: %d\n", (int)CFGetRetainCount(ct_font), (int)CFGetRetainCount(cg_font));
        
        int chars_len = 1;
        CFStringRef string_ref = CFStringCreateWithCString(NULL, "A", kCFStringEncodingUTF8);
        CFMutableAttributedStringRef attr_string = CFAttributedStringCreateMutable(kCFAllocatorDefault, chars_len);
        CFAttributedStringReplaceString(attr_string, CFRangeMake(0, 0), string_ref);
        CFAttributedStringSetAttribute(attr_string, CFRangeMake(0, chars_len), kCTFontAttributeName, ct_font);
        CTTypesetterRef typesetter = CTTypesetterCreateWithAttributedString(attr_string);
        
        printf(" After:\nct_font: %d\ncg_font: %d\n\n\n", (int)CFGetRetainCount(ct_font), (int)CFGetRetainCount(cg_font));
        
        CFRelease(typesetter);
        CFRelease(attr_string);
        CFRelease(string_ref);
        CFRelease(ct_font);
        CFRelease(cg_font);
    
        CGDataProviderRelease(provider);
    }
    free(font);
    
    return 0;
}
```
Result:
```
 Before:
ct_font: 1
cg_font: 2
 After:
ct_font: 5
cg_font: 2
```

![screen shot 2016-11-22 at 10 01 58 am](https://cloud.githubusercontent.com/assets/833473/20513276/25b35aa8-b09a-11e6-9ad5-d0e78316e648.png)

@drott: Is it possible to create CTFont from memory without involving CGFont?

**Comment by brawer** [comment]
> Is it possible to create CTFont from memory without involving CGFont?
 
Yes. For example, [here](https://github.com/unicode-org/text-rendering-tests/blob/master/src/fonttest/coretext_engine.mm#L62)’s some code that creates a CTFontDescriptor without CGFont; and [here](https://github.com/unicode-org/text-rendering-tests/blob/master/src/fonttest/coretext_font.mm#L161)’s how to create a CTFont from that descriptor. However, before macOS 10.12, font variations will be ignored when not going through CGFont.

**Comment by ebraminio** [comment]
Thanks. I don't know how to convert char* to a path suitable for passing to CFURLCreateFromFileSystemRepresentation, is converting to temporary file is the trick for that? And do you have any idea about what went wrong with the simplified code? [this](https://gist.github.com/ebraminio/58820475ee5554a2731ce7985896a216/) is the original harfbuzz involving code to represent that.

**Comment by drott** [comment]
What's the retain count after the release block, especially after releasing the typesetter and the attributed string?
```
        CFRelease(typesetter);
        CFRelease(attr_string);
        CFRelease(string_ref);
        CFRelease(ct_font);
        CFRelease(cg_font);
```

**Comment by ebraminio** [comment]
```
        printf(" After:\nct_font: %d\ncg_font: %d\n", (int)CFGetRetainCount(ct_font), (int)CFGetRetainCount(cg_font));
        
        CFRelease(typesetter);
        printf(" after typesetter release:\nct_font: %d\ncg_font: %d\n", (int)CFGetRetainCount(ct_font), (int)CFGetRetainCount(cg_font));
        CFRelease(attr_string);
        printf(" after attr_string release:\nct_font: %d\ncg_font: %d\n", (int)CFGetRetainCount(ct_font), (int)CFGetRetainCount(cg_font));
        CFRelease(string_ref);
        printf(" after string_ref release:\nct_font: %d\ncg_font: %d\n", (int)CFGetRetainCount(ct_font), (int)CFGetRetainCount(cg_font));
        CFRelease(ct_font);
        printf(" after ct_font release:\nct_font: %d\ncg_font: %d\n", (int)CFGetRetainCount(ct_font), (int)CFGetRetainCount(cg_font));
        CFRelease(cg_font);
        printf(" after cg_font release:\nct_font: %d\ncg_font: %d\n", (int)CFGetRetainCount(ct_font), (int)CFGetRetainCount(cg_font));
        
        CGDataProviderRelease(provider);
        printf(" after provider release:\nct_font: %d\ncg_font: %d\n\n\n", (int)CFGetRetainCount(ct_font), (int)CFGetRetainCount(cg_font));
```

```
 Before:
ct_font: 1
cg_font: 2
 After:
ct_font: 5
cg_font: 2
 after typesetter release:
ct_font: 3
cg_font: 2
 after attr_string release:
ct_font: 3
cg_font: 2
 after string_ref release:
ct_font: 3
cg_font: 2
 after ct_font release:
ct_font: 2
cg_font: 2
 after cg_font release:
ct_font: 2
cg_font: 1
 after provider release:
ct_font: 2
cg_font: 1
```

**Comment by ebraminio** [comment]
Hey guys, any other pointer on this, specially some help on making ctfont from memory on my simple to compile and run snippet? I asked on [stackoverflow](http://stackoverflow.com/q/40805382/1414809) also to see if I am missing some point on cg/ctfont releases.

**Comment by ebraminio** [comment]
Seems [CTFontManagerCreateFontDescriptorFromData](http://stackoverflow.com/questions/40805382/how-to-avoid-memory-leak-with-ctfontcreatewithgraphicsfont?noredirect=1#comment68866701_40805382) what was I needed here :) going for #361 ...

**Comment by behdad** [comment]
> Seems CTFontManagerCreateFontDescriptorFromData what was I needed here :) going for #361 ...

What's the catch?  I still don't get it.

**Comment by ebraminio** [comment]
> What's the catch? I still don't get it.

Honestly I can't say confidently if this is a right bug or not (I don't know if `@autoreleasepool` helps it or not) but if we assume so, #361 perhaps helps it, AFAIK

**Comment by ebraminio** [comment]
This seems far from real world cases so lets close it, #367 could workaround it however.
