### ISSUE TITLE
incompatibility with FT_SET_TRANSORM?

### ISSUE THREAD

**Issue by lamelizard** [behdad/harfbuzz#295]
Thank you for this software, it's great.

I'm using HarfBuzz 1.2.7 with Freetype and it's working well, except then I try to transform the font with FT_SET_TRANSFORM, It may be my code that's wrong, though;
First I load an Freetype font, then I transorm it with a matrix that spins the result counterclockwise ans after that I load it into harfbuzz and then render it (I hope these steps were correct?);
The result is that every single glyph is spinned, rather then the full text (It should look like it's going from the bottom left to the top right but the result is on an horizontal row which looks kursiv, just the other way around).
According to the Bug report #252 Harfbuzz uses  FT_GET_ADVANCE (I found it in hb_ft_get_glyph_[h/v]_advance);
But in [https://www.freetype.org/freetype2/docs/reference/ft2-quick_advance.html#FT_Get_Advance](url) it's written that this function does not return the transformed values. And this it what the result looks like: Spinned Glyphs with "not spinned" advances.
This may also be related to 
> We don't handle / allow for emboldening / obliqueing.

from hb-ft.cc, but I'm not quite sure.
So what I want to ask is:
Is transformation supported and I just did it wrong? Is it something that is planned to work in the future (if it doesn't allready)? Or is it something which is known to not work but not considered important?

**Comment by behdad** [comment]
That's not going to work.  You have to shape and transform the resulting positions yourself.
