### ISSUE TITLE
BCP47 lang tag to OT langtag mapping: zh-MO and zh-Hant-HK are mapped to ZHT

### ISSUE THREAD

**Issue by jungshik** [behdad/harfbuzz#300]
Test page: http://jungshik.github.io/noto/locltest/locl-test.html

The last three segments in red should all have 'HK' and identical. They're lang-tagged with 'zh-HK', 'zh-Hant-HK' and 'zh-MO'.  However, the latter two are mapped to 'ZHT' instead of 'ZHH' ('TW' is shown in place of 'HK' in both Chrome and Firefox). 

The heuristics in hb-ot-tag.cc needs a bit of adjustment. 

The test font comes from https://github.com/adobe-fonts/locl-test and locl-test.htmll is slightly modified to include zh-Hant-HK and zh-MO. 

/cc @kenlunde

**Comment by behdad** [comment]
cc @brawer

**Comment by jungshik** [comment]
@kenlunde, do you agree that it's better to map zh-MO (and zh-Hant-Mo) to ZHH instead of ZHT?

**Comment by behdad** [comment]
Fixed 'zh-Hant-HK'; waiting for confirmation from Ken re MO.

**Comment by kenlunde** [comment]
@jungshik: Yes, the most appropriate mapping for zh-MO (and friends) would be to ZHH rather than ZHT.

**Comment by behdad** [comment]
Thanks.  All fixed.

**Comment by kenlunde** [comment]
🍻
