### ISSUE TITLE
Make Mongolian contextual forms after Narrow NBSP available even if in different font faces.

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [behdad/harfbuzz#301]
Inspired by [Bugzilla@Mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=490534)
In many Mongolian typefaces, some vowel letters has contextual forms after [NNBSP](https://en.wikipedia.org/wiki/Narrow_no-break_space) to produce suffixes as _-i_, _-u/ü_, _-un/ün_. They should be available even if NNBSP is display by different font face.

**Comment by KrasnayaPloshchad** [comment]
On a web site https://r12a.github.io/scripts/mongolian/variants I found some materials has mentioned the usage of NNBSP at the further reading section, so I think Mongolian contextual forms after Narrow NBSP should weok independent of font faces.

**Comment by behdad** [comment]
Not going to happen.

**Comment by KrasnayaPloshchad** [comment]
On Firefox 49 I found NNBSP seems works with Mongolian/Manchu text, but ZWJ still depends on specific font.
