### ISSUE TITLE
Collapsed advance widths when shaping with Padauk font

### ISSUE THREAD

**Issue by drott** [behdad/harfbuzz#305]
Running `hb-shape`or `hb-view` with the SIL Padauk font  from http://software.sil.org/padauk/download/ and Latin characters results in 0 advance width and collapsed rendering. This leads to broken rendering with that font in Chrome. Presumably, for the same reason the rendering with this font is broken in Firefox.

This might be a font bug.

*Padauk 2.8:*
`~/dev/harfbuzz/util/hb-view padauk-2.80/Padauk-book.ttf "abcdefg" > padauk_2_8.png`
![padauk_2_8](https://cloud.githubusercontent.com/assets/1021784/18010384/f32058be-6bb8-11e6-907f-81cefc61a22d.png)

*Padauk 3.0*
` ~/dev/harfbuzz/util/hb-view padauk-3.0/Padauk-book.ttf "abcdefg" > padauk_3_0.png`

![padauk_3_0](https://cloud.githubusercontent.com/assets/1021784/18010391/f8893a32-6bb8-11e6-8a23-be7831b9714c.png)

**Comment by jfkthame** [comment]
Yes, this is a font bug - the GDEF table in Padauk gives class 3 (mark) to lots of Latin glyphs that should be normal base glyphs, not marks. That results in their widths being zeroed.

@mhosken, could you look into this?

**Comment by mhosken** [comment]
Oops! Yes. I'll fix that. Will need to do a new release, which will take a while :(. This is an example of some testing code leaking from our battles to get OpenType working for this font. If only the battle weren't so fierce.

**Comment by ebraminio** [comment]
Nothing to do on harfbuzz side then so lets close it. Thank you all.
