### ISSUE TITLE
Incorrect layout of accented characters

### ISSUE THREAD

**Issue by manuel-rhdt** [behdad/harfbuzz#307]
When I typeset e.g. V̂ (regular V with combining circumflex accent) I get bad positioning using the Latin Modern Roman Font with hb-view and the ot-shaper. However when using the coretext shaper everything looks alright. Maybe I need to use certain font features or am I missing something else?

ot rendering:
![ot](https://cloud.githubusercontent.com/assets/3199013/18069031/c4a59254-6e44-11e6-8b4a-de9ca5a71456.png)

coretext rendering:
![coretext](https://cloud.githubusercontent.com/assets/3199013/18069013/a7593b6a-6e44-11e6-9e26-b941347f4a81.png)

**Comment by khaledhosny** [comment]
Latin Modern does not have any mark positioning information so the bad positioning is a font issue. My guess is that Core Text is doing fallback positioning based on glyph metrics. HarfBuzz supports can do fallback positioning as well, but it applies it only to fonts lacking GPOS table.

The proper way forward here is to get the font extended with mark positioning information.

**Comment by behdad** [comment]
Closing unless there's any actionable proposal.  I personally don't think we should do any fallbacks if GPOS is present.

**Comment by moyogo** [comment]
The fallback for mark positioning could kick in if there's no mark-related feature in GPOS or more generally if the GPOS features don't move the diacritics.

**Comment by behdad** [comment]
> The fallback for mark positioning could kick in if there's no mark-related feature in GPOS or more generally if the GPOS features don't move the diacritics.

Yes but that might mess up with designer intention.  I'm not totally against it, but so far it wasn't a big deal.

We do the same thing with kerning: only apply TrueType kern table only if there's no GPOS at al.

**Comment by KrasnayaPloshchad** [comment]
> The fallback for mark positioning could kick in if there's no mark-related feature in GPOS or more generally if the GPOS features don't move the diacritics.

I think this can be implement but disabled by default, i.e. using an API to configure this to enable.
