### ISSUE TITLE
Do fine-grained mark fallback placement if mark was not attached?

### ISSUE THREAD

**Issue by behdad** [behdad/harfbuzz#317]
cc @khaledhosny

**Comment by khaledhosny** [comment]
I’ve been thinking about this, and I’m increasingly with the opinion of keeping things as they now as I fear that any more complex heuristic can fail in some edge cases. For example I can think of fonts that intentionally don’t move combining marks over some glyphs, e.g. lower case o or e, and a heuristic that tries to do positioning fallback when the mark is not moved will kick in here and might give unintended result.

**Comment by behdad** [comment]
Agree.  Let's leave as is.  We'll reevaluate in another five years :)
