### ISSUE TITLE
harfbuzz won't compile

### ISSUE THREAD

**Issue by dennisr35** [behdad/harfbuzz#319]
I try to complile harfbuzz, but got some errors.

Nmake /f Makefile.vc CFG=release

I had to rename the config.h.win32.in and hb-version.h.in files (delete .in). This removed some errors, but now the following include files are missing:
hb-buffer-deserialize-json.hh
hb-ot-shape-complex-myanmar-machine.hh
hb-ot-shape-complex-indic-machine.hh
hb-ot-shape-complex-use-machine.hh

I use VC2015

**Comment by brawer** [comment]
These files are generated using Ragel, an open-source compiler for finite-state machines. Here’s a project that builds Ragel, calls it to generate the HarfBuzz files, and then compiled HarfBuzz. I’m currently using the gyp build system for my project; of course, your setup might be different, it really depends on your build system.
https://github.com/googlei18n/fontview
https://github.com/googlei18n/fontview/blob/master/src/third_party/harfbuzz/harfbuzz.gyp#L74

**Comment by brawer** [comment]
Ragel: http://www.colm.net/open-source/ragel/

**Comment by khaledhosny** [comment]
The simplest way to build on Windows with NMake is to use release tarballs, otherwise you will need to generate the generated files your self as @brawer explained.

**Comment by ebraminio** [comment]
HarfBuzz release tarballs are [here](https://www.freedesktop.org/software/harfbuzz/release/) and you should be able to run nmake for its build. We have also a working Windows CI configuration [here](https://github.com/behdad/harfbuzz/blob/master/appveyor.yml) that possibly would be useful (it uses [msys2](https://msys2.github.io/)). As a bug tracker is not best place for asking support, I suggest using [stackoveflow](stackoverflow.com/questions/tagged/harfbuzz) or [harfbuzz mailing list](https://lists.freedesktop.org/mailman/listinfo/harfbuzz/) for further discussions.

**Comment by dennisr35** [comment]
I downloaded the tarball and it worked. thanks
