### ISSUE TITLE
hb-view --width option

### ISSUE THREAD

**Issue by mhlakhani** [behdad/harfbuzz#32]
pango-view has a --width option which automatically breaks lines that are longer than a specified width. Are there any plans to add something similar to hb-view?

**Comment by ebraminio** [comment]
How about reserving this for [hb_shape_dwrite_experimental_width](https://github.com/behdad/harfbuzz/blob/master/src/hb-directwrite.cc#L918) like APIs?

**Comment by behdad** [comment]
> How about reserving this for hb_shape_dwrite_experimental_width like APIs?

When we add that we should also add a --justify option.  So, the two can be added separately.
