### ISSUE TITLE
[ot1.8] Apply ‘rvrn’ feature for variations

### ISSUE THREAD

**Issue by brawer** [behdad/harfbuzz#320]
The `opentype-gx` branch should activate the [‘rvrn’ feature](https://www.microsoft.com/typography/otspec180/features_pt.htm#rvrn).

**Comment by behdad** [comment]
Fixed in opentype-gx branch.

**Comment by KrasnayaPloshchad** [comment]
This is useful to implement muliltiple font weights, this article has an example on Latin and CJK:
http://www.typeisbeautiful.com/2016/09/10968/zh-hant/

Also, I found a HarfBuzz developer appearing in this article.
