### ISSUE TITLE
Argument signedness of hb_buffer_add* functions

### ISSUE THREAD

**Issue by drott** [behdad/harfbuzz#321]
I am trying to sanitize and compile `Source/platform/fonts` of Blink with `-Wconversion` to avoid integer truncation and overflow errors that are hard to detect otherwise.

One thing I noticed is that most of the 
`hb_buffer_add_*` functions take `int`s for `text_length` and `item_length`

When can these be negative, what's the reason for this argument type? 

The arguments to these functions on the blink side are `unsigned`s and can never be `< 0`, so I am trying to understand what the purpose of the type could be and whether we could/should perhaps change those to `unsigned` or `size_t`.

**Comment by behdad** [comment]
They take -1 to mean "0-terminated string".

**Comment by behdad** [comment]
A scheme copied from glib and other C libraries, though admittedly, not best design.
