### ISSUE TITLE
Unrecognized Ideographic Variation Sequence char should be ignored, not become space

### ISSUE THREAD

**Issue by brawer** [behdad/harfbuzz#323]
With the attached font [TestCMAP14.otf](https://github.com/behdad/harfbuzz/files/488115/TestCMAP14.otf.zip), HarfBuzz shapes U+82A6 U+E0102 into `uni82A6_uE0100` at position (0,0) followed by `space` at (1000,0). The first glyph is expected since the font does not define a variation for U+E0102, but the space is rather surprising. Compare to CoreText, which emits just uni82A6_uE0100 at (0,0) without a space.
https://raw.githack.com/brawer/fonttest/master/reports/FreeStack.html#CMAP-1
https://raw.githack.com/brawer/fonttest/master/reports/CoreText.html#CMAP-1

**Comment by KrasnayaPloshchad** [comment]
This need to check which sequence is supported by font.

**Comment by brawer** [comment]
Yes, “unrecognized” = ”not in the font’s cmap table”.

**Comment by behdad** [comment]
The space is zerowidth and harmless.  This is WAI.

**Comment by behdad** [comment]
At some point there will be API to configure this, but you should not rely on this.  Same thing about ZWJ / ZWNJ, and many other "default-ignorable" characters.
