### ISSUE TITLE
static version of run-time library

### ISSUE THREAD

**Issue by dennisr35** [behdad/harfbuzz#325]
I try to build harfbuzz with VC2015 with static version of run-time library. This is the /MT compiler switch. As Harfbuzz uses makefiles I am not sure how to specify the compiler switch.

Thanks

**Comment by khaledhosny** [comment]
How are you building HarfBuzz, using autotools or nmake?

**Comment by dennisr35** [comment]
nmake. I already found a solution editing the make files.
