### ISSUE TITLE
harfbuzz-1.3.2 (and 1.3.1) fail shaping/vertical.tests on Gentoo

### ISSUE THREAD

**Issue by PPed72** [behdad/harfbuzz#337]
See also: https://bugs.gentoo.org/show_bug.cgi?id=596124
```
# cat /var/tmp/portage/media-libs/harfbuzz-1.3.2/work/harfbuzz-1.3.2-abi_x86_64.amd64/test/shaping/test-suite.log
=================================================
   HarfBuzz 1.3.2: test/shaping/test-suite.log
=================================================

# TOTAL: 21
# PASS:  20
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: tests/vertical
====================

Running tests in /var/tmp/portage/media-libs/harfbuzz-1.3.2/work/harfbuzz-1.3.2/test/shaping/tests/vertical.tests
Testing fonts/sha1sum/191826b9643e3f124d865d617ae609db6a2ce203.ttf:U+300C
Actual:   [uni300C.vert=0@-448,-578+0,-1024]
Expected: [uni300C.vert=0@-512,-578+0,-1024]
1 tests failed.
```
[harfbuzz-1.3.2:20161004-094340.log.gz](https://github.com/behdad/harfbuzz/files/508098/harfbuzz-1.3.2.20161004-094340.log.gz)

**Comment by khaledhosny** [comment]
Can you reproduce the failure with older versions of HarfBuzz, or is it specific to 1.3.2 and 1.3.1? I can’t reproduce this locally.

**Comment by PPed72** [comment]
In data martedì 4 ottobre 2016 03:33:30 CEST, Khaled Hosny ha scritto:
> Can you reproduce the failure with older versions of HarfBuzz, or is it
> specific to 1.3.2 and 1.3.1? I can’t reproduce this locally.

1.2.7 worked fine for me.

-- 
Paolo Pedroni
Email: paolo.pedroni<at>iol.it

**Comment by khaledhosny** [comment]
There are not that many commits between 1.2.7 and 1.3.1, so it would be helpful if you can git bisect them to find the commit introducing this. At a first glance I don’t see anything that could be related.

**Comment by PPed72** [comment]
In data martedì 4 ottobre 2016 04:36:47 CEST, Khaled Hosny ha scritto:
> There are not that many commits between 1.2.7 and 1.3.1, so it would be
> helpful if you can git bisect them to find the commit introducing this. At
> a first glance I don’t see anything that could be related.

It must be some dependency, because now 1.2.7 fails as well...

I'll try to see what might have caused it.

-- 
Paolo Pedroni
Email: paolo.pedroni<at>iol.it

**Comment by PPed72** [comment]
Which version of glib are you using? I have 2.48.2 on my system which is failing tests, while I had 2.46.2 last time tests succeeded. Sadly I can't downgrade glib to test if it's the real culprit. Everything else that's changed between then and now does not make a difference...

**Comment by khaledhosny** [comment]
I have 2.48.2 here as well. Though I think glib is unlikely to be involved in this, FreeType is a more likely candidate.

**Comment by behdad** [comment]
Definitely FreeType change.

**Comment by PPed72** [comment]
The only thing that changed in freetype is that I enabled infinality. Tomorrow I will check for that.
-- 
Paolo Pedroni
Email: paolo.pedroni<at>iol.it
Il 04 ott 2016 6:44 PM, Behdad Esfahbod <notifications@github.com> ha scritto:Definitely FreeType change.

**Comment by behdad** [comment]
> The only thing that changed in freetype is that I enabled infinality

That always explains everything!!

**Comment by khaledhosny** [comment]
@PPed72 did you try without Infinality?

**Comment by PPed72** [comment]
Yes, I did, and it worked. It seems I forgot to follow up on this thread, sorry.
