### ISSUE TITLE
[hb-coretext] Hook up 'kern' feature to kCTKernAttributeName

### ISSUE THREAD

**Issue by behdad** [behdad/harfbuzz#338]
Right now it's not possible to disable kerning in hb-coretext.  As seen here:
https://bugs.chromium.org/p/chromium/issues/detail?id=648190

**Comment by behdad** [comment]
Cosimo and I started implementing this, but the docs for kCTKernAttributeName made me think it adds extra kerning, aka tracking aka letter-spacing.  So I asked Ned.  Ned confirmed that it's a "weird tristate thing". Ie. (my interpretation) if you don't set it, you get default kerning.  If you set it to zero, it disables kerning.  If you set it to non-zero, it adds extra letter-spacing / tracking on top of default kerning.  So yeah, we can use this.  Will try to finish it today.

**Comment by drott** [comment]
Great, thank you both. Am I right that in the way we use HarfBuzz from Blink, i.e. with a new hb_buffer setup for each word we would not be affected by the "can't re-enable kerning" problem that you're observing?

**Comment by behdad** [comment]
> Great, thank you both. Am I right that in the way we use HarfBuzz from Blink, i.e. with a new hb_buffer setup for each word we would not be affected by the "can't re-enable kerning" problem that you're observing?

Correct.  In particular, we do not apply features to subranges of the buffer in Chrome or Firefox.
