### ISSUE TITLE
CoreText include fails configure on iOS.

### ISSUE THREAD

**Issue by ryanbartley** [behdad/harfbuzz#342]
I've looked through much of the available literature on this and saw that it was resolved with #34, but something in the logic is preventing me from configuring with CoreText on iOS. I can see [here](https://github.com/behdad/harfbuzz/blob/master/configure.ac#L407) that the logic is in place but can't figure out how to get past this...
```
checking for CTFontRef... no
checking for CTFontRef... (cached) no
configure: error: CoreText support requested but libcoretext not found
```
[Here](https://gist.github.com/ryanbartley/1b506f6b25d9653daf2579e9f4198e6b)'s my config.log from the build. As you'll see, the test of `#include <CoreText/CoreText.h>` doesn't run after the `#include <ApplicationServices/ApplicationServices.h>` test fails. I've seen that vlc had to change the logic to remove ApplicationServices completely and while that's an option I'd rather not hot patch my build system as it seems like this logic should be working. Any help would be greatly appreciated!

Edit: After a bit more research, the problem is not in `configure.ac` as I originally thought but in the configure script itself. If i `sed` the ApplicationServices include with the CoreText include and `sed` the frameworks, it configures and builds. I'll dig deeper.

**Comment by khaledhosny** [comment]
I think this line is the where to start:
```
checking for CTFontRef... (cached) no
```

It shows that the second check for CTFontRef is not actually executed (and the log suggests this otherwise), and instead the cached value from the first check is used.

**Comment by ryanbartley** [comment]
Thanks for the fast reply. Unfortunately, I'm pretty new to this toolchain configure stuff. [Here's](https://gist.github.com/ryanbartley/0fb50d7abb619438ec4a633e859d9c14) what I believe is the pertinent logic from the configure script and though I haven't really worked with configure scripts before, the logic seems to be correct. Am I missing something?

**Comment by khaledhosny** [comment]
It seems that `AC_CHECK_TYPE` caches its result, and the second call just takes the cached value. You probably need to ask in some autotools forum to get answers from more knowledgeable people.

**Comment by jfkthame** [comment]
Presumably, you could simply work around the problem by replacing CTFontRef in the second of the checks with a different Core Text type (e.g. CTRunRef), so that it won't use the cached result.

**Comment by khaledhosny** [comment]
I guess that would work.
