### ISSUE TITLE
Cham medial Ra (u+AA34)

### ISSUE THREAD

**Issue by ohbendy** [behdad/harfbuzz#348]
Image shows consonant ka (u+AA06) with medial Ra (AA34) following in Noto Sans Cham, displayed in Firefox 49.0:
<img width="70" alt="screen shot 2016-10-12 at 09 07 21" src="https://cloud.githubusercontent.com/assets/12471463/19295012/bac62026-905b-11e6-8784-bb705ffc39f8.png">
However, as in Burmese, the medial Ra ought to appear before the consonant, as indicated in Unicode proposal n3120:
<img width="827" alt="screen shot 2016-10-12 at 09 09 42" src="https://cloud.githubusercontent.com/assets/12471463/19295015/be95bae0-905b-11e6-83b5-a6cce676ad8d.png">
Though it's a font for Western Cham, as opposed to Eastern Cham, the font CJM Kh 001 takes care of this by including precomposed combinations of medial Ra with every consonant (inefficient):
<img width="60" alt="screen shot 2016-10-12 at 09 13 25" src="https://cloud.githubusercontent.com/assets/12471463/19295060/27ba4f40-905c-11e6-9ea3-84f5b8fc5faa.png">

**Comment by jfkthame** [comment]
In the copy of Noto Sans Cham that I have on hand, at least, there's no `pref` feature. Note that the [USE spec](https://www.microsoft.com/typography/OpenTypeDev/USE/intro.htm#reordering) explicitly says:

> Note that prebase medial consonants (CONS_MED_PRE) do not get reordered automatically by USE. Rather, the font designer is expected to use the `<pref>` feature to signal when a glyph belonging to this class should be reordered through the application of the pref feature. Only one glyph per cluster can be reordered using `<pref>`.

So the first thing to do is to ensure an appropriate `pref` feature is added to the font; then re-test. (From a brief look at the code, I think this will fix the problem.)

**Comment by ohbendy** [comment]
Ah, I see, thanks. Any ideas for the syntax in the <pref> feature for this?

**Comment by behdad** [comment]
Right.  Noto Sans Cham has bogus tables.

**Comment by marekjez86** [comment]
@ohbendy : I'm not sure if you were working on the newest Noto Cham but it should be fixed in https://github.com/googlei18n/noto-fonts-alpha/blob/master/from-pipeline/unhinted/otf/sans/NotoSansCham-Regular.otf (other weights are there also; ttf files are in https://github.com/googlei18n/noto-fonts-alpha/blob/master/from-pipeline/unhinted/ttf/sans/ )

**Comment by marekjez86** [comment]
@jfkthame : it should be fixed in https://github.com/googlei18n/noto-fonts-alpha/blob/master/from-pipeline/unhinted/otf/sans/NotoSansCham-Regular.otf (other weights are there also; ttf files are in https://github.com/googlei18n/noto-fonts-alpha/blob/master/from-pipeline/unhinted/ttf/sans/ )

**Comment by ohbendy** [comment]
Thank you. I just opened the OTF in Glyphs, but it's not showing any OT features.

**Comment by punchcutter** [comment]
I just checked and all the Cham in that folder are broken. They have no GDEF/GPOS/GSUB tables. Same for Devanagari and Myanmar. I assume pretty much everything in there is broken if it was built with the same version of tools.

**Comment by marekjez86** [comment]
@punchcutter , @ohbendy : my bad. looks to me that I used wrong command for the fontmake. here's the updated font (I rebuilt and quickly checked for the tables, but I haven't fully tested them). I need to rebuild the rest

[NotoSansCham.zip](https://github.com/behdad/harfbuzz/files/991194/NotoSansCham.zip)

**Comment by punchcutter** [comment]
@marekjez86 Those look ok now for medial Ra. Kerning (and GPOS in general) is partially broken as reported here: https://github.com/fonttools/fonttools/issues/950

**Comment by marekjez86** [comment]
[NotoSansCham.zip](https://github.com/behdad/harfbuzz/files/1039204/NotoSansCham.zip)

@jfkthame ,  @ohbendy : the above should be correct now (rebuilt the fonts after https://github.com/fonttools/fonttools/issues/950 was fixed)
