### ISSUE TITLE
why they use 'kana' for both script tag

### ISSUE THREAD

**Issue by prepare** [behdad/harfbuzz#350]
@behdad 
Hello sir, 

In OpenType Spec,
https://www.microsoft.com/typography/otspec/scripttags.htm 

     Desc            |   tagname
     ---             ---
     Hiragana 	     |   kana 
     Katakana        |   kana

Do you known why they use  'kana' for both script name.
I don't see duplicate items in other name

:)

**Comment by KrasnayaPloshchad** [comment]
To my eyes, both Hiragana and Katakana are used in Japanese, and they require the same implementations for their typography.

**Comment by behdad** [comment]
Heya,

No idea really why they decided these should be merged.  Maybe because it's the only case where multiple Unicode scripts are commonly used to write one language.  At any rate, we just follow the standard here.

**Comment by KrasnayaPloshchad** [comment]
> Maybe because it's the only case where multiple Unicode scripts are commonly used to write one language.

You can see the exanple here: https://www.w3.org/TR/jlreq/

**Comment by prepare** [comment]
Thank you everyone.
I send e-mail to mstwsite at microsoft.com for this.
The below is the reply.
I've asked him (Basit Ali) for permission to post to this thread too.

> Hello,
> 
> 
> 
>  
> 
> Below is a reply from one of our engineers. I hope this helps.
> 
>  
> 
> Basically, it’s done that way on the assumption that, for purposes of OpenType Layout processing, there’s never a need to distinguish between them, or even that they should be combined together during processing.
> 
>  
> 
> For instance, if an implementer wanted to kern (say) Thai and Hiragana glyphs, they’d have to do extra work to make that happen. But if you want to kern Hiragana and Katakana glyphs, then that’s no more difficult than kerning two Latin glyphs.
> 
>  
> 
> Thanks,
> 
> Ali
