### ISSUE TITLE
Add a function to rotate the buffer

### ISSUE THREAD

**Issue by khaledhosny** [behdad/harfbuzz#354]
It seems that almost every HarfBuzz client doing vertical text that I checked will reverse the positions returned by HarfBuzz for vertical text to use them as if they were horizontal. May be we should have a
~~buffer option~~ a function to do this in HarfBuzz since it seems to be the most common use? (this is mainly because every time I do it I get it wrong the first few iterations 😃).

**Comment by KrasnayaPloshchad** [comment]
This would be helpful to get better behavior to render Old Hangul on vertical layout. CC @kenlunde

**Comment by behdad** [comment]
> This would be helpful to get better behavior to render Old Hangul on vertical layout.

No.

**Comment by behdad** [comment]
Let's close now as really low prio.
