### ISSUE TITLE
Harfbuzz and mac os Sierra

### ISSUE THREAD

**Issue by MayuraVerma** [behdad/harfbuzz#359]
I want to know how to make harfbuzz default shaping engine in mac OS Sierra system wide and all applications. 

Is it possible?

If need to role it back to coretext later, can I do?

I know this is not an issue. I couldn't find the answer anywhere, please assist.

**Comment by khaledhosny** [comment]
You can’t generally do that.

**Comment by MayuraVerma** [comment]
But the harfbuzz has homebrew script for Mac. I am curious what is point of installing Mac, if it can't be used with any application? 

Also on the OS support section of harfbuzz, it's confirm to support unix based system.

Coretext engine in Mac OS is horrible. If there is a way to replace that with harfbuzz for Indic scripts, specifically KANNADA language, I want to try. Please assist.

**Comment by khaledhosny** [comment]
> But the harfbuzz has homebrew script for Mac. I am curious what is point of installing Mac,

That is for applications that use HarfBuzz directly.

> if it can't be used with any application?

It can be used by plenty of applications, just not the applications that use Core Text.

> Also on the OS support section of harfbuzz, it's confirm to support unix based system.

That does not mean you can use it as a drop in replacement for Core Text. Applications that use HarfBuzz need to do so explicitly or through other libraries that use HarfBuzz.
