### ISSUE TITLE
Optical size API, hooked up to CoreText (was Support AAT trak table)

### ISSUE THREAD

**Issue by drott** [behdad/harfbuzz#360]
Part of [crbug.com/627609](https://crbug.com/627609) seems to be about `trak` table support for the San Francisco font. We currently lack support for this in `hb-coretext`.

**Comment by drott** [comment]
Discussed with Behdad: resolution would be to shape at intended point size using the CTFont, so that CoreText can apply correct advance width tracking. On the Blink side, we calculate a pt size from the CSS pixels, using the fixed 96dpi assumed screen pixel density of the [CSS reference pixel](https://www.w3.org/TR/css3-values/#reference-pixel).

**Comment by drott** [comment]
Behdad, any update? We're receiving some requests in Chrome to prioritise this. Thank you!

**Comment by behdad** [comment]
A few weeks...

**Comment by aziz** [comment]
Any update on this? Chrome still has major kerning issues rendering "San Fransisco" font on macOS

**Comment by behdad** [comment]
Soonish.. :)

**Comment by behdad** [comment]
Reopening till we test and confirm.

**Comment by drott** [comment]
Apparently what needs to be specified to CoreText for the point size argument of the call creating the UI font is not really points but CSS pixels, so the hb_font_ptem API may still change.
