### ISSUE TITLE
Consider moving to a CTFont based face constructor on Mac

### ISSUE THREAD

**Issue by drott** [behdad/harfbuzz#361]
In Chrome, we're creating a `CGFont` specifically for shaping, see `FontPlatformData::cgFont`, then internally, HarfBuzz creates a `CTFont` out of it again. This code path covers the dreaded `CTFontCreateWithGraphicsFont` mentioned in issue #291, so we might get this potential leak out of the way as well.

hb-coretext, IIRC, has two functions, one making tables available for the OpenType shaper, one, providing the fallback AAT shaper.

`hb_face_create` conceptually accepts an argument that does not contain a font size. A `CGFont` in that sense may be conceptually closer.

However, if we want to fix trak table support, issue #360, we might need to recreate a `CTFont` for each new font size shaping run, profiting less from caching a size independent face.

**Comment by ebraminio** [comment]
I think we decided to not go on this path, if not, #367 simply can be revived.
