### ISSUE TITLE
Burmese နု် (U+1014 U+102F U+103A) mis-renders

### ISSUE THREAD

**Issue by bhamiltoncx** [behdad/harfbuzz#365]
The Burmese grapheme နု် (U+1014 U+102F U+103A) mis-renders, even in the latest Android 7.1.

See attached image.

![burmese_android_bug_1014_102f_103a](https://cloud.githubusercontent.com/assets/671827/20281513/a1b9e468-aa65-11e6-89ba-0d9196c2e1da.png)

**Comment by KrasnayaPloshchad** [comment]
This is also mis-renders to me, even if I use Padauk and Myammar Text font on BabelPad, but when I reorder as န်ု (U+1014 U+103A U+102F), it works to me.
![test with myammar text](https://cloud.githubusercontent.com/assets/10364351/20333208/fe3ef584-abeb-11e6-8556-7c9e77c1b46c.PNG)
![test with padauk](https://cloud.githubusercontent.com/assets/10364351/20333221/080d06e6-abec-11e6-98a1-18aa03bb92e8.PNG)

Here is my test with `hb-view`
Myammar Text:
![result](https://cloud.githubusercontent.com/assets/10364351/20333249/3424c43a-abec-11e6-8ed1-7b019f2c19bc.png)
Padauk:
![result2](https://cloud.githubusercontent.com/assets/10364351/20333257/4375af58-abec-11e6-97d4-aec7769b9a44.png)

**Comment by Richard57** [comment]
The spelling with the vowel before the asat is simply wrong; the renderer is doing its job by highlighting an otherwise invisible spelling error.  The correct coding is given in the Unicode Standard in Section 16.3 Myanmar - http://www.unicode.org/versions/Unicode9.0.0/ch16.pdf under the heading 'Contractions'.  The literal transliteration of the pronoun is <kywannup>, which itself strongly indicates that the sequence should be <asat, sign u>.

**Comment by lianghai** [comment]
See the Table 16-3 in the Section 16.3 Myanmar for the syllable structure defined by the Unicode Standard, and OpenType's spec at: https://www.microsoft.com/typography/OpenTypeDev/myanmar/intro.htm#well

HarfBuzz's implementation of the OT spec is in this file: https://github.com/behdad/harfbuzz/blob/master/src/hb-ot-shape-complex-myanmar-machine.rl

Unicode's analysis and OT's spec don't allow _asat_ immediately after vowel sign U.

**Comment by bhamiltoncx** [comment]
Hmm. It seems we're in a pickle, then to represent the _nnu_ syllable.

Re-ordering to <na, asat, sign u> (U+1014 U+103A U+102F) as the Unicode standard suggests renders incorrectly on macOS 10.12.1 (and, I believe, iOS):

န်ု (U+1014 U+103A U+102F)

whereas <na, sign u, asat> (U+1014 U+102F U+103A) renders correctly on macOS and iOS, but mis-renders on Android:

နု် (U+1014 U+102F U+103A)

Screenshot on macOS 10.12.1:

<img width="391" alt="screen shot 2017-01-03 at 9 44 51 am" src="https://cloud.githubusercontent.com/assets/671827/21617134/99f913ba-d199-11e6-8d4e-1bb6bb0c30e4.png">

Unless I'm misunderstanding, that means there is a bug in macOS and iOS, which also means there is no way to represent this syllable in a manner which works across Android and iOS until Apple fixes their bug.

I can report this to Apple, but is there any work around in the mean time that folks can think of?

**Comment by KrasnayaPloshchad** [comment]
@bhamiltoncx What happened if you try another fonts (such as Padauk)?

**Comment by bhamiltoncx** [comment]
@KrasnayaPloshchad: It looks like Padauk on macOS does resolve the issue. (The default Myanmar font on macOS (and, I believe, iOS), appears to be Myanmar Sangam MN, which shows the buggy behavior).

Here's what I see:

![screen shot 2017-01-03 at 11 18 33 am](https://cloud.githubusercontent.com/assets/671827/21619855/6c8f86ea-d1a6-11e6-8a4d-d04e8547acb0.png)

Unfortunately, we're still going to have trouble on iOS, since the user cannot replace the system font there without rooting the device, as far as I know.

Even if we license Padauk and ship it with all our apps and override the font inside each app, I believe we cannot override the system's font for content outside the app like push notifications, emails, etc.

**Comment by bhamiltoncx** [comment]
I filed a bug on Apple to track this issue (rdar://29851286) and copied it to OpenRadar:

https://openradar.appspot.com/radar?id=6093041815257088

**Comment by KrasnayaPloshchad** [comment]
> Unfortunately, we're still going to have trouble on iOS, since the user cannot replace the system font there without rooting the device, as far as I know.

iOS does not have the term “root” in this sense, instead is jailbreaking.

**Comment by lianghai** [comment]
Btw, the macOS/iOS issue @bhamiltoncx noticed is an issue in Apple's AAT fonts Myanmar MN and Myanmar Sangam MN, which are unrelated to OpenType.

**Comment by behdad** [comment]
What's the verdict here?

**Comment by bhamiltoncx** [comment]
Apple bug, filed on then, but we might want to make Harfbuzz less strict
here to match their behavior.

**Comment by behdad** [comment]
> we might want to make Harfbuzz less strict here to match their behavior.

Do you know what Windows does?

**Comment by KrasnayaPloshchad** [comment]
@bhamiltoncx You can try [this virtual machine](https://dev.windows.com/en-us/microsoft-edge/tools/vms/) if you want to know what Windows does.

**Comment by bhamiltoncx** [comment]
I realize now that Harfbuzz is doing the right thing. Masking spelling errors like this is at best misleading, and at worst a security bug:

https://marc.durdin.net/2017/03/when-phishers-eat-rice/

Let's just close this. Thanks for your patience!
