### ISSUE TITLE
[ot1.8] Support 'vrtr' feature

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [behdad/harfbuzz#366]
The OpenType specification introduced a new feature `vrtr` for vertical layout several months ago. This can be used for Western-style punctuations to make them presented sideways in vertical writing.

See:
https://www.microsoft.com/typography/otspec/changes.htm
https://www.microsoft.com/typography/otspec/features_uz.htm#vrtr

**Comment by khaledhosny** [comment]
I don’t think HarfBuzz needs to do anything here, it is up to the client to activate this feature for sideways text runs. May be we need to make sure it is the last feature applied, but I think that is already the case for user features if the lookups are ordered correctly in the font.

**Comment by KrasnayaPloshchad** [comment]
So this feature should be implemented seperately in Firefox and LibreOffice?

**Comment by khaledhosny** [comment]
Yes, the client would set it explicitly on the side ways buffer. Unless @behdad thinks otherwise.

**Comment by behdad** [comment]
Yes, I think client should set.  I'm not quite comfortable with that, but cannot think of anything else right now. Though, we can add an additional property to the buffer, eg. `hb_buffer_set_line_direction()` or something.  But let's not rush into doing that.
