### ISSUE TITLE
 'TargetConditionals.h' file not found

### ISSUE THREAD

**Issue by mahmoudghonim** [behdad/harfbuzz#368]
In file included from /home/harfbuzz-master/src/hb-coretext.cc:32:
/home/harfbuzz-master/src/hb-coretext.h:32:10: fatal error:
'TargetConditionals.h' file not found
#include <TargetConditionals.h>
         ^
1 error generated.
ERROR    root: compiler frontend failed to generate LLVM bitcode, halting

************************
hb-coretext.h file:
**#include <TargetConditionals.h>**

**Comment by khaledhosny** [comment]
How are you building HarfBuzz, and on what platform?

**Comment by mahmoudghonim** [comment]
Platform : Linux Ubuntu 14.04.

Building Harfbuzz: 
./autogen.sh
./configure --prefix=/usr
make
reference: http://blog-archive.copyninja.info/2012/07/compiling_harfbuzz_on_debian.html

**Comment by khaledhosny** [comment]
Something is broken then, `hb-coretext.cc` should not be built on Linux, it is only for Mac. Please provide the full build log.

**Comment by khaledhosny** [comment]
Also using `--prefix=/usr` is very dangerous, this will overwrite your system-managed version of HarfBuzz upon `make install` which is something you shouldn’t be doing and can break your system. The default, which is `/usr/local` should be fine, so just drop the `--prefix=/usr`

**Comment by mahmoudghonim** [comment]
I successfully built it  on linux but I'm trying to compile harfbuzz using Emscripten to get harfbuzz as a bit code "harfbuzz.bc" or "harfbuzz.js"

**By using Emscripten you can:
Compile C and C++ code into JavaScript**

According to : https://github.com/TheCherno/Sparky/edit/3D/Dependencies/FreeType-Emscripten/em_build_freetype.bat
I'm trying to simulate sparky Emscripten Experience with "Harfbuzz".
http://pastebin.com/z5G3apC0

**but I faced Exception "helper-cairo-ansi.cc:28:"**

In file included from /home/mahmoud/Desktop/hello_world/harfbuzz-master/util/helper-cairo-ansi.cc:28:
/home/mahmoud/Desktop/hello_world/harfbuzz-master/util/options.hh:261:5: error: use of undeclared identifier
      'hb_ot_shape_glyphs_closure'
    hb_ot_shape_glyphs_closure (font, buffer, features, num_features, glyphs);
    ^
1 error generated.
ERROR    root: compiler frontend failed to generate LLVM bitcode, halting

**Comment by khaledhosny** [comment]
I know nothing about Emscripten, but there is https://github.com/prezi/harfbuzz-js

**Comment by mahmoudghonim** [comment]
yeah I know but there was a problems on it and  we posted an issue there.
https://github.com/prezi/harfbuzz-js/issues/6

Now, I'm trying to build it Manually from a-z as a plain "B" by simulating  sparky Emscripten Experience but I'm facing problems like the previous one.

Kindly, check link below.
https://www.youtube.com/watch?v=S9MV_FDHMfk
starting from duration 30:00 he is compiling freetype source code to bitcode "freetype.bc" and the other dependencies,  finally link all binaries with sparky source code to get "spark.html".
