### ISSUE TITLE
Why I'm getting 0 glyph index when using blob

### ISSUE THREAD

**Issue by SamehMahmoud** [behdad/harfbuzz#369]
Hello,
I need to use harbuzz without freetype, so, I'm creating hb_face_t * using the function hb_face_create

    int array_size=1024*59;
    char * array = new char[array_size];
    int pos = 0;
    ifstream fin("/home/sameh/Desktop/K-Sina.ttf");
    if(fin.is_open()){
        cout << "File is opended" << endl;

        while(!fin.eof() && pos < array_size){
            fin.get(array[pos]);
            pos++;
        }

        array[pos-1]='\0';
        cout << "reading array " << endl;
        cout << array[5] << endl;
    }

    hb_blob_t * blob;
    blob = hb_blob_create(array , sizeof(array) , HB_MEMORY_MODE_READONLY, NULL , NULL);
    hb_face_t * faceX;
    faceX = hb_face_create(blob , 0);
    hb_font_t * fontX = hb_font_create(faceX);
    hb_buffer_t * buffer;
    buffer = hb_buffer_create();
    string text = "السلام عليكم";
    size_t length = text.size();
    hb_buffer_add_utf8(buffer,text.c_str(),length,0,length);
    hb_buffer_guess_segment_properties(buffer);
    hb_shape(fontX , buffer , NULL , 0);
    unsigned int count;
    hb_glyph_info_t * glyph_info = hb_buffer_get_glyph_infos(buffer,&count);
    hb_glyph_position_t * glyph_position = hb_buffer_get_glyph_positions(buffer , &count);
    cout << "count is " << count << endl;
    cout << "glyph = " << glyph_info[1].codepoint << endl; // prints out 0 !

As you can see  glyph_info[1].codepoint  returns 0
Thank you

**Comment by manuel-rhdt** [comment]
You have to set font funcs on the font before shaping! The easiest would be to just call ‘hb_ot_font_set_funcs()‘ on your fontX. This makes harfbuzz use its internal opentype implementation (for getting glyph indices, advances and such) but you could also use font funcs provided by other libraries like freetype (see hb_ft_font_t).

**Comment by SamehMahmoud** [comment]
Unfortunately, I still getting the same result even after using hb_ot_font_set_funcs(). I can't use any argument from other libraries as I'm trying to use harfbuzz as standalone. Here is my code : 

`
    int array_size=1024*59;
    char * array = new char[array_size];
    int pos = 0;
    ifstream fin("/home/sameh/Desktop/K-Sina.ttf");
    if(fin.is_open()){
        cout << "File is opended" << endl;

        while(!fin.eof() && pos < array_size){
            fin.get(array[pos]);
            pos++;
        }

        array[pos-1]='\0';
        cout << "reading array " << endl;
        cout << array[5] << endl;
    

    hb_blob_t * blob;

    blob = hb_blob_create(array , sizeof(array) , HB_MEMORY_MODE_READONLY, NULL , NULL);

    hb_face_t * faceX;

    faceX = hb_face_create(blob , 0);

    hb_font_t * fontX = hb_font_create(faceX);

    hb_ot_font_set_funcs(fontX);

    hb_buffer_t * buffer;

    buffer = hb_buffer_create();

    string text = "السلام عليكم";

    size_t length = text.size();

    hb_buffer_add_utf8(buffer,text.c_str(),length,0,length);

    hb_buffer_guess_segment_properties(buffer);

    hb_shape(fontX , buffer , NULL , 0);

    unsigned int count;

    hb_glyph_info_t * glyph_info = hb_buffer_get_glyph_infos(buffer,&count);

    hb_glyph_position_t * glyph_position = hb_buffer_get_glyph_positions(buffer , &count);

    cout << "count is " << count << endl;

    cout << "glyph = " << glyph_info[1].codepoint << endl;
`
Thank you

**Comment by SamehMahmoud** [comment]
Any help ?

**Comment by khaledhosny** [comment]
> `blob = hb_blob_create(array , sizeof(array) , HB_MEMORY_MODE_READONLY, NULL , NULL);`

The second argument is the length of the data not the size of its type.

**Comment by SamehMahmoud** [comment]
Thank you very much Mr.Khaled is working now
