### ISSUE TITLE
hb_font_get_glyph_name returns null with blob

### ISSUE THREAD

**Issue by SamehMahmoud** [behdad/harfbuzz#370]
hello
I'm getting null/empty value from hb_font_get_glyph_name

here is my code

int array_size=1024*59;
    
char array array_size[array_size];
   
 int pos = 0;
   
 ifstream fin("/home/sameh/Desktop/K-Sina.ttf" , ios::binary);

    if(fin.is_open()){

        cout << "File is opended" << endl;

        fin.read(array, 1024*58);
    hb_blob_t * blob;

    blob = hb_blob_create(array , array_size , HB_MEMORY_MODE_READONLY, NULL , NULL);

    hb_face_t * faceX;

    faceX = hb_face_create(blob , 0);

    hb_font_t * fontX = hb_font_create(faceX);

    hb_ot_font_set_funcs(fontX);

    hb_buffer_t * buffer;

    buffer = hb_buffer_create();

    string text = "سامح";

    size_t length = text.size();

    hb_buffer_add_utf8(buffer,text.c_str(),length,0,length);

    hb_buffer_guess_segment_properties(buffer);

    hb_ot_font_set_funcs(fontX);

    hb_shape(fontX , buffer , NULL , 0);

    unsigned int count;

    hb_glyph_info_t * glyph_info = hb_buffer_get_glyph_infos(buffer,&count);

    hb_glyph_position_t * glyph_position = hb_buffer_get_glyph_positions(buffer , &count);

    cout << "count is " << count << endl;

    cout << "glyph = " << glyph_info[1].codepoint << endl;

    char * name = new char;

    hb_font_get_glyph_name(fontX , glyph_info[1].codepoint , name , 10);

    cout << "glyph=" << name << endl; // prints out "glyph=" !!

    fin.close();

}

**Comment by SamehMahmoud** [comment]
any help please

**Comment by khaledhosny** [comment]
> any help please

You need to be a bit more patient, it is been less than 30 minutes since you opened the issue!

The OT font functions don’t support glyph names yet. What do you need the glyph names for?

**Comment by khaledhosny** [comment]
You need to also work your C++ skills, your code is very badly written.

**Comment by SamehMahmoud** [comment]
We are working in java project and libgdx. my role in the team is to use harfbuzz through jni to reshape strings. They need a way to get unicode as they can't use glyph index to draw text. I know glyph names are very different than unicodes, but some font files containing the names like the following format : 
uni[UnicodeValue]

**Comment by khaledhosny** [comment]
> They need a way to get unicode as they can't use glyph index to draw text.

This won’t work. You really need to use glyph indices, there is no way around this. Not every glyph in the font is mapped to a character, so you need an API that can work with glyph indices.

**Comment by SamehMahmoud** [comment]
I'm c++ newbie so, my code is looking bad for sure :)

**Comment by SamehMahmoud** [comment]
I know the code is looking very bad, as I'm beginner. Please, tell me what exactly wrong with this code to fix it. Thanks
