### ISSUE TITLE
Trimmed characters in Arabic text

### ISSUE THREAD

**Issue by soroush** [behdad/harfbuzz#373]
I'm not sure if this is related to harfbuzz or not... There seems to be a bug in Qt 5.7.0 that I have reported it here:

https://bugreports.qt.io/browse/QTBUG-57453

Maybe [this](https://github.com/behdad/harfbuzz/blob/master/src/hb-ot-shape-complex-arabic.cc#L541) is related? I would be glad if you take a look.

Thanks

**Comment by khaledhosny** [comment]
This code is for `stch` feature which is used mostly in Syriac (see #141). That Qt bug does not seem like something related to HarfBuzz.

**Comment by soroush** [comment]
For future reference, the original bug was reported [here](https://bugreports.qt.io/browse/QTBUG-48005) and is in progress

Thanks
