### ISSUE TITLE
Make freezes at "CCLD libhb-ucdn.la" with mingw(i686)

### ISSUE THREAD

**Issue by ghost** [behdad/harfbuzz#379]
I'm not sure if it's a valid and logical, but in windows(win7_x64 with cygwin) after calling the autogen.sh, I call the configure as following
`$ ./configure --host=i686-w64-mingw32 --build=i686-w64-mingw32 --enable-static=yes --enable-shared=yes --with-glib=no --with-gobject=no --with-cairo=no --with-fontconfig=no --with-icu=no --with-graphite2=no --with-freetype=yes --with-uniscribe=no --with-directwrite=no --with-coretext=no CFLAG="-O3" CXXFLAG="-O3"`
(as the host specified for win32_x86)
The configure pass successfully
 then call the make, and the problems come here, it freezes forever like the following
```
$ make
make  all-recursive
make[1]: Entering directory '/cygdrive/h/clib/harfbuzz-master'
Making all in src
make[2]: Entering directory '/cygdrive/h/clib/harfbuzz-master/src'
make  all-recursive
make[3]: Entering directory '/cygdrive/h/clib/harfbuzz-master/src'
Making all in hb-ucdn
make[4]: Entering directory '/cygdrive/h/clib/harfbuzz-master/src/hb-ucdn'
  CCLD     libhb-ucdn.la
```
The process freezes at the "CCLD libhb-ucdn.la"
As I check the process, there are 4 make process belong to this, and 6 bash(sh) processes and one sed and all idle, sound like waiting for something!?

So what the problem would be? my problem?

Note[0]: but if I call the configure without host and build, it works very good and generates a cygwin based x64 build, it also works with 32bit cygwin (i686-pc-cygwin).
Note[1]: I believe there is no any issue with mingw(both x86_64 and i686) toolchain here as I could make freetype(and more stuffs) without any problem

Build platform:
Win7_x64
Cygwin (gcc 5.4 and mingw 5.4, both i686 and x86_64 versions)

Thanks.

**Comment by khaledhosny** [comment]
Try running make in verbose mode `make V=1` and see if it gives any clues.

**Comment by khaledhosny** [comment]
Looks likw the OP deleted his account, closing then.
