### ISSUE TITLE
Marchen text failed with 1.4.0

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [behdad/harfbuzz#386]
I have tested [BabelStone Marchen](http://www.babelstone.co.uk/Fonts/Marchen.html) with HarfBuzz version 1.4.0 as author’s guidence, but all the texts failed. HarfBuzz 1.3.4 does not have this problem.

**Comment by behdad** [comment]
Instead of filing multiple issues and leaving comments on unrelated bugs and threads, helps if you file one well-reported issue.  In particular, where's screenshots of the good and bad versions in this report?  Also, it's up to Mozilla people to decide which version of HarfBuzz to upgrade to.

**Comment by KrasnayaPloshchad** [comment]
I just feel surprised when I found this bug with the newest version, sorry. Here is what I have gotten:

1.4.0
![marchentest](https://cloud.githubusercontent.com/assets/10364351/21706007/a057bfec-d3fe-11e6-9bf9-6bd58f5780c4.png)

1.3.4
![marchentest](https://cloud.githubusercontent.com/assets/10364351/21706022/c4171b4e-d3fe-11e6-836f-bce103b2cd88.png)

**Comment by behdad** [comment]
And where's the sample text?

**Comment by behdad** [comment]
Ok, found them.
