### ISSUE TITLE
Problem with FT_Get_Var_Blend_Coordinates in /usr/lib/libharfbuzz.so.0

### ISSUE THREAD

**Issue by nyayaya** [behdad/harfbuzz#390]
Kinda new to this issue reporting thing, let me know if you want more info.

Just had to reinstall my system a few hours, tried to compile a couple programs and noticed they're all failing with a similar error referring to harfbuzz. 

Im running Arch with 4.8.13-1 kernel and harfbuzz from official repos, version 1.4.1-1.

The three programs I received errors in are retroarch, mpv and calibre . Heres some logs:

##mpv

[245/246] Compiling video/out/vo_tct.c
[246/246] Linking build/mpv
/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/../../../../lib/libharfbuzz.so: undefined reference to `FT_Get_Var_Blend_Coordinates'
collect2: error: ld returned 1 exit status

Waf: Leaving directory `/home/user/git/mpv-build/mpv/build'
Build failed

##retroarch

LD retroarch
/usr/lib/libharfbuzz.so.0: undefined reference to `FT_Get_Var_Blend_Coordinates'
collect2: error: ld returned 1 exit status
make: *** [Makefile:142: retroarch] Error 1

##calibre (for this one its runtime)

Traceback (most recent call last):
  File "/usr/bin/calibre", line 20, in <module>
    sys.exit(calibre())
  File "/usr/lib/calibre/calibre/gui_launch.py", line 69, in calibre
    from calibre.gui2.main import main
  File "/usr/lib/calibre/calibre/gui2/__init__.py", line 8, in <module>
    from PyQt5.QtWidgets import QStyle  # Gives a nicer error message than import from Qt
ImportError: /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates

**Comment by khaledhosny** [comment]
Looks like you are using unofficial FreeType package on Arch Linux that is lagging behind the official FreeType package that HarfBuzz package is built against. See https://bugs.archlinux.org/task/52421.

**Comment by khaledhosny** [comment]
See also https://gist.github.com/cryzed/e002e7057435f02cc7894b9e748c5671

**Comment by nyayaya** [comment]
Yep, you were right. I was using the infinality bundle. I installed the official freetype2 and everything compiled fine.
Thanks!
