### ISSUE TITLE
Build problem of HarfBuzz on AIX with its native compilers

### ISSUE THREAD

**Issue by sapi18n** [behdad/harfbuzz#393]
HarfBuzz cannot be built on AIX with its native compilers cc_r and xlC-r. A free sofware group called Bull provides patches for it.

http://www.bullfreeware.com/affichage.php?id=2900

I suggest HarfBuzz should migrate these patches into it. I have tested them successfully and these patches do not affect the original build using GNU. The modifications are in configure and check-header-quards.sh.

**Comment by khaledhosny** [comment]
They are patching the `configure` script directly, but any such changes should go to `configure.ac` and it is not clear from the patch what should be patched there (might be even an autotools issue).

**Comment by behdad** [comment]
Please report to autotools.
