### ISSUE TITLE
Build problem of HarfBuzz on HP with its native compilers

### ISSUE THREAD

**Issue by sapi18n** [behdad/harfbuzz#394]
HarfBuzz cannot be build on HP with its native compilers cc and aCC. There are two critical problems and one undesirable warning.

1. Errors #2028 and #2026
The error messages look like

    "hb-open-file-private.hh", line 261: error #2028: expression must have a constant value
        DEFINE_SIZE_UNION (4, tag);
        ^

It is caused by DEFINE_SIZE_UNION macro in src/hb-open-type-private.hh. It is

    #define DEFINE_SIZE_UNION(size, _member) \
      DEFINE_INSTANCE_ASSERTION (this->u._member.static_size == (size)); \
      static const unsigned int min_size = (size)

HP's cc and aCC do not allow 'this->u._member.static_size'. Since DEFINE_INSTANCE_ASSERTION is just for checking, it can be removed.

2. #error in src/hb-warning.cc
The error messages look like

    "hb-warning.cc", line 32: error #2035: #error directive: "Could not find any
              system to define atomic_int macros, library WILL NOT be thread-safe"
      #error "Could not find any system to define atomic_int macros, library WILL NOT be thread-safe"
       ^

There are four #error statement in src/hb-warning.cc. These lines must be #warning, not #error.

3. Compile option conflict
There are many warning like

      CXX      libharfbuzz_la-hb-buffer-serialize.lo
    aCC: warning 901: unknown option: `-hreads': use +help for online documentation.

The original option is '-mthreads' and it is added automatically if a compiler name is cc or acc. However HP has '-mt' option, and the compilers seem to treat 'hreads' as an addition to '-mt'.

Such warnings are harmless, but the autmatic addition of '-mthreads' is not good time to time.

**Comment by khaledhosny** [comment]
> There are four #error statement in src/hb-warning.cc. These lines must be #warning, not #error.

That is on purpose to avoid building thread-unsafe HarfBuzz unintentionally, check `hb-atomic-private.hh` and `hb-mutex-private.hh` for possible solutions as the errors say.

**Comment by behdad** [comment]
Please file one report per issue.  This one contains 3.
