### ISSUE TITLE
[emscripten] Loading multiple fonts and re-use them to shape.

### ISSUE THREAD

**Issue by mrapogee** [behdad/harfbuzz#397]
I'm trying to load multiple fonts into memory but it doesn't appear to be working. If I call load_font twice and use the FontPack for measure_text, the value returned from measure_text is different then If I call load_font once. I can't seem to find an example of this, do know what's going on?

```c++
#include <stdlib.h>
#include <stdio.h>

#include <hb.h>
#include <hb-ot.h>
#include "ucdn/ucdn.c"
#include "ucdn/ucdn.h"
// #include <emscripten.h>

hb_buffer_t *hb_buffer = hb_buffer_create();

struct FontPack {
  FontPack(hb_blob_t *blob) {
    face = hb_face_create(blob, 0);
    font = hb_font_create(face);
    hb_ot_font_set_funcs(font);
  }
  ~FontPack()
  {
      hb_face_destroy(face);
      hb_font_destroy(font);
  }
  hb_font_t *font;
  hb_face_t *face;
};

FontPack * makePack (hb_blob_t *blob) {
  FontPack *pack = new FontPack(blob);
  return pack;
}

int destroyPack (FontPack* pack) {
  delete pack;
  return 1;
}

hb_font_t* getFont (FontPack* pack) {
  return pack->font;
}

extern "C" {
/*
int main() 
{
  EM_ASM( allReady() );
  return 1;
}
*/
FontPack* load_font (int font_size, char* font_data) 
{
    printf ("Loading font file of size %d\n", font_size);
    hb_blob_t *font_blob;
    font_blob = hb_blob_create(font_data, font_size, HB_MEMORY_MODE_READONLY, NULL, NULL);
    FontPack *pack = makePack(font_blob);
    hb_blob_destroy(font_blob);

    return pack;
}

int unload_font (FontPack *pack)
{
  destroyPack(pack);
  return 1;
}

double measure_text (FontPack *pack, char *text)
{

    hb_font_t *font = getFont(pack);
    hb_buffer_reset(hb_buffer);
    hb_buffer_add_utf8 (hb_buffer, text, -1, 0, -1);
    hb_buffer_guess_segment_properties (hb_buffer);
    
    hb_shape (font, hb_buffer, NULL, 0);

    unsigned int glyph_count;
    hb_glyph_position_t *pos = hb_buffer_get_glyph_positions (hb_buffer, &glyph_count);

    double current_x = 0;
    //double current_y = 0;
    for (unsigned int i = 0; i < glyph_count; i++)
    {
        //double x_position = current_x + pos[i].x_offset;
        //double y_position = current_y + pos[i].y_offset;

        current_x += pos[i].x_advance;
        //current_y += pos[i].y_advance;
    }

    return current_x / 64.;
}

}
```

Other Issues: 

1. In certain fonts, some letters are randomly 100x wider

**Comment by behdad** [comment]
Does this not work in C++, or only when compiling to JS?  I don't have time to try right now, but it's supposed to work.

**Comment by mrapogee** [comment]
After some more testing, it appears to work when compiling normally but not when compiling to js. I'll close this and perhaps add some resolution once I have some time to debug and research what the problem is.

Thanks! Sorry, should have tried to compile to with gcc first.

**Comment by mrapogee** [comment]
The only thing that doesn't work on both is glyph names. They are always blank.

**Comment by behdad** [comment]
Ok, let's track this for figuring out fixes needed to compile harfbuzz with emscripten.  I know, for example, we cast functions of different types to eachother freely, and other things that are probably not safe for emscripten.

**Comment by mrapogee** [comment]
Sounds good.

**Comment by mrapogee** [comment]
I have some code in [mrapgoee/FontMetrics-js](https://github.com/mrapogee/FontMetrics-js)

**Comment by behdad** [comment]
> I have some code in mrapgoee/FontMetrics-js

Interesting!

**Comment by mrapogee** [comment]
I figured out the problem. I was freeing the source buffer via the emscripten Module._free(), I thought harfbuzz copied it into an index or something. It appears to be measuring correctly if I leave the buffer in memory.

We may want to create a different issue for verifying emscripten works correctly, since the focus of this issue is resolved.

**Comment by khaledhosny** [comment]
> The only thing that doesn't work on both is glyph names. They are always blank.

Indeed, the `ot` font function don’t currently support glyph names, but that shouldn’t be an issue in practice.
