### ISSUE TITLE
Build problem of HarfBuzz on HP with its native compilers, DEFINE_SIZE_UNION

### ISSUE THREAD

**Issue by sapi18n** [behdad/harfbuzz#398]
HarfBuzz cannot be build on HP with its native compilers cc and aCC. 

Error messages look like

    "hb-open-file-private.hh", line 261: error #2028: expression must have a constant value
     DEFINE_SIZE_UNION (4, tag);
     ^

It is caused by DEFINE_SIZE_UNION macro in src/hb-open-type-private.hh. It is

    #define DEFINE_SIZE_UNION(size, _member) \
      DEFINE_INSTANCE_ASSERTION (this->u._member.static_size == (size)); \
      static const unsigned int min_size = (size)

HP's cc and aCC do not allow 'this->u._member.static_size'. Since DEFINE_INSTANCE_ASSERTION is just for checking, it can be removed.

**Comment by behdad** [comment]
We already rewrote that code; should work in latest release I think.

**Comment by sapi18n** [comment]
I just confirmed that the issue did not exist in 1.4.2.
