### ISSUE TITLE
Build problem of HarfBuzz on HP with its native compilers, #error in src/hb-warning.cc

### ISSUE THREAD

**Issue by sapi18n** [behdad/harfbuzz#399]
HarfBuzz cannot be build on HP with its native compilers cc and aCC.

Error messages look like

    "hb-warning.cc", line 32: error #2035: #error directive: "Could not find any
     system to define atomic_int macros, library WILL NOT be thread-safe"
     #error "Could not find any system to define atomic_int macros, library WILL NOT be thread-safe"
     ^

There are four #error statement in src/hb-warning.cc. These lines must be #warning, not #error.

OR the compile option to force a multi-thread compilation must be examined for HP compilers. Currently "-mthread" seems to be passed, but I think "-mt" is the right one for HP. (I amd not an HP compiler expert but Google says it.)

**Comment by behdad** [comment]
> There are four #error statement in src/hb-warning.cc. These lines must be #warning, not #error.

No. It's an error to build HarfBuzz in an unthreadsafe manner.  If you really want that, you can define HB_NO_MT.

As for the "-mthread" issue, that sounds like a problem with the threading discovery macro `AX_PTHREAD`. I just updated that macro to latest version upstream. Not sure if it makes any difference.

**Comment by sapi18n** [comment]
I just tried the latest master + 1.4.2 but the issue still existed. Please find a way to set a proper compiling option. HP needs '-mt' and doesn't need '-mthread'.

**Comment by behdad** [comment]
You need to debug `ax_pthread.m4` / configure to see why it's not choosing -mt.  Or report the bug to `ax_pthread.m4` maintainers:
https://www.gnu.org/software/autoconf-archive/ax_pthread.html

We don't decide what to pass to the compiler.
