### ISSUE TITLE
API required for hb_font_set_var_coords_design or similar [fvar/avar support]

### ISSUE THREAD

**Issue by drott** [behdad/harfbuzz#404]
In order to be able to link Skia variation axis parameters to HarfBuzz the discussion in [Skia bug 5916](https://bugs.chromium.org/p/skia/issues/detail?id=5916) concluded with having an API to specify axis parameters in design coordinates, rather than in normalized values.

**Comment by behdad** [comment]
Working on it.

**Comment by behdad** [comment]
In https://github.com/behdad/harfbuzz/releases/tag/1.4.2
