### ISSUE TITLE
Unchecked return values from get_nominal_glyph()

### ISSUE THREAD

**Issue by pwithnall** [behdad/harfbuzz#411]
I’ve been running Coverity on Harfbuzz, and it’s flagged up a couple of places where the return value of `get_nominal_glyph()` is not checked, even though it’s checked everywhere else. I don’t know enough about the handling of codepoint 0 to know whether this is OK:
 * `_hb_fallback_shape()` in `hb-fallback-shape.cc` (Coverity ID: 141031)
 * `set_glyph()` in `hb-ot-shape-normalize.cc` (Coverity ID: 124694)

If it’s OK to ignore the return values here, I can mark the Coverity reports as to be ignored. Otherwise, I guess some code changes are needed to propagate the error handling.

**Comment by behdad** [comment]
Thanks.  Those are intentional.  Added casts that should silence these.
