### ISSUE TITLE
Hangul Conjoining Jamo Sequences are NOT shaped into syllable blocks in the vertical mode

### ISSUE THREAD

**Issue by jungshik** [behdad/harfbuzz#414]
Tested with three fonts;  Noto Sans CJK 1.004, Nanum BarunGothic YetHangul, and Nanum Myeongjo YetHangul [1]

This text file is passed to hb-view/hb-shape with ```--direction=ttb``` to generate the output files below:

[u1113.txt](https://github.com/behdad/harfbuzz/files/762350/u1113.txt)

It has 4 Old Koerean syllables: <U+1113, U+1167>, <U+1113, U+1167, U+11A8>, <U+1113, U+1167, U+11A9> and <U+1113, U+1167, U+11AA> separated by U+0020. The first one L (leading consonant) and V (vowel) and the rest three have L + V + T (trailing consonants). 

Noto Sans CJK
![u1113_ttb_notosans_tot](https://cloud.githubusercontent.com/assets/8578343/22764896/4049c38c-ee22-11e6-9280-cfb44dee750d.png)

The output of hb-shape: 
```
[gid64051=0@-460,-894+0,-1000|gid64509=0@0,-894+0,-1000|gid1=2@-112,-880+0,-1000|
gid63676=3@-460,-894+0,-1000|gid64414=3@0,-894+0,-1000|gid64734=3@0,-894+0,-1000|
gid1=6@-112,-880+0,-1000|gid63676=7@-460,-894+0,-1000|gid64414=7@0,-894+0,-1000|
gid64735=7@0,-894+0,-1000|gid1=10@-112,-880+0,-1000|gid63676=11@-460,-894+0,-1000|
gid64414=11@0,-894+0,-1000|gid64736=11@0,-894+0,-1000|gid1=14@-112,-880+0,-1000]
```

Nanum BarunGothic YetHangul 
![u1113_ttb_nanumbarungothic_tot](https://cloud.githubusercontent.com/assets/8578343/22764949/8bb86422-ee22-11e6-981c-15e0d54fad04.png)

Nanum Myeongjo YetHangul
![u1113_ttb_nanummyeongjo_tot](https://cloud.githubusercontent.com/assets/8578343/22764964/9962e124-ee22-11e6-8a72-1e46b7e8f434.png)

[u1113_ttb_nanummyeongjo_tot.shape.txt](https://github.com/behdad/harfbuzz/files/762358/u1113_ttb_nanummyeongjo_tot.shape.txt)

Nanum {BarunGothic,Myeongjo} YetHangul have a pre-composed glyph for <U+1113, U+1167> (the first syllable in the screenshot), which is why the sequence is shaped correctly in the vertical mode while other three sequences are not.  

[1]  Nanum fonts can be downloaded from here: http://appdown.naver.com/naver/font/NanumFont/setupmac/NanumBarunGothicYetHangul_OTF_hangeulcamp.dmg
http://appdown.naver.com/naver/font/NanumFont/setupmac/NanumMyeongjoYetHangul_OTF_hangeulcamp.dmg
Unfortunately, they don't have a zip/tar ball so that dmg for Mac has to be downloaded to extract font files.

**Comment by jungshik** [comment]
What's expected (except that the orientation should be vertical instead of horizontal) 

* Noto Sans CJK
![u1113_ltr_notosans_tot](https://cloud.githubusercontent.com/assets/8578343/22765139/8c2a8e02-ee23-11e6-81f4-339c3b11f795.png)

The output from hb-shape for horizontal layout: 
```
[gid64051=0+920|gid64509=0+0|gid1=2+224|gid63676=3+920|gid64414=3+0|gid64734=3+0|
gid1=6+224|gid63676=7+920|gid64414=7+0|gid64735=7+0|gid1=10+224|gid63676=11+920|
gid64414=11+0|gid64736=11+0|gid1=14+224][]
```

**Comment by jungshik** [comment]
This is spun off from googlei18n/noto-cjk#79.

**Comment by jungshik** [comment]
It looks like a bug in the font. Let's close this for now.

**Comment by behdad** [comment]
HarfBuzz doesn't implement per-glyph vertical origin in hb-ot-font, and FreeType doesn't implement VORG table.  Both need to be addressed for this to work properly.

**Comment by jungshik** [comment]
The font in question does not have VORG table and harfbuzz seems to calculate the vertical origin correctly (from CFF and tsb in vmtx table).  

With @kenlunde 's change in https://github.com/googlei18n/noto-cjk/issues/79#issuecomment-278643399,  the vertical positions are all correct in hb-shape and Chrome. hb-view output is off, though. 

See https://github.com/googlei18n/noto-cjk/issues/79#issuecomment-278768486 and comments following that.

**Comment by behdad** [comment]
Ok, closing again; we have tracking bugs for VORG etc elsewhere.

**Comment by KrasnayaPloshchad** [comment]
Is there anyway to resolve it?

**Comment by kenlunde** [comment]
@KrasnayaPloshchad: It looks like we found a solution, which involves 'vmtx' table overrides and a 'vert' GPOS (not GSUB) feature for adjusting the zero-width V ('vjmo') and T ('tjmo') glyphs. Look at the end of [Noto CJK Issue #79](https://github.com/googlei18n/noto-cjk/issues/79) for the details and a test font.

**Comment by KrasnayaPloshchad** [comment]
Still affect LibreOffice 6.0.2.
