### ISSUE TITLE
MSVC compile issue with new hb_fallback_shaper changes

### ISSUE THREAD

**Issue by johne53** [behdad/harfbuzz#423]
I just reported this on the mailing list before realising there's a bug list here, so sorry for the duplication...

This morning (18th Feb 2017) I updated Harfbuzz from git master and tried to build with MSVC.  When compiling 'src/hb-fallback-shape.cc' it now gives me a lot of errors, starting with this at line 31:-

      error C2039: 'fallback' : is not a member of 'hb_shaper_data_t'

And there are other errors relating to '_hb_fallback_shaper_face_data_create' / '_hb_fallback_shaper_face_data_destroy' / '_hb_fallback_shaper_font_data_create' and '_hb_fallback_shaper_font_data_destroy' (all of them report "Identifier not found").  These ones seem to be due to the new HB_SHAPER_DATA_ENSURE_DEFINE macros getting defined too early (if I move them so that they come after the relevant functions, those particular errors disappear).  However, the same macro always gives me the errors which tell me that "fallback is not a member of 'hb_shaper_data_t". I can't seem to get rid of that one. :-(

Everything else still compiles okay AFAICT.

**Comment by behdad** [comment]
How do you try to build?  Try defining HAVE_FALLBACK

**Comment by johne53** [comment]
Thanks Behdad - that fixed it.

For some reason, it looks like I currently build without #defining HAVE_CONFIG_H.  I'll need to investigate why...  I'm not building with make so my guess is that I didn't know how to obtain the values for PACKAGE_VERSION / PACKAGE_BUGREPORT etc.
