### ISSUE TITLE
autotools warnings

### ISSUE THREAD

**Issue by eroux** [behdad/harfbuzz#424]
when running `autoreconf -fi` (or `autogen.sh`) with `autoreconf (GNU Autoconf) 2.69` I get several

```
configure.ac:22: warning: AC_RUN_IFELSE was called before AC_USE_SYSTEM_EXTENSIONS
../../lib/autoconf/specific.m4:368: AC_USE_SYSTEM_EXTENSIONS is expanded from...
configure.ac:22: the top level
```

working on a PR

**Comment by behdad** [comment]
Ignore it.  I fixed that before. Broke automake on my version of Ubuntu.  Will eventually fix it when we don't have to support Ubuntu 14.04

**Comment by eroux** [comment]
oh ok thanks!

**Comment by behdad** [comment]
Closing since not actionable currently, and works.
