### ISSUE TITLE
OpenType 'rand' (Randomize) feature not correctly implemented

### ISSUE THREAD

**Issue by linusromer** [behdad/harfbuzz#427]
XeLaTeX 3.14159265-2.6-0.99996 (which uses HarfBuzz 1.0.1) does not use the OpenType 'rand' (Randomize) feature correctly. It seems like the 'rand' feature has not been correctly implemented in HarfBuzz. Obviously, HarfBuzz chooses a fixed variant for each glyph instead of picking the variants randomly.

See also this [tex-stackexchange question](http://tex.stackexchange.com/questions/355007/opentype-rand-randomize-feature-not-correct-implemented-in-xetex).

**Comment by khaledhosny** [comment]
The `rand` feature is not currently supported in any special way, it will be treated as a regular feature and the first variant will always be picked since the document is not asking for any others. See this [mailing list discussion](https://lists.freedesktop.org/archives/harfbuzz/2011-June/001308.html) on why it is not simple to support.

**Comment by linusromer** [comment]
The second restriction of this [mailing list discussion](https://lists.freedesktop.org/archives/harfbuzz/2011-June/001308.html) implies that every word has to use the same seed. While I do not see the need of this restriction, I completely understand that it makes the support of the Randomize feature senseless.
Shall I close this issue, because it is not solvable by concept?

**Comment by behdad** [comment]
I don't think we'll get to implement this any time soon, to say the least.

**Comment by KrasnayaPloshchad** [comment]
>bI don't think we'll get to implement this any time soon, to say the least.

Does HarfBuzz allowing this feature working as 'salt' feature? If so, there is not necessary to consider for this, any client would get implementation to present any variant casually.

**Comment by KrasnayaPloshchad** [comment]
OK, you'll get solution if #673 is fixed.

**Comment by linusromer** [comment]
@KrasnayaPloshchad Good to know, thank you!

**Comment by KrasnayaPloshchad** [comment]
Yeah, pull requests are welcome.

**Comment by KrasnayaPloshchad** [comment]
Now I suggest focusing on #803 for this.
