### ISSUE TITLE
incorrect rendering with harfbuzz and noto serif

### ISSUE THREAD

**Issue by MayuraVerma** [behdad/harfbuzz#439]
ಜಾ಼ಕಿರ್

correct rendering with coretext and noto sans.
and also harfbuzz and noto sans
![screen shot 2017-03-07 at 6 49 20 am](https://cloud.githubusercontent.com/assets/14062593/23657122/3bf40e9c-0302-11e7-952e-39131953a3be.png)

incorrect rendering with harfbuzz and noto serif.
![screen shot 2017-03-07 at 6 49 48 am](https://cloud.githubusercontent.com/assets/14062593/23657276/e637f760-0302-11e7-859d-875df59b7e55.png)

**Comment by behdad** [comment]
Ok, we checked the font.  It doesn't have correct GDEF to allow nukta to attach to base consonant.  Both Uniscribe and HarfBuzz fail to position the nukta.  It's essentially a font, and CoreText indic shaper bug.  cc @nedley
