### ISSUE TITLE
Consider detecting invalid GSUB lookup targets

### ISSUE THREAD

**Issue by drott** [behdad/harfbuzz#440]
Spun off from [chromium issue 611970](https://bugs.chromium.org/p/chromium/issues/detail?id=611970#c29).

Shaping with incorrectly subsetted fonts that have GSUB lookups pointing to glyf table entries without contours, or not-present glyf table entries leads to missing glyphs in the shape result which could be avoided if the GSUB table was flagged as broken and further lookups would be dropped.

Font [Calibri_Bold_broken_subset.otf](https://bugs.chromium.org/p/chromium/issues/attachment?aid=274510) is [available from the Chromium bugtracker.](https://bugs.chromium.org/p/chromium/issues/attachment?aid=274510)

Example hb-view call:
`$ hb-view Calibri-Bold.otf "fifiti"`
empty output
whereas:
`$ hb-view --features=-liga Calibri-Bold.otf "fifiti" `
produces the correctly rendered string.

**Comment by behdad** [comment]
Garbage in, garbage out. :)

**Comment by behdad** [comment]
FWIW it's impossible to detect such tables, as GSUB substitutions are Turing-complete.

**Comment by khaledhosny** [comment]
Yep, and the idea that one can extract fonts from PDF files and expect them to work anywhere else is rather naive IMHO, since PDF producers do all kinds of horrible things when subsetting fonts and they get way with it since basically on the glyph tables are used by PDF viewers.

**Comment by behdad** [comment]
> the idea that one can extract fonts from PDF files and expect them to work anywhere else is rather naive IMHO

Right. I was going to write that on https://github.com/coolwanglu/pdf2htmlEX/issues/710

Basically fonts in PDF don't have to have cmap table even... You *cannot* shape text with them.

**Comment by drott** [comment]
I agree that the expectation for PDF subsetted fonts to work reliably elsewhere as a full font is generally invalid. But "garbage in, garbage out" might be a bit broad here and we can do better for our users. 

@behdad, could you elaborate on why it's impossible to detect a broken GSUB in this case? Perhaps with a GSUB table in isolation it may not be possible, or if the approach is to do some sort of formal analysis of the GSUB "programs". But shaping a sample word, performing the GSUB lookups for a shaped word like "fill" to identify the destination glyph 'ligature_fi' which then cannot be found from the `glyf` table, I don't see why this couldn't be detected as an invalid GSUB lookup result and GSUB for this `hb_font_t` could be flagged as broken and perhaps retried without doing any further GSUB lookups? Also, you mentioned that FF seems to manage detecting this situation by using OTS (unconfirmed, but FF does display f and i glyphs instead of a missing fi ligatures on the page in question, so it does something to address this problem.)

**Comment by khaledhosny** [comment]
OTS actually does not reject the GSUB table. The reason that the test case works with Firefox is before the page uses prefixed `-moz-font-feature-settings:"liga" 0` and does not use the unprefixed or the `-webkit` prefix.

**Comment by khaledhosny** [comment]
I agree with Behdad that it is not easy to reject such broken tables; the fact that a GSUB lookup uses glyph ids not present in the font does not mean it is broken since another lookup might use these as input. So the only way is to check the final glyphs, which I think is better done by the client (if needed to be done at all); after shaping check if the buffer has any invalid glyphs and if so drop it and reshape again without GSUB table (this under the assumption that a broken, say, cmap will be caught by OTS so leaving leaving only GSUB ad possible candidate).

But then it is easier to say WAI and let the user fix the broken fonts :)
