### ISSUE TITLE
cluster values in Arabic are jumping

### ISSUE THREAD

**Issue by typoman** [behdad/harfbuzz#454]
Hi All,

By using the sample.py I tried to run a test on a font and I realized for utf-8 string the cluster values add up twice for Arabic letters but I can't make sense of that because the letters are being substituted not ligated or decomposed. For example if I run the shaper on "سسس" then the cluster values will be 0, 2, 4. Can someone explain how can I find a proper mapping from unicode string to glyphs in this situation? 

Thanks

**Comment by khaledhosny** [comment]
These are indices to the input array, so if your input is UTF-8 they will be byte indices and Arabic characters are 2 bytes in UTF-8.

**Comment by behdad** [comment]
You sure your sample.py is not ancient?  We fixed this a long time ago.  See:

https://github.com/behdad/harfbuzz/blob/master/src/sample.py#L44

**Comment by typoman** [comment]
Thank you very much and sorry for inconvenience!
