### ISSUE TITLE
Build failure in GNOME Continuous

### ISSUE THREAD

**Issue by ebassi** [behdad/harfbuzz#455]
Harfbuzz is failing to build on the GNOME continuous integration/delivery build server after commit 7d64c0ef37dd930e9807bd80d398491aa9c4428c.

Selected log fragment:

```
make[2]: Entering directory '/ostbuild/source/harfbuzz/_build/src'
make[2]: *** No rule to make target 'hb-buffer-deserialize-json.hh', needed by 'all'.  Stop.
make[2]: Leaving directory '/ostbuild/source/harfbuzz/_build/src'
```

Full build log is available [here](http://build.gnome.org/continuous/buildmaster/builds/2017/04/05/28/build/log-harfbuzz.txt).

I've tagged Harfbuzz to commit 7d64c0ef37dd930e9807bd80d398491aa9c4428c for the time being.

**Comment by behdad** [comment]
I'm sorry it took long to fix it, but it should be fixed.  Can you try again?  Thanks.

**Comment by ebassi** [comment]
Yep, I can confirm that Continuous successfully built Harfbuzz after #467 was merged. [Build log](http://build.gnome.org/continuous/buildmaster/builds/2017/04/18/16/build/log-harfbuzz.txt) for reference.

Thanks!
