### ISSUE TITLE
Remove cast of functions to (hb_destroy_func_t)

### ISSUE THREAD

**Issue by behdad** [behdad/harfbuzz#474]
It's undefined to call functions with a different signature.  So we need to add wrappers that match hb_destroy_func_t signature and call those.

Originally reported and discussed here:
https://bugs.chromium.org/p/chromium/issues/detail?id=696729

**Comment by drott** [comment]
Thank you for fixing these.

**Comment by drott** [comment]
There are two more instances with likely the same root cause in [758478](https://bugs.chromium.org/p/chromium/issues/detail?id=758478) and [761245](https://bugs.chromium.org/p/chromium/issues/detail?id=761245), would be great if we could have a fix soon. Thanks very much.
