### ISSUE TITLE
fail to build with msys2 on win7_64

### ISSUE THREAD

**Issue by 9064911** [behdad/harfbuzz#476]
I'm trying to make static lib for harfbuzz with only freetype.

I tried with cygwin_mingw and msys2 too, both fail, vary issues. Never had issues with other projects like freetype, linpng, etc.

First how to ask not build the exe files (hb-shape.exe and hb-view.exe)?

**Attempt 0**
with msys2_mingw_i686:
`./configure --enable-fast-install=no --enable-static=yes --enable-shared=no --with-glib=no --with-gobject=no --with-cairo=no --with-fontconfig=no --with-icu=no --with-graphite2=no --with-freetype=yes --with-uniscribe=no --with-directwrite=no --with-coretext=no --host=i686-w64-mingw32 --build=i686-w64-mingw32`  <<--->> Result : OK

Now the make call:
```
$ make
make  all-recursive
make[1]: Entering directory '/h/__gits/harfbuzz'
Making all in src
make[2]: Entering directory '/h/__gits/harfbuzz/src'
make  all-recursive
make[3]: Entering directory '/h/__gits/harfbuzz/src'
Making all in hb-ucdn
make[4]: Entering directory '/h/__gits/harfbuzz/src/hb-ucdn'
make[4]: Leaving directory '/h/__gits/harfbuzz/src/hb-ucdn'
make[4]: Entering directory '/h/__gits/harfbuzz/src'
  CXX      libharfbuzz_la-hb-blob.lo
In file included from /usr/include/errno.h:9:0,
                 from hb-private.hh:53,
                 from hb-blob.cc:32:
/usr/include/sys/errno.h:14:0: warning: "errno" redefined
 #define errno (*__errno())

In file included from /opt/lib/gcc/i686-w64-mingw32/6.3.0/include/stddef.h:1:0,
                 from /usr/include/stdlib.h:16,
                 from hb-private.hh:43,
                 from hb-blob.cc:32:
/opt/i686-w64-mingw32/include/stddef.h:19:0: note: this is the location of the previous definition
 #define errno (*_errno())

In file included from /opt/i686-w64-mingw32/include/windows.h:114:0,
                 from hb-atomic-private.hh:51,
                 from hb-object-private.hh:37,
                 from hb-blob.cc:34:
/opt/i686-w64-mingw32/include/stralign.h: In function ‘WCHAR* ua_wcscpy(PUWSTR, PCUWSTR)’:
/opt/i686-w64-mingw32/include/stralign.h:37:102: error: ‘wcscpy’ was not declared in this scope
   __CRT_INLINE PUWSTR ua_wcscpy(PUWSTR Destination,PCUWSTR Source) { return wcscpy(Destination,Source); }
                                                                                                      ^
Makefile:1943: recipe for target 'libharfbuzz_la-hb-blob.lo' failed
make[4]: *** [libharfbuzz_la-hb-blob.lo] Error 1
make[4]: Leaving directory '/h/__gits/harfbuzz/src'
Makefile:2431: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/h/__gits/harfbuzz/src'
Makefile:1324: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/h/__gits/harfbuzz/src'
Makefile:484: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/h/__gits/harfbuzz'
Makefile:416: recipe for target 'all' failed
make: *** [all] Error 2
```
**Attempt 1**
with msys2_mingw_x86_64:
`./configure --enable-fast-install=no --enable-static=yes --enable-shared=no --with-glib=no --with-gobject=no --with-cairo=no --with-fontconfig=no --with-icu=no --with-graphite2=no --with-freetype=yes --with-uniscribe=no --with-directwrite=no --with-coretext=no --host=x86_64-w64-mingw32 --build=x86_64-w64-mingw32` <<--->> Result : OK

Now the make call:
```
$ make
make  all-recursive
make[1]: Entering directory '/h/__gits/harfbuzz'
Making all in src
make[2]: Entering directory '/h/__gits/harfbuzz/src'
make  all-recursive
make[3]: Entering directory '/h/__gits/harfbuzz/src'
Making all in hb-ucdn
make[4]: Entering directory '/h/__gits/harfbuzz/src/hb-ucdn'
  CC       libhb_ucdn_la-ucdn.lo
  CCLD     libhb-ucdn.la
make[4]: Leaving directory '/h/__gits/harfbuzz/src/hb-ucdn'
make[4]: Entering directory '/h/__gits/harfbuzz/src'
  CXX      libharfbuzz_la-hb-blob.lo
In file included from /usr/include/errno.h:9:0,
                 from hb-private.hh:53,
                 from hb-blob.cc:32:
/usr/include/sys/errno.h:14:0: warning: "errno" redefined
 #define errno (*__errno())

In file included from /opt/lib/gcc/x86_64-w64-mingw32/6.3.0/include/stddef.h:1:0,
                 from /usr/include/stdlib.h:16,
                 from hb-private.hh:43,
                 from hb-blob.cc:32:
/opt/x86_64-w64-mingw32/include/stddef.h:19:0: note: this is the location of the previous definition
 #define errno (*_errno())

In file included from /usr/include/sys/select.h:26:0,
                 from /usr/include/sys/types.h:68,
                 from /usr/include/stdio.h:61,
                 from hb-private.hh:52,
                 from hb-blob.cc:32:
/usr/include/sys/_timeval.h:40:18: error: conflicting declaration ‘typedef long int time_t’
 typedef _TIME_T_ time_t;
                  ^~~~~~
In file included from /opt/x86_64-w64-mingw32/include/stddef.h:7:0,
                 from /opt/lib/gcc/x86_64-w64-mingw32/6.3.0/include/stddef.h:1,
                 from /usr/include/stdlib.h:16,
                 from hb-private.hh:43,
                 from hb-blob.cc:32:
/opt/x86_64-w64-mingw32/include/crtdefs.h:138:20: note: previous declaration as ‘typedef __time64_t time_t’
 typedef __time64_t time_t;
                    ^~~~~~
In file included from /opt/x86_64-w64-mingw32/include/windows.h:114:0,
                 from hb-atomic-private.hh:51,
                 from hb-object-private.hh:37,
                 from hb-blob.cc:34:
/opt/x86_64-w64-mingw32/include/stralign.h: In function ‘int ua_wcsicmp(LPCUWSTR, LPCUWSTR)’:
/opt/x86_64-w64-mingw32/include/stralign.h:155:56: error: ‘_wcsicmp’ was not declared in this scope
       return _wcsicmp((LPCWSTR)String1,(LPCWSTR)String2);
                                                        ^
Makefile:1943: recipe for target 'libharfbuzz_la-hb-blob.lo' failed
make[4]: *** [libharfbuzz_la-hb-blob.lo] Error 1
make[4]: Leaving directory '/h/__gits/harfbuzz/src'
Makefile:2431: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/h/__gits/harfbuzz/src'
Makefile:1324: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/h/__gits/harfbuzz/src'
Makefile:484: recipe for target 'all-recursive' failed
make[1]: Leaving directory '/h/__gits/harfbuzz'
make[1]: *** [all-recursive] Error 1
Makefile:416: recipe for target 'all' failed
make: *** [all] Error 2
```

**Attempt 2**
with cygwin mingw_i686
`./configure --enable-fast-install=no --enable-static=yes --enable-shared=no --with-glib=no --with-gobject=no --with-cairo=no --with-fontconfig=no --with-icu=no --with-graphite2=no --with-freetype=yes --with-uniscribe=no --with-directwrite=no --with-coretext=no --host=i686-w64-mingw32 --build=i686-w64-mingw32`  <<--->> Result : OK

calling the make:
```
$ make "V=1"
make  all-recursive
make[1]: Entering directory '/cygdrive/h/__gits/harfbuzz'
Making all in src
make[2]: Entering directory '/cygdrive/h/__gits/harfbuzz/src'
make  all-recursive
make[3]: Entering directory '/cygdrive/h/__gits/harfbuzz/src'
Making all in hb-ucdn
make[4]: Entering directory '/cygdrive/h/__gits/harfbuzz/src/hb-ucdn'
/bin/sh ../../libtool  --tag=CC   --mode=compile i686-w64-mingw32-gcc -DHAVE_CONFIG_H -I. -I../..  -I../.. -I../../src -I../../src   -g -O2 -MT libhb_ucdn_la-ucdn.lo -MD -MP -MF .deps/libhb_ucdn_la-ucdn.Tpo -c -o libhb_ucdn_la-ucdn.lo `test -f 'ucdn.c' || echo './'`ucdn.c
libtool: compile:  i686-w64-mingw32-gcc -DHAVE_CONFIG_H -I. -I../.. -I../.. -I../../src -I../../src -g -O2 -MT libhb_ucdn_la-ucdn.lo -MD -MP -MF .deps/libhb_ucdn_la-ucdn.Tpo -c ucdn.c -o libhb_ucdn_la-ucdn.o
mv -f .deps/libhb_ucdn_la-ucdn.Tpo .deps/libhb_ucdn_la-ucdn.Plo
/bin/sh ../../libtool  --tag=CC   --mode=link i686-w64-mingw32-gcc  -g -O2  -Bsymbolic-functions -o libhb-ucdn.la  libhb_ucdn_la-ucdn.lo
```
It freeze forever,  I just can terminate it, no sign of progress, it's freezed really.

 **Attempt 3**
with cygwin mingw_x86_64
`./configure --enable-fast-install=no --enable-static=yes --enable-shared=no --with-glib=no --with-gobject=no --with-cairo=no --with-fontconfig=no --with-icu=no --with-graphite2=no --with-freetype=yes --with-uniscribe=no --with-directwrite=no --with-coretext=no --host=x86_64-w64-mingw32 --build=x86_64-w64-mingw32` <<--->> Result : OK

now calling the make
```
$ make "V=1"
make  all-recursive
make[1]: Entering directory '/cygdrive/h/__gits/harfbuzz'
Making all in src
make[2]: Entering directory '/cygdrive/h/__gits/harfbuzz/src'
make  all-recursive
make[3]: Entering directory '/cygdrive/h/__gits/harfbuzz/src'
Making all in hb-ucdn
make[4]: Entering directory '/cygdrive/h/__gits/harfbuzz/src/hb-ucdn'
/bin/sh ../../libtool  --tag=CC   --mode=compile x86_64-w64-mingw32-gcc -DHAVE_CONFIG_H -I. -I../..  -I../.. -I../../src -I../../src   -g -O2 -MT libhb_ucdn_la-ucdn.lo -MD -MP -MF .deps/libhb_ucdn_la-ucdn.Tpo -c -o libhb_ucdn_la-ucdn.lo `test -f 'ucdn.c' || echo './'`ucdn.c
libtool: compile:  x86_64-w64-mingw32-gcc -DHAVE_CONFIG_H -I. -I../.. -I../.. -I../../src -I../../src -g -O2 -MT libhb_ucdn_la-ucdn.lo -MD -MP -MF .deps/libhb_ucdn_la-ucdn.Tpo -c ucdn.c -o libhb_ucdn_la-ucdn.o
mv -f .deps/libhb_ucdn_la-ucdn.Tpo .deps/libhb_ucdn_la-ucdn.Plo
/bin/sh ../../libtool  --tag=CC   --mode=link x86_64-w64-mingw32-gcc  -g -O2  -Bsymbolic-functions -o libhb-ucdn.la  libhb_ucdn_la-ucdn.lo
```
Same for the i686, it hangs forever.

----------------------------

All fail! I just need the static lib with freetype dependency. I know it looks really weird and could be my problem, so please help to make it fix. I only have problem with harfbuzz, could build the freetype, zlib, pnglib, ... with cygwin mingw without any issue, all pass success.

Is there any online service to ask build the repository and grab the builds? Sorry I'm new with git.

**Comment by behdad** [comment]
> I'm trying to make static lib for harfbuzz with only freetype.
> 
> I tried with cygwin_mingw and msys2 too, both fail, vary issues. Never had issues with other projects like freetype, linpng, etc.
> 
> First how to ask not build the exe files (hb-shape.exe and hb-view.exe)?

Why do you care? Don't use them.

> Attempt 0
> with msys2_mingw_i686:
> ./configure --enable-fast-install=no --enable-static=yes --enable-shared=no --with-glib=no --with-gobject=no --with-cairo=no --with-fontconfig=no --with-icu=no --with-graphite2=no --with-freetype=yes --with-uniscribe=no --with-directwrite=no --with-coretext=no --host=i686-w64-mingw32 --build=i686-w64-mingw32 <<--->> Result : OK

I've never used such an environment.  I use mingw from Linux though.

> Now the make call:
> 
> $ make
> make  all-recursive
> make[1]: Entering directory '/h/__gits/harfbuzz'
> Making all in src
> make[2]: Entering directory '/h/__gits/harfbuzz/src'
> make  all-recursive
> make[3]: Entering directory '/h/__gits/harfbuzz/src'
> Making all in hb-ucdn
> make[4]: Entering directory '/h/__gits/harfbuzz/src/hb-ucdn'
> make[4]: Leaving directory '/h/__gits/harfbuzz/src/hb-ucdn'
> make[4]: Entering directory '/h/__gits/harfbuzz/src'
>   CXX      libharfbuzz_la-hb-blob.lo
> In file included from /usr/include/errno.h:9:0,
>                  from hb-private.hh:53,
>                  from hb-blob.cc:32:
> /usr/include/sys/errno.h:14:0: warning: "errno" redefined
>  #define errno (*__errno())
> 
> In file included from /opt/lib/gcc/i686-w64-mingw32/6.3.0/include/stddef.h:1:0,
>                  from /usr/include/stdlib.h:16,
>                  from hb-private.hh:43,
>                  from hb-blob.cc:32:
> /opt/i686-w64-mingw32/include/stddef.h:19:0: note: this is the location of the previous definition
>  #define errno (*_errno())

So, headers both from your mingw system as well as your /usr/... posix system (what is that?) are being mixed.  That's recipe for failure.  Not our fault.  Something wrong with your toolchain setup.

> In file included from /opt/i686-w64-mingw32/include/windows.h:114:0,
>                  from hb-atomic-private.hh:51,
>                  from hb-object-private.hh:37,
>                  from hb-blob.cc:34:
> /opt/i686-w64-mingw32/include/stralign.h: In function ‘WCHAR* ua_wcscpy(PUWSTR, PCUWSTR)’:
> /opt/i686-w64-mingw32/include/stralign.h:37:102: error: ‘wcscpy’ was not declared in this scope
>    __CRT_INLINE PUWSTR ua_wcscpy(PUWSTR Destination,PCUWSTR Source) { return wcscpy(Destination,Source); }

Again, it's error in your mingw32 include files.  Again, suggesting that headers are being mixed and a faulty toolchain setup.

**Comment by behdad** [comment]
Ok I see you are using mingw inside cygwin.  Why not just use cygwin itself?

**Comment by 9064911** [comment]
Hello dear Behdad
Thanks dear for reply, really appreciate it.

Well cygwin builds without any error very awesome. Well i'm on windows and as you mentioned the mingw on linux might work of course, going to have a try of course.

Using cygwin will make it dependent on cygwin runtime, since mingw won't. I also tried to disable ucdn as `--with-ucdn=no` and enable the icu.
The freeze issue could solved, but it gives another error as following
`./configure --with-ucdn=no --with-icu=yes --enable-static=yes --enable-shared=yes --with-glib=no --with-gobject=no --with-cairo=no --with-graphite2=no --with-freetype=yes --host=i686-w64-mingw32 --build=i686-w64-mingw32`
The above results OK with following fin result:
```
Unicode callbacks (you want at least one):
        Builtin (UCDN):         false
        Glib:                   false
        ICU:                    true

Font callbacks (the more the better):
        FreeType:               true

Tools used for command-line utilities:
        Cairo:                  false
        Fontconfig:             true

Additional shapers (the more the better):
        Graphite2:              false

Platform shapers (not normally needed):
        CoreText:               false
        Uniscribe:              false
        DirectWrite:            false

Other features:
        Documentation:          false
        GObject bindings:       false
        Introspection:          false

```
and the make call as following
```
make
make  all-recursive
make[1]: Entering directory '/cygdrive/h/__gits/harfbuzz'
Making all in src
make[2]: Entering directory '/cygdrive/h/__gits/harfbuzz/src'
make[3]: Entering directory '/cygdrive/h/__gits/harfbuzz/src/hb-ucdn'
make[3]: Leaving directory '/cygdrive/h/__gits/harfbuzz/src/hb-ucdn'
make  all-recursive
make[3]: Entering directory '/cygdrive/h/__gits/harfbuzz/src'
make[4]: Entering directory '/cygdrive/h/__gits/harfbuzz/src'
  CXX      libharfbuzz_la-hb-blob.lo
  CXX      libharfbuzz_la-hb-buffer-serialize.lo
  CXX      libharfbuzz_la-hb-buffer.lo
  CXX      libharfbuzz_la-hb-common.lo
  CXX      libharfbuzz_la-hb-face.lo
  CXX      libharfbuzz_la-hb-font.lo
  CXX      libharfbuzz_la-hb-ot-tag.lo
  CXX      libharfbuzz_la-hb-set.lo
  CXX      libharfbuzz_la-hb-shape.lo
  CXX      libharfbuzz_la-hb-shape-plan.lo
  CXX      libharfbuzz_la-hb-shaper.lo
  CXX      libharfbuzz_la-hb-unicode.lo
hb-unicode.cc:149:2: error: #error "Could not find any Unicode functions implementation, you have to provide your own"
 #error "Could not find any Unicode functions implementation, you have to provide your own"
  ^
hb-unicode.cc:150:2: error: #error "Consider building hb-ucdn.c.  If you absolutely want to build without any, check the code."
 #error "Consider building hb-ucdn.c.  If you absolutely want to build without any, check the code."
  ^
make[4]: *** [Makefile:2020: libharfbuzz_la-hb-unicode.lo] Error 1
make[4]: Leaving directory '/cygdrive/h/__gits/harfbuzz/src'
make[3]: *** [Makefile:2431: all-recursive] Error 1
make[3]: Leaving directory '/cygdrive/h/__gits/harfbuzz/src'
make[2]: *** [Makefile:1324: all] Error 2
make[2]: Leaving directory '/cygdrive/h/__gits/harfbuzz/src'
make[1]: *** [Makefile:484: all-recursive] Error 1
make[1]: Leaving directory '/cygdrive/h/__gits/harfbuzz'
make: *** [Makefile:416: all] Error 2
```
When I enable the ucdn it freezes forever as stated, and when I disable it it gives error as above.

=============

About the msys2_mingw32 as you mentioned about toolchain problem. AWESOME, it was my fault indeed, so sorry. Now I could make it very well with msys2_mingw32, but the cygwin_mingw32 still has the problem as it's okay as far as I could make it.

Thanks, happy coding.
CHEERS.

**Comment by behdad** [comment]
I cannot spend more time on this as I don't develop on Windows. Others might be able to help.

**Comment by 9064911** [comment]
It's okay dear behdad, thanks for the help, really appreciate it.

Well as I could fix the toolchain include issue(as you mentioned) and make a success build with the msys2_mingw(both i686, and x86_64).

The issue about the cygwin_mingw could be because of its linker, and a bug by cygwin itself.

Happy coding, thanks.

**Comment by ebraminio** [comment]
So this can be closed I guess. You can use cmake builds also, or [vcpkg](https://github.com/Microsoft/vcpkg) which makes things easier on Windows if you can move rest of your app to it and building static harfbuzz is easy on it as using `vcpkg install harfbuzz:windows-x86-static`.

**Comment by anthrotype** [comment]
@ebraminio thanks for you work on harfbuzz's cmake build and the vcpkg portfile! It really makes super easy to build the harfbuzz library on windows! 👍

**Comment by ebraminio** [comment]
@anthrotype Thank you, actually you motivated me to develop the final goal of all my works on harfbuzz https://github.com/ebraminio/kashida which is a simple but yet in early stage tool to test Kashida implementation of DirectWrite.
