### ISSUE TITLE
Language tags "mal" and "ml" correspond to different language systems

### ISSUE THREAD

**Issue by dscorbett** [behdad/harfbuzz#477]
`ot_languages` in hb-ot-tag.cc maps "mal" to 'MAL ' and "ml" to 'MLR '. "mal" and "ml" are synonymous so they should map to the same language system. Unfortunately, BCP 47 does not distinguish between the traditional and reformed orthographies of Malayalam.

**Comment by behdad** [comment]
@brawer @roozbehp comments?

**Comment by roozbehp** [comment]
'mal' is not standard BCP 47, so it should be removed.

As for MAL vs MLR, it seems that MLR is for modern Malayalam typography, and MAL is for traditional Malayalam typography. (https://www.microsoft.com/typography/OpenTypeDev/malayalam/intro.htm refers to MLM, which seems to be a typo.)

So, I would remove 'mal' and keep mapping 'ml' to MLR.

/cc @cibu

**Comment by dscorbett** [comment]
The same problem is true of "ga" and "gle", which map to 'IRI ' and 'IRT ' though both mean Irish.

**Comment by behdad** [comment]
Any actionable item here?

**Comment by dscorbett** [comment]
Yes: in hb-ot-tag.cc, remove from `ot_languages` the entries for `"gle"` and `"mal"`. That would fix this bug.

There should be some way of specifying traditional Irish and traditional Malayalam, but I could see that being done separately.
