### ISSUE TITLE
Remove win32/ folder and direct nmake support

### ISSUE THREAD

**Issue by ebraminio** [behdad/harfbuzz#479]
First of all I should mention that all @fanc999 works on harfbuzz project is highly appreciated on providing nmake and that was very helpful on making cmake port also happen (namely and used on CMake port items, the creation and separation of Makefile.sources and annotating harfbuzz API with HB_EXPORT, and probably much more I am just missing).

As just a suggestion, now that we have cmake port in and that is able to generate nmake build files also, I like to just propose removal of nmake support and win32 folder entirely from harfbuzz project. I think cmake is just easier to use for Windows people as its better integration with Visual Studio (also even better with [native vs support](https://blogs.msdn.microsoft.com/vcblog/2016/10/05/cmake-support-in-visual-studio/)) and this will reduce maintenance load of harfbuzz project and less confusion of people want to use harfbuzz on their Windows projects.

I should mention however gir/gobject implementation of the cmake port is just not done yet and I probably wouldn't able to reach to it as lack of experience on it, but I am also not sure how much that would be needed for third party projects that was provided on nmake port, and there are possibly more needed tweaks for our just new and early cmake to make it really useful for other projects which probably @fanc999 knows better than me so there is no rush on this and there is also a chance this will be just closed if we conclude removing nmake is not a good move for harfbuzz project. Thanks all.

**Comment by KrasnayaPloshchad** [comment]
👍 I agree with you, to make the build easier on Windows is valuable to be considered. Althrough MS Windows has Uniscribe and DirectWrite to give native support for OT text layout, several Windows developers has expected to intergrate HarfBuzz to get their own support, or free from some technical limits, if we can make some efforts to reduce their fears, we would get great achievement, also get more support from Windows developers whose want to point out what’s wrong with us.

**Comment by ebraminio** [comment]
I can say CMake support is complete except the gir/gobject part, which I am not sure who is interested on it. Have a look at this example, https://github.com/ebraminio/kashida which uses DirectWrite backend of HarfBuzz with a CMake based build system.

**Comment by behdad** [comment]
What's the status of this?

**Comment by ebraminio** [comment]
I suggest just removing win32 folder and redirect all Windows users to https://github.com/Microsoft/vcpkg which is provided by Microsoft so no random Windows compile issues anymore.

**Comment by behdad** [comment]
sgtm.
