### ISSUE TITLE
Arabic complex text layout problem

### ISSUE THREAD

**Issue by 0M1D** [behdad/harfbuzz#480]
There is a problem rendering words with diacritics.
for example, instead of having "تسجّل", which is in right form, I got "تسجّ ل", which is obviously wrong.
Actually, the code that I am using is one of the user examples provided in buzzard wiki page: 
tangrams/harfbuzz-example

![screenshot 79](https://cloud.githubusercontent.com/assets/28187699/25556685/f5f68b70-2d15-11e7-9cb4-edfa0f0d750a.png)

**Comment by jfkthame** [comment]
What font are you using? Have you tried a different Arabic font?

**Comment by 0M1D** [comment]
"amiri-regular.ttf"
yes, I just tried anew with "Adobe Arabic.otf" but ... Nope, the same problem
![error](https://cloud.githubusercontent.com/assets/28187699/25557384/6fe3ba02-2d25-11e7-9553-be5765169f50.png)

**Comment by jfkthame** [comment]
Other harfbuzz clients don't seem to have this problem, which suggests it is an issue with the sample code you're using, or your local build. You could try comparing the results with the basic hb-view tool.

**Comment by 0M1D** [comment]
In fact, it is not my own code. Harfbuzz is downloaded and compiled from GitHub and the source code is an example at GitHub which is suggested at Harfbuzz wiki page it self. I am altering nothing in the code. you can try the example yourself, if ya dont mind.
Thanks anyway for your help.

**Comment by ebraminio** [comment]
Quite likely bug of unicode functions passed to harfbuzz (reminds me HB_NO_UNICODE_FUNCS flag actually) on that particular project https://github.com/tangrams/harfbuzz-example and not related to harfbuzz itself so you should ask maintainers of that project for a fix. Feel free to ping again if you see the same issue with hb-view.exe provided on [release tab](https://github.com/behdad/harfbuzz/releases) of harfbuzz project.

**Comment by 0M1D** [comment]
would you please help me how to fix that error. i mean "Could not find any Unicode functions implementation, you have to provide your own". I think I must resolve that.

**Comment by ebraminio** [comment]
That is a whole different project for me and I am not familiar with its build system and such but my general tip would be using pango instead harfbuzz which is higher level text rendering abstraction useful for other projects and if you are targeting MSVC, you can use https://github.com/Microsoft/vcpkg for installing pango as it offers bidi algorithm (for supporting a text like "متن ۱۲۳" which contains two different text direction) and a lot other needed and well tested things needed for implementing. text rendering which harfbuzz doesn't intend to support on its level of abstraction.

**Comment by 0M1D** [comment]
Indeed, I need Harfbuzz exactly for words with known script and language, not bidirectional or sth complex.
Do you know any open source project which uses Harfbuzz (and possibly freetype), I really need to solve this problem with Harfbuzz.
Thanks in advance.

**Comment by ebraminio** [comment]
If you are able to install Cairo, freetype and harfbuzz from vcpkg, you can try building https://github.com/behdad/harfbuzz-tutorial/blob/master/hello-harfbuzz.c

**Comment by ebraminio** [comment]
I have also developed two related projects on https://github.com/ebraminio/glcourse  and https://github.com/ebraminio/kashida but they came with no bug fix support, sorry.

**Comment by 0M1D** [comment]
thanks, man. I hoooooooooooope that will do.
