### ISSUE TITLE
Character-level RTL mirroring does not match the OpenType spec

### ISSUE THREAD

**Issue by dscorbett** [behdad/harfbuzz#492]
[The OpenType specification](https://www.microsoft.com/typography/otspec/TTOCHAP1.htm#ltrrtl) says that the layout engine should only automatically mirror characters in the [OpenType Mirroring Pairs List](https://www.microsoft.com/typography/otspec/ompl.txt), which is a copy of Bidi_Mirroring_Glyph as of Unicode 5.1. HarfBuzz uses Bidi_Mirroring_Glyph as of Unicode 9.0. The only difference is the addition of the pair U+27CB MATHEMATICAL RISING DIAGONAL ↔ U+27CD MATHEMATICAL FALLING DIAGONAL.

**Comment by behdad** [comment]
Right... This is one of those things that I couldn't convince others when it was being decided, and I decided to stick to my own proposal, which was to use latest mirror list.  It's harmless, so I don't think I'm going to change for now..

**Comment by behdad** [comment]
FWIW, client can provide their own mirror ist that matches OpenType.  Closing this since I don't see any immediate action.
