### ISSUE TITLE
support for AAT 'morx' table

### ISSUE THREAD

**Issue by olivierberten** [behdad/harfbuzz#493]
Fontkit, whose shaping engine is heavily based on harfbuzz, also supports morx shaping. Its code <https://github.com/devongovett/fontkit/tree/master/src/aat> doesn't seem very long so maybe it wouldn't be such a big effort adding such support to harfbuzz ;-)

**Comment by KrasnayaPloshchad** [comment]
This is already reported in #322.

**Comment by behdad** [comment]
I was actually working on this with @brawer last week.

**Comment by khaledhosny** [comment]
AAT also requires supporting Apple’s `kern` subtables which seem to be used for general glyph positioning not just kerning (i.e. more like `GPOS`).

**Comment by behdad** [comment]
Closing in favor of https://github.com/behdad/harfbuzz/issues/322

**Comment by ebraminio** [comment]
Done as https://github.com/harfbuzz/harfbuzz/commit/14ff3cbe0f30dea24e1bb175b1e8e41039f6afdc
