### ISSUE TITLE
Different mark positioning behavior between HarfBuzz and Uniscribe

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [behdad/harfbuzz#500]
The following string has different behavior between HarfBuzz and Uniscribe if I try to use [Libertinus Serif v6.4](https://github.com/khaledhosny/libertinus/releases/tag/v6.4):
`Ā̄Ē̄Ī̄Ō̄Ū̄ā̄ē̄ī̄ō̄ū̄`

Here is my test results with hb-view:
![1](https://ooo.0o0.ooo/2017/06/23/594c9fd35ba80.png)
And what happened in BabelPad:
![2](https://ooo.0o0.ooo/2017/06/23/594c9fd38e597.png)

**Comment by behdad** [comment]
Ok this is because we precompose glyphs when the font supports them, and the font happens to be buggy.  Don't think we are going to make any changes.

**Comment by KrasnayaPloshchad** [comment]
So what’s wrong with it?
