### ISSUE TITLE
Non-Policing Request for Context Substitutions

### ISSUE THREAD

**Issue by Richard57** [behdad/harfbuzz#502]
A context substitution can legitimately convert an input string of 2 glyphs into an output string of 3 glyphs.  If the first glyph is converted to 2 glyphs, is it considered legitimate for the second substLookupRecord to have a Sequence Index of 1?  I have encountered a [problem](http://wrdingham.co.uk/lanna/test/safari_test.htm) with the Core Text implementation of context substitutions, and the simplest work-around involves replacing a sequence of two substLookupRecords

`0 mai_kam_split
2 mai_kam_action`

with a sequence of 3:

`0 mai_kam_split
1 mai_kam_action -- Core Text only - no effect otherwise
2 mai_kam_action -- For other renderers`

Can I be confident that HarfBuzz won't start to refuse to accept the final substitution because it doesn't like the sequenceIndex of the substitution added for Core Text?

The next simplest work-around would require about 60 temporary glyphs to record the need to apply mai_kam_split in the next lookup.

**Comment by behdad** [comment]
We're definitely very non-policing in principle and in practice.  And yes, we don't try to match CoreText.  We try to match Uniscribe when it makes sense and only then.

Right now there's an outstanding issue with out-of-order sequence-indices after deleting glyphs.  I tried fixing that in b9b005f3a44ccf78a45b212b126287b69b9f4b40 but that introduced other problems.  I'll fix it at some point.

cc @nedley re CoreText issue.

**Comment by nedley** [comment]
I’m happy to investigate bugs that are reported against CoreText using bugreport.apple.com.

**Comment by Richard57** [comment]
Isn't that address for paid-up Apple developers?

**Comment by nedley** [comment]
It requires a free account.

**Comment by Richard57** [comment]
That's good news, though setting the account up was very confusing, as I already had an Apple ID.  I've reported the bug as https://bugreport.apple.com/web/?problemID=33370739 "Misinterpretation of Sequence Index in Opentype GSUB Context Substitution".
