### ISSUE TITLE
hb-shape --no-glyph-names --debug

### ISSUE THREAD

**Issue by emuller-amazon** [behdad/harfbuzz#506]
WIth the --no-glyph-names option, the hb-shape output uses (correctly) glyph ids, but the --debug option still uses glyph names. I think it should use glyph ids as well.

**Comment by behdad** [comment]
I agree. Working on this.

BTW, it looks like I just repurposed --debug, which was meant for something else.  I'm going to rename it to something like --show-messages maybe.  Ideas?

**Comment by khaledhosny** [comment]
`--verbose`?

**Comment by behdad** [comment]
> --verbose?

That's already used for something else.

**Comment by emuller-amazon** [comment]
--trace or --trace-features ?

**Comment by behdad** [comment]
Oh I like --trace.  Donno how it didn't occur to me!  Changing to that.

**Comment by behdad** [comment]
Later on, if we make what's currently available with compiling with `HB_DEBUG` be available at runtime, we can add a whole slew of --trace-sanitize, --trace-apply, etc...
