### ISSUE TITLE
hb_ft_font_create is not added to lib file when compiling harfbuzz with nmake under windows

### ISSUE THREAD

**Issue by monhi** [behdad/harfbuzz#511]
Hi Behdad,
I try to compile harfbuzz (1.4.6) under windows operating system with MSDEV 2013,
It was successful.
But when I add this library to following program, I see that 'hb_ft_font_create' is not added to the harfbuzz.lib and dll file.

https://github.com/wutipong/drawtext-sdl2-freetype2-harfbuzz

My nmake command is:
nmake /f Makefile.vc CFG=debug

Ragel is also compiled and added to the project by using mingw project.

Best Wishes,
Mahdi

**Comment by behdad** [comment]
cc @ebramino

**Comment by behdad** [comment]
cc @ebraminio

**Comment by ebraminio** [comment]
You have to compile it with freetype support with something like:

`nmake /f Makefile.vc CFG=debug FREETYPE=1 FREETYPE_DIR=FREETYPE_INCLUDE_PATH ADDITIONAL_LIB_DIR=FREETYPE_LIB_PATH`

You can also use vcpkg which provides tested ports of various C libraries https://github.com/Microsoft/vcpkg for MSVC.

**Comment by ebraminio** [comment]
From @minho at #513:

> Hi again
> Now I use following command line to compile in windows
> nmake /f Makefile.vc CFG=debug FREETYPE=1 FREETYPE_DIR=c:\freetype\include ADDITIONAL_LIB_DIR=c:\freetype\lib
>
> lib and dll files are created successfully
>
> But again it does not support 'hb_ft_font_create' function.

**Comment by ebraminio** [comment]
cc @fanc999

**Comment by monhi** [comment]
Please give me something to test or some idea.
@fanc999
@ebraminio

**Comment by fanc999** [comment]
Hi,

I was not able to reproduce this issue... the DLL/LIB included that symbol when I tried out the build.  Can you rebuild the code by doing

nmake /f Makefile.vc CFG=debug FREETYPE=1 FREETYPE_DIR=c:\freetype\include ADDITIONAL_LIB_DIR=c:\freetype\lib clean

and then redo

nmake /f Makefile.vc CFG=debug FREETYPE=1 FREETYPE_DIR=c:\freetype\include ADDITIONAL_LIB_DIR=c:\freetype\lib

Note that the README.txt says that you should clean and redo the build if you happen to change configuration options.

With blessings, and cheers!

**Comment by monhi** [comment]
Yes by rebuilding the library from scratch finally it compiled successfully.
Thanks a lot
Now you can close this issue.
