### ISSUE TITLE
Indic v3

### ISSUE THREAD

**Issue by behdad** [behdad/harfbuzz#512]
Apple is sending dev3, bng3, etc script tags to Universal Shaping Engine.  We should do the same, but after updating the USE data table to include data for Indic scripts as well.  Would be nice to do this without duplicate data, but then again, the data size is small.

**Comment by behdad** [comment]
I have opened another issue for this apparently.

**Comment by behdad** [comment]
They are not. Do you have fonts built with this I can test?

**Comment by MayuraVerma** [comment]
Hello Behdad,

I have updated the NotoSansKannadaUI with Indic V3 tags. Dropped all the knda and knd2 from it. I can share it here. I suppose it is not any violation of usage rights. 

Apple core text recognizes the font, most of the ligatures, combinations are working fine. 

There are few usual suspects. I am not sure, if it is font issue or shaping engine issue. If we can get to test in harfbuzz, it will be very helpful.

**Comment by brawer** [comment]
@MayuraVerma, can you send a pull request which adds your test font as `TestShapeKndaV3.ttf` to the [fonts directory](https://github.com/unicode-org/text-rendering-tests/tree/master/fonts) in [Unicode’s text rendering tests](https://github.com/unicode-org/text-rendering-tests)? Thank you in advance!

To make test cases for the test suite, we’d a also need a set of strings to be rendered. It should be strings whose rendering will fail (give a different result) when an engine-under-test doesn’t correctly implement V3.

If you make your additions upstream (at Unicode), HarfBuzz (and other implementations, including CoreText) will automatically run your tests; eg. HarfBuzz [imports](https://github.com/harfbuzz/harfbuzz/tree/master/test/shaping/data/text-rendering-tests) this test suite.

**Comment by MayuraVerma** [comment]
@brawer I have send a pull request. I will submit the set of strings as an issue in that project.
