### ISSUE TITLE
harfbuzz problem when compiling in windows with hb_ft_font_create function

### ISSUE THREAD

**Issue by monhi** [behdad/harfbuzz#513]
Dear Behdad,
Hi again
Now I use following command line to compile in windows 
nmake /f Makefile.vc CFG=debug FREETYPE=1 FREETYPE_DIR=c:\freetype\include ADDITIONAL_LIB_DIR=c:\freetype\lib

lib and dll files are created successfully 

But again it does not support 'hb_ft_font_create' function.

Best Regards
Mahdi,

@ebraminio

**Comment by ebraminio** [comment]
Lets revive your old file and move this there, #511
