### ISSUE TITLE
Use existing alternative hyphen glyphs instead of a fallback font

### ISSUE THREAD

**Issue by paperboyo** [behdad/harfbuzz#517]
Hello,

I'm terribly sorry if harbuzz already does this or, indeed, if it's not something harfbuzz should be responsible for (I'm just too lazy to open several bugs against different applications that use harfbuzz :-). I've tried my best to understand if it belongs here, and [this](https://github.com/behdad/harfbuzz/commit/81ef4f407d9c7bd98cf62cef951dc538b13442eb) and [that](https://github.com/behdad/harfbuzz/issues/152) look like it may. Sorry, and feel free to close if I'm wrong!

Recently, I've come across latest Chrome using a ([broken](https://github.com/googlei18n/noto-fonts/issues/946)) fallback font's glyph for a missing non-breaking hyphen glyph: https://github.com/guardian/frontend/issues/17506.

Wouldn't it be prudent to just use U+2010 (and then U+002D) from the same font if U+2011 (or U+2010) is missing instead of going down the fallback route which is unlikely to ever look correct?

Thank you!

Regards
m.

**Comment by behdad** [comment]
> I'm terribly sorry if harbuzz already does this or, indeed, if it's not something harfbuzz should be responsible for (I'm just too lazy to open several bugs against different applications that use harfbuzz :-). I've tried my best to understand if it belongs here, and this and that look like it may. Sorry, and feel free to close if I'm wrong!

We used to do that for all compatibility-decompositions, but there was backlash (for good reason), so disabled it, and implemented spaces specially.  I agree for noBreak cases we should do.  Thankfully there's only five such characters; three of them are already space and handled.  Remains two, which I will implement:
```
grep ';<noBreak' UnicodeData.txt   | grep -v WS | grep -v Zs
0F0C;TIBETAN MARK DELIMITER TSHEG BSTAR;Po;0;L;<noBreak> 0F0B;;;;N;;;;;
2011;NON-BREAKING HYPHEN;Pd;0;ON;<noBreak> 2010;;;;N;;;;;
```

Thanks!

**Comment by paperboyo** [comment]
Thanks, @behdad!

So, after your change, U+2010 will be used when U+2011 is missing. Great and shouldn't be controversial.

What about using U+002D when U+2010 itself is missing, too? One could argue that this may be more controversial (a design for a hyphen-minus could vary from a design for a hyphen). But I would say that if that would be the case - font designer would include U+2010 in the font.

As things stand, many standard fonts - among them e.g. the latest Georgia (v. 5.058) does not have a glyph at U+2010. So your change would still see the fallback go beyond the initial font.

In my humblest of opinions there shouldn't be any backlash for also using U+002D when U+2010 is missing. WDYT?

**Comment by behdad** [comment]
> So, after your change, U+2010 will be used when U+2011 is missing. Great and shouldn't be controversial.

Correct.


> What about using U+002D when U+2010 itself is missing, too? One could argue that this may be more controversial (a design for a hyphen-minus could vary from a design for a hyphen). But I would say that if that would be the intention - font designer would include U+2010 in the font.
> 
> As things stand, many standard fonts - among them e.g. the latest Georgia (v. 5.058) and latest Noto Serif - do not have a glyph at U+2010. So your change would still see the fallback go beyond the initial font.
> 
> In my humblest of opinions there shouldn't be any backlash for also using U+002D when U+2010 is missing. WDYT?

I'm not comfortable doing that.  U+2010 does look distinctly wider than U+002D in most fonts.  I'm sure good typographers wouldn't like me to substitute that... cc @jfkthame

**Comment by behdad** [comment]
Actually, looks like we do handle U+2011, or at least try to.  See 52e6c4e15893ed1cb0997795912a07b3e446b65a

Is this definitely not working for you?

**Comment by paperboyo** [comment]
> U+2010 does look distinctly wider than U+002D in most fonts.

Very true (although the other way around - minus is usually wider :)! But wouldn't substitution happen only if U+2010 is missing - ie. in a situation when a font designer haven't included a distinct U+2010? In my (limited!) experience, when U+2010 is missing, U+002D looks like a hyphen, maybe was even treated as a genuine hyphen by the designer (going by the name _HYPHEN-MINUS_). Case in point would be Georgia again.

> Actually, looks like we do handle U+2011, or at least try to.

🎆  My bad, I haven't actually run the project myself. And the font that [brought me here in the first place](https://github.com/guardian/frontend/issues/17506) is missing both U+2011 and U+2010 (and U+002D looks and talks and walks like a hyphen).

I suspect https://github.com/behdad/harfbuzz/commit/52e6c4e15893ed1cb0997795912a07b3e446b65a is working correctly, so I will wait on your decision regarding a fallback from missing U+2010 to U+002D and will close this. Sorry for the confusion and thank you!

**Comment by behdad** [comment]
Sure, let's see what Jonathan says.

BTW, most users of HarfBuzz will not use this functionality, as they do font selection independently.  The exceptions currently are Chrome and LibreOffice, which use a HarfBuzz-driven font fallback scheme.

**Comment by jfkthame** [comment]
My preference would be *not* to do U+2010 / U+002D substitution. IMO, harfbuzz is supposed to shape the text provided, using the font and features specified; deciding on substitutions for characters that are not supported by a given font should be handled at a separate level. (A client could presumably implement such a substitution by providing a custom get_glyph callback, if it doesn't want to do it in a separate layer prior to calling hb_shape.)

U+2011 / U+2010 seems acceptable, given that the only difference between these characters is expected to be breaking behavior. But mixing HYPHEN-MINUS into this would be a clear step onto a slippery slope of "probably look-alike" replacements (why not do it for U+2212 as well, after all?), and I think we should avoid that.

**Comment by behdad** [comment]
I agree.

**Comment by paperboyo** [comment]
Another font where U+2010 is a direct (component) copy of U+002D is an alpha version of Noto Serif:

![noto](https://user-images.githubusercontent.com/6032869/28919622-8ac920ae-784e-11e7-82c3-b048c49f73df.PNG)

I would think that if font designers want to include a proper minus, they use U+2212 MINUS SIGN...

> BTW, most users of HarfBuzz will not use this functionality, as they do font selection independently. The exceptions currently are Chrome and LibreOffice, which use a HarfBuzz-driven font fallback scheme.

Thanks, that's a very useful info (sorry to have turned this issue into a pre-school for an ignoramus). I care mostly about browsers (will have a look at Edge and Firefox independently, then). I'm pretty sure Adobe apps already cleverly substitute U+2011>U+2010>U+002D (because our print fonts are missing former two), but can't double check now.

@jfkthame 
> U+2011 / U+2010 seems acceptable, given that the only difference between these characters is expected to be breaking behavior. But mixing HYPHEN-MINUS into this would be a clear step onto a slippery slope of "probably look-alike" replacements (why not do it for U+2212 as well, after all?), and I think we should avoid that.

Yep, agreed. Thank you!
