### ISSUE TITLE
CMakelists.txt fix for Freetype builds

### ISSUE THREAD

**Issue by roxlu** [behdad/harfbuzz#518]
Instead of searching for freetype using pkg-config, use the FindFreetype feature of CMake. This allows for better integration with other projects that make use of CMake. 

I've created a patch here https://gist.github.com/roxlu/0108d45308a0434e27d4320396399153#file-harfbuzz_freetype_fix-patch  

You can clone that gist and compile it using the `cmake_build.sh` script. Tested on Windows (in Git Bash) and on OSX. 

* I haven't marked the include directories as advanced in the CMakelists.txt.

**Comment by ebraminio** [comment]
Great. It is OK I believe since you've tested Windows also specifically. Please upload it as a pull request and it will be merged. Marking folders as advanced follows WebKit convention, no problem if is not possible on your change.

**Comment by behdad** [comment]
What's the status of this?

**Comment by ebraminio** [comment]
@roxlu: can you please propose the change as PR?

**Comment by khaledhosny** [comment]
I toke the liberty to submit a PR for this patch https://github.com/behdad/harfbuzz/pull/564.
