### ISSUE TITLE
Requested 'harfbuzz >= 1.2.3' but version of harfbuzz is 0.9.27

### ISSUE THREAD

**Issue by sedci-rocky** [behdad/harfbuzz#520]
I was trying to install **Pango-1.40.7** on an **Ubuntu 14.04** server and harfbuzz was one of the required dependencies. I have already installed **HarfBuzz-1.4.7** but when it comes to installing Pango, it says:

"_checking for HARFBUZZ... no_"

I checked the **config.log** of Pango and there was a line saying:

"_Requested 'harfbuzz >= 1.2.3' but version of harfbuzz is 0.9.27_"

I tried doing **hb-view --version** and it said:

"_hb-view (HarfBuzz) 1.4.7
Available shapers: graphite2,ot,fallback
Linked HarfBuzz library has a different version: 0.9.27_"

How can I solve this issue? Thank you.

**Comment by khaledhosny** [comment]
That is a general software installation issue. Pango uses pkg-config, so you need to make sure the newer version of HarfBuzz you installed is “seen” by pkg-config.

**Comment by sedci-rocky** [comment]
Is there a way to make pkg-config "see" the newer version of HarfBuzz library? Do I need to tweak or configure something on the HarfBuzz package? Sorry for this question. I'm still inexperienced when it comes to updating libraries. Thank you.

**Comment by khaledhosny** [comment]
See pkg-config manual page, you need to `PKG_CONFIG_PATH` env variable to where `harfbuzz.pc` is installed if it is not one of the default paths.

**Comment by sedci-rocky** [comment]
I have now successfully installed Pango. As you mentioned, I have modified the harfbuzz.pc file to point on the appropriate version of HarfBuzz. Thank you @khaledhosny for the prompt responses.
