### ISSUE TITLE
Kerning Wrong in This Case

### ISSUE THREAD

**Issue by ronimg** [behdad/harfbuzz#523]
I'm using Adobe After Effects to render text, then comparing that with the output I'm getting with harfbuzz. Most of the time everything is fine, but in this specific case the kerning looks off.
This is the output from After Effects:
![pasted image at 2017_08_17 08_55 am](https://user-images.githubusercontent.com/5513411/29402065-77c29db8-832b-11e7-9192-e0f2f863544f.png)

And this is the output from harfbuzz:
![screen shot 2017-08-17 at 09 07 46](https://user-images.githubusercontent.com/5513411/29402099-991b8e34-832b-11e7-8638-149cceacfcfc.png)

If you look at how the "r" and the "a" are connecting in the word "Track" you can see the difference.
In After Effects I use what's called "Metrics" which uses the font's internal character pairing. We're doing the same with harfbuzz.

The font is called JOURNAL.

[JOURNAL.TTF.zip](https://github.com/behdad/harfbuzz/files/1230544/JOURNAL.TTF.zip)

Thanks

**Comment by khaledhosny** [comment]
How are you using HarfBuzz? The font does not have `GPOS` table but have a `kern` table, so your font functions need to provide `hb_font_get_glyph_kerning_func_t` callback function for kerning to work.

**Comment by kotuk81** [comment]
Hi, 

The way we are using HarfBuzz is like this: 

       static hb_feature_t KerningOn = { KernTag, 1, 0, std::numeric_limits<unsigned int>::max() };

        std::vector<hb_feature_t> hbFeatures;
        hbFeatures.push_back(HBFeature::KerningOn);
        // Shape it! 
        hb_shape(m_hbFont, m_hbBuffer, hbFeatures.data(), (int32_t)hbFeatures.size());

**Comment by khaledhosny** [comment]
The relevant part would be how you are creating your `m_hbFont`.

**Comment by kotuk81** [comment]
m_fontFace = TrueType.GetFace();
        FT_Set_Char_Size(*m_fontFace, 0, (*m_fontFace)->units_per_EM, (uint32_t)dpi, (uint32_t)dpi);

        if (m_hbFont) {
            hb_font_destroy(m_hbFont);
            m_hbFont = nullptr;
        }

        m_hbFont = hb_ft_font_create(*m_fontFace, NULL);

**Comment by khaledhosny** [comment]
If you are using `hb_ft_font_create` then kerning should work, it works with `hb-view` for that font. I don't know what is goung on, but something is wrong on your side.

**Comment by kotuk81** [comment]
Hm.. I'll test it with the latest version of HarfBuzz...

**Comment by behdad** [comment]
Try with hb-view and report.  Thanks.

**Comment by KrasnayaPloshchad** [comment]
I tested with the latest hb-view and I get the expected effect:
![1](https://i.loli.net/2017/08/21/599a698d7a851.png)
However with the latest LibreOfficeDev [master](http://dev-builds.libreoffice.org/daily/master/Win-x86_64@42/) build I get the different effect, T and r looks not kerned.
![2](https://i.loli.net/2017/08/21/599a69a1517ed.png)

**Comment by kotuk81** [comment]
I found the issue on our side. 
In this particular font the tracking information was part of the pos[i].x_offset.

**Comment by ronimg** [comment]
What version will this fix be in?

**Comment by khaledhosny** [comment]
There is no issue in HarfBuzz, the issue is in the code using HarfBuzz.

**Comment by ronimg** [comment]
Oh, sorry. Got my threads crossed.

**Comment by KrasnayaPloshchad** [comment]
>What version will this fix be in?

HarfBuzz got fixes in 1.7.0.
