### ISSUE TITLE
Dotted circle is inserted between Gurmukhi udaat and vowel sign

### ISSUE THREAD

**Issue by dscorbett** [behdad/harfbuzz#524]
A dotted circle is inserted after the udaat and before the vowel sign in ⟨ਕੑੇ⟩ (U+0A15, U+0A51, U+0A47). _The Unicode Standard_ [recommends this order](http://www.unicode.org/versions/Unicode10.0.0/ch12.pdf#page=32), so there should be no dotted circle: “U+0A51 GURMUKHI SIGN UDAAT [...] should occur after the consonant to which [it] attaches and before any vowel sign.”

**Comment by KrasnayaPloshchad** [comment]
Conifrmed. With BabelPad and Nirmala UI I can see the desired example:
![1](https://user-images.githubusercontent.com/10364351/29503408-0a38b83a-866a-11e7-9c8a-b387af38e61f.PNG)
But with the latest hb-view utility I can see dotted circle: 
![2](https://user-images.githubusercontent.com/10364351/29503431-37aa1d40-866a-11e7-9731-65b865b10dce.png)
If I change the order to U+0A15, U+0A47, U+0A51, both BabelPad and hb-view works as expected, no dotted circle appearing.

**Comment by jfkthame** [comment]
U+0A51 GURMUKHI SIGN UDAAT seems to be missing from IndicSyllabicCategory.txt

**Comment by jfkthame** [comment]
> If I change the order to U+0A15, U+0A47, U+0A51, both BabelPad and hb-view works as expected, no dotted circle appearing.

Is it really desirable that both sequences <0A15, 0A47, 0A51> and <0A15, 0A51, 0A47> should render the same? Or would it be better to support only the sequence recommended by the Standard?
