### ISSUE TITLE
Does not build without HAVE_FALLBACK?

### ISSUE THREAD

**Issue by behdad** [behdad/harfbuzz#526]
Martin reports that.

**Comment by khaledhosny** [comment]
Does it? I changed `have_fallback=false` in `configure.ac`, but build completed just fine (`test-shape` asserted, though).

**Comment by behdad** [comment]
@mhosken ?

**Comment by mhosken** [comment]
Yes it builds that way fine for me too. The context in which it failed was an embedded build within chromium.

**Comment by behdad** [comment]
Chromium was broken.  We fixed it.  Thanks.
