### ISSUE TITLE
Informational: harfbuzz forks with maybe possiblyadded features

### ISSUE THREAD

**Issue by timofonic** [behdad/harfbuzz#527]
https://github.com/fuchsia-mirror/third_party-harfbuzz
https://github.com/TamirEvan/thirdparty-harfbuzz/
https://github.com/TamirEvan/thirdparty-harfbuzz/
Is this the official? https://github.com/freedesktop/harfbuzz
https://github.com/johne53/MB3Harfbuzz
https://chromium.googlesource.com/chromium/src/+log/master/third_party/harfbuzz-ng

I also found other stuff...
git clone https://chromium.googlesource.com/chromium/src/third_party/freetype2
https://github.com/timofonic/freetype2 (mirrored here)

**Comment by fitojb** [comment]
These aren’t forks, these are mirrors…

**Comment by behdad** [comment]
Nothing interesting in these.
