### ISSUE TITLE
Kannada JIHVAMULIYA and UPADHMANIYA insert dotted circles

### ISSUE THREAD

**Issue by roozbehp** [behdad/harfbuzz#528]
According to Unicode, these should display fine just appearing by themselves. But HarfBuzz inserts dotted circles after them. Here's the result of:

./test/shaping/hb-unicode-encode 0CF1 20 0CF2| ./util/hb-view --font-file=$HOME/src/noto-fonts/unhinted/NotoSansKannada-Regular.ttf --output-file=kannada.png
![kannada](https://user-images.githubusercontent.com/302255/29953425-f5060616-8e84-11e7-901c-e12cd29850f1.png)

**Comment by jfkthame** [comment]
The same will presumably apply to the equivalent Brahmi signs U+11003 and U+11004, as these also have Indic_Syllabic_Category=Consonant_With_Stacker, which is not being handled correctly by harfbuzz. (See hb-ot-shape-complex-indic-private.hh, which treats it as OT_Repha, with a suspicious-looking TODO comment!)

**Comment by jfkthame** [comment]
BTW, does the Noto Kannada font have any support for these characters (besides just rendering simple glyphs)? From a quick look, I'm not seeing any sign of the expected ligatures for things like <U+0CF2, U+0CAB>.

**Comment by behdad** [comment]
From shaping point of view looks to me like just treating them as consonant is best.  I'll commit that for now.

**Comment by roozbehp** [comment]
@jfkthame There's a bug open for complex behavior of these in Noto Sans Kannada at https://github.com/googlei18n/noto-fonts/issues/459

**Comment by dscorbett** [comment]
This change breaks the latest development version of FreeSerif. FreeSerif uses 'psts' to substitute consonants with their subjoined forms following jihvamuliya and upadhmaniya, but now that `Consonant_With_Stacker` is treated as `Consonant`, 'psts' does not get applied.

**Comment by behdad** [comment]
> This change breaks the latest development version of FreeSerif.

Humm....

> FreeSerif uses 'psts' to substitute consonants with their subjoined forms

That should happen in 'pstf', not 'psts'.

> following jihvamuliya and upadhmaniya, but now that Consonant_With_Stacker is treated as Consonant, 'psts' does not get applied.

**Comment by dscorbett** [comment]
'pstf' applies to “_Halant_ + _Consonant_ combinations”, but these characters subjoin following consonants without any halant. So is 'pstf' appropriate?

**Comment by behdad** [comment]
Why does 'psts' not apply?!

**Comment by behdad** [comment]
We apply 'psts' globally.

**Comment by dscorbett** [comment]
Is it global to the cluster or global to the whole input string?

**Comment by behdad** [comment]
> Is it global to the cluster or global to the whole input string?

Global to the syllable.  Though, backtrack/lookahead can span across syllable boundaries.

**Comment by behdad** [comment]
Ok so the problem I suppose is that now the stacked component ends up in a separate cluster...

**Comment by behdad** [comment]
So we do need a better solution for these, as they behave more like "consonant halant".  I suppose we can hack the grammar.  @jfkthame WDYT?

**Comment by behdad** [comment]
@dscorbett do you have tests you can contribute to HarfBuzz perhaps?

**Comment by dscorbett** [comment]
I could make a pull request using record-test.sh, but FreeSerif is GPL-licensed and I don’t know any other font that tries to handle these characters. Would that be okay?

**Comment by behdad** [comment]
Yes, GPL is fine for the tests.  I was thinking maybe you have a test suite that failed...

**Comment by JelleBosmaMT** [comment]
FYI Starting with the design proposal for Noto Sans Kannada update:

With a calt or abvs lookup I can get a subscript consonant after JIHVAMULIYA and UPADHMANIYA in Mac Safari and Chrome browsers, reproducing the samples given by Unicode. With blwf it doesn't work. In Windows it doesn't work at all. Which is not a problem for HarfBuzz.
