### ISSUE TITLE
Kannada AAT font issue

### ISSUE THREAD

**Issue by bengulurumanjunatha** [behdad/harfbuzz#531]
ಪೋಸ್ಟ್‌ಪೇಯ್ಡ್‌ and ಎಕ್ಸ್‌ಪ್ರೆಸ್ have failed to rendered in Chrome (harfbuzz) on Mac OS with "Kannada Sangam MN" and "Kannada MN" AAT fonts. 

Open this below page in Safari and Chrome.
http://kannadafont.blogspot.com/2017/03/blog-post.html

Please compare the result between Safari Version 11.0 (13604.1.38.1.6) and Chrome Version 60.0.3112.113 (Official Build) (64-bit)

Safari screenshot
![Safari screenshot](https://user-images.githubusercontent.com/30472162/30005800-240da4dc-90b0-11e7-8e9f-d774e9fcd0fe.png)

Chrome screenshot
![Chrome screenshot](https://user-images.githubusercontent.com/30472162/30005826-8f3125b8-90b0-11e7-8c51-460b92cd98ab.png)

**Comment by behdad** [comment]
Can you provide the shortest sequence that misrenders?  With which font exactly?  What version of OS X?

**Comment by bengulurumanjunatha** [comment]
It is happening with halant followed by consonant followed by halant, zwnj and then consonant/Vowel
Sequence 1
(u+0cb8)(u+0ccd)(u+0c9f)(u+0ccd)(u+200c)(u+0caa)
Sequence 2
(u+0c95)(u+0ccd)(u+0cb8)(u+0ccd)(u+200c)(u+0caa)
Sequence 3
(u+0c95)(u+0ccd)(u+0cb8)(u+0ccd)(u+200c)(u+0c8e)

Fonts: Kannada Sangam MN and Kannada MN, they are system default fonts in Mac OS for Sans-serif and Serif class respectively.
Mac OS version: High Sierra, build 17A365.

**Comment by jfkthame** [comment]
I can't seem to reproduce this on Sierra (10.12), so I wonder if there has been a change in the Kannada fonts or Core Text shaping that's affecting it somehow.

Test with hb-view:

    hb-unicode-encode u+0cb8 u+0ccd u+0c9f u+0ccd u+200c u+0caa 20 u+0c95 u+0ccd u+0cb8 u+0ccd u+200c u+0caa 20 u+0c95 u+0ccd u+0cb8 u+0ccd u+200c u+0c8e | hb-view --font-file /Library/Fonts/Kannada\ MN.ttc --shaper coretext

results in the expected shaping, and the corresponding text also looks OK in Chrome on this system.

We should re-test on High Sierra when we have the opportunity...

**Comment by behdad** [comment]
> We should re-test on High Sierra when we have the opportunity...

@anthrotype can you test please?

**Comment by MayuraVerma** [comment]
Both KannadaSangamMN and KannadaMN has been updated (recompiled) in High Sierra. 
And iOS 11 added native Kannada keyboard. Although there is no documentation about the fonts. When I compare the older version fonts with ones in High Sierra, the newer version is updated to Unicode 10. 

I can test this and report back in a day.

**Comment by anthrotype** [comment]
@behdad sorry I didn’t see this 😐 I can test once I’m back to London (don’t have my mac with me atm).

**Comment by MayuraVerma** [comment]
Chrome has issue with Kannada Sangam MN, Kannada MN and Baloo Thamma.

![screen shot 2017-10-20 at 6 49 31 pm](https://user-images.githubusercontent.com/14062593/31845552-7c09afe6-b5c7-11e7-9969-a9a434cdd96b.png)

![screen shot 2017-10-20 at 6 48 59 pm](https://user-images.githubusercontent.com/14062593/31845553-7c22ce9a-b5c7-11e7-86b8-676ded680944.png)

**Comment by bengulurumanjunatha** [comment]
As you might know, MN fonts uses both AAT feature and OpenType feature. 

Chrome is picking up the AAT feature to render Kannada text in mac. 

Safari is picking up OT feature. 

Mail app in mac uses AAT feature in Address bar (failed render) and OT in the content (correct render). 

![screen shot 2017-11-18 at 10 25 03 am](https://user-images.githubusercontent.com/30472162/32982475-00e44674-cc4b-11e7-9d59-8fc356c6f22d.png)

So it is apparent from the above the screenshot. This is a font issue.

I am closing this issue.
