### ISSUE TITLE
how to use nastaliq font with harfbuzz

### ISSUE THREAD

**Issue by monhi** [behdad/harfbuzz#534]
Dear Behdad,
Hi,
I would like to use harfbuzz with nastaliq font 
you can download nastaliq font from following link

[nastaliq url](http://www.sarzamindownload.com/930/-%D9%81%D9%88%D9%86%D8%AA-%D9%86%D8%B3%D8%AA%D8%B9%D9%84%DB%8C%D9%82---Nastaliq-Font
)

But when I use it with my sample program, I find that characters are not connected to each other correctly.
Problem is in junction point between characters. 
Please tell me how to overcome this. 

Thanks in advance 
Mahdi,

**Comment by khaledhosny** [comment]
Did you try with `hb-view`? IranNastaliq definitely works with HarfBuzz, so might be a problem in your integration code.

**Comment by monhi** [comment]
Salam
Thanks a lot Khaled
hb-view works perfect.
Now I am going to use hb-view source code for integration.
