### ISSUE TITLE
Fallback positioning of half marks

### ISSUE THREAD

**Issue by dscorbett** [behdad/harfbuzz#535]
Combining half marks (U+FE20 through U+FE2F) are meant to join with half marks in adjacent grapheme clusters. Changing their x and y positions disrupts their joining. Fallback positioning should therefore not reposition these glyphs. Fallback positioning should still take them into account for cases like ⟨a︠́b︡⟩ where another mark is placed relative to the half mark.

Alternatively, fallback positioning could reposition an entire conjoining sequence of half marks together. This would look good but might be too complicated to be worth while.

**Comment by behdad** [comment]
My take is, any font that wants to implement that must use GPOS.
