### ISSUE TITLE
Supplementing overriding ot font functions?

### ISSUE THREAD

**Issue by khaledhosny** [behdad/harfbuzz#536]
Is there a way to override/supplement a font function in ot font functions like one can do with unicode functions? Like, say, I want to implement hb_font_get_glyph_h_kerning_func_t while using the rest of the ot functions.

**Comment by behdad** [comment]
`hb_font_create_sub_font`?

**Comment by khaledhosny** [comment]
Right. Let me see if I can get it to work.

**Comment by behdad** [comment]
Let's do it in hb-ot-font itself.

**Comment by khaledhosny** [comment]
> Let's do it in hb-ot-font itself.

The overriding or the kern support?

**Comment by behdad** [comment]
> The overriding or the kern support?

'kern' table support in hb-ot-font. Isn't that what you need?

**Comment by khaledhosny** [comment]
Yes :)

**Comment by behdad** [comment]
Would you like to give it a try, or I should?

**Comment by khaledhosny** [comment]
If you have time that would be great, otherwise I might give it a try next week or so.

**Comment by behdad** [comment]
I'll do next week.  I like to integrate it in the shaper by default as well. Ie. like GPOS.

**Comment by khaledhosny** [comment]
>  I like to integrate it in the shaper by default as well. Ie. like GPOS.

Makes sense. One less way to get inconsistent output from HarfBuzz.

**Comment by behdad** [comment]
> I like to integrate it in the shaper by default as well. Ie. like GPOS.
> 
> Makes sense. One less way to get inconsistent output from HarfBuzz.

Yeah. And I have some exciting ideas...

**Comment by behdad** [comment]
Let's follow up in https://github.com/behdad/harfbuzz/issues/250
