### ISSUE TITLE
Dotted circle between Bengali anji and candrabindu

### ISSUE THREAD

**Issue by dscorbett** [behdad/harfbuzz#538]
A dotted circle is inserted between U+0980 BENGALI ANJI and U+0981 BENGALI SIGN CANDRABINDU in ⟨ঀঁ⟩, but that is a valid cluster.

**Comment by jfkthame** [comment]
Looks like U+0980 BENGALI ANJI is missing from Unicode's IndicSyllabicCategory.txt, which is why we don't recognize it as part of a valid cluster.

(The proposal http://unicode.org/L2/L2011/11359-bengali-anji.pdf confirms that it's appropriate for CANDRABINDU to appear on this character.)

**Comment by jfkthame** [comment]
> U+0980 BENGALI ANJI is missing from Unicode's IndicSyllabicCategory.txt

FTR, reported this via the Unicode feedback form.

**Comment by behdad** [comment]
Fixed.

Would be nice to add a test for it.  David, do you have a test font?

**Comment by dscorbett** [comment]
[Lohit Assamese 2.91.5](https://releases.pagure.org/lohit/lohit-assamese-ttf-2.91.5.tar.gz)
