### ISSUE TITLE
harfbuzz truncates Arabic text

### ISSUE THREAD

**Issue by munzirtaha** [behdad/harfbuzz#540]
I started seeing Arabic text broken in many Qt-based applications like Calligra and Calibre. I've just filed a bug at
https://bugreports.qt.io/browse/QTBUG-63326
Then, it occurred to me it might be a harfbuzz issue, so I tested with
hb-view ./Scheherazade-Regular.ttf "لغة الضاد (59:20) ضاعت مرة أخرى Qt"
and Indeed the text is 97% truncated!

Does this test indicate it's a harfbuzz issue?

**Comment by behdad** [comment]
Attach screenshot.

**Comment by behdad** [comment]
And do you have Graphite enabled or not?

**Comment by munzirtaha** [comment]
Yes, the Arch package is compiled with graphite as can be seen in this screenshot which also shows how the text is rendered both in a terminal and a window

![hb-view](https://user-images.githubusercontent.com/2936425/30670857-cddbe572-9e6c-11e7-9888-d33965ae11c9.png)

**Comment by behdad** [comment]
@mhosken

**Comment by mhosken** [comment]
Not sure what is going on. Here are some comparative figures:

hb-shape .fonts/Scheherazade-Regular.ttf "لغة الضاد (59:20) ضاعت مرة أخرى Qt"
[t=33+430|Q=32+1114|space=31+512|uni0649=30+1000|uni0631.fina=29+487|uni062E.init=28+977|uni0627=27+297|uni0654=27@-307,79+0|space=26+512|uni0629=25+372|uni0631.fina=24+487|uni0645.init=23+578|space=22+512|uni062A.fina=21+1378|uni0639.init=20+735|uni0627.fina=19+362|uni0636.init=18+1210|space=17+512|parenleft=16+547|zero=15+772|two=14+772|colon=13+641|nine=12+772|five=11+772|parenright=10+547|space=9+512|uni062F=8+621|uni0627.fina=7+362|uni0636.medi=6+1210|uni0644.init=5+336|uni0627=4+297|space=3+512|uni0629.fina=2+553|uni063A.medi=1+590|uni0644.init=0+336]

hb-shape .fonts/Scheherazade-Regular.ttf "لغة الضاد (59:20) ضاعت مرة أخرى Qt" --shapers=ot
[t=33+430|Q=32+1114|space=31+512|uni0649=30+1130|uni0631.fina=29@-130,0+357|uni062E.init=28+977|uni0654=27@-10,79+0|uni0627=27+297|space=26+512|uni0629=25+502|uni0631.fina=24@-130,0+357|uni0645.init=23+578|space=22+512|uni062A.fina=21+1378|uni0639.init=20+735|uni0627.fina=19+362|uni0636.init=18+1210|space=17+512|parenleft=16+547|zero=15+772|two=14+772|colon=13+641|nine=12+772|five=11+772|parenright=10+547|space=9+512|uni062F=8+621|uni0627.fina=7+362|uni0636.medi=6+1210|uni0644.init=5+336|uni0627=4+297|space=3+512|uni0629.fina=2+553|uni063A.medi=1+590|uni0644.init=0+336]

There are minor differences between the results, even with glyphs in different orders within a cluster, but nothing that would seemingly cause the output failure I also get.

**Comment by mhosken** [comment]
missing xscale in graphite integration.
