### ISSUE TITLE
Compilation fails on mac 10.9 with 

### ISSUE THREAD

**Issue by roxlu** [behdad/harfbuzz#55]
See configure / make output 
https://gist.githubusercontent.com/roxlu/60ebdff18f4e29d14a75/raw/45e502d743e29c0cb9a960cb8a86330e94f915fd/gistfile1.txt

See generated .hh
https://gist.github.com/roxlu/110abf7e040821c1f2f6#file-hb-ot-shape-complex-myanmar-machine-hh-L23

**Comment by behdad** [comment]
Closing obsolete.  I think you might have had ragel from master, which was not working properly when I checked last year.
