### ISSUE TITLE
windows bots failing

### ISSUE THREAD

**Issue by behdad** [behdad/harfbuzz#551]
I added a test to indic-syllable and curiously just the mingw bots are failing:
https://ci.appveyor.com/project/behdad/harfbuzz/build/1.0.549

Quite likely appveyor issue.  Just filing here and moving on.

We should make the test suite just print the test log in the bots.

**Comment by ebraminio** [comment]
Interesting error it has, mix of Windows and Unix style paths on [path env](https://ci.appveyor.com/project/behdad/harfbuzz/build/1.0.549/job/noyk4iaqnqtukbo0#L686), possibly an internal issue of msys2 or autotools on it, I am in favor of commenting [these lines](https://github.com/behdad/harfbuzz/blob/master/appveyor.yml#L35-L42) out for now. We are also [changing PATH](https://github.com/behdad/harfbuzz/blob/master/appveyor.yml#L68) on our CI script but it is not the issue I guess as PATH is already have other non-UNIX style paths.

**Comment by khaledhosny** [comment]
The libtool issue does not seem to be the actual one, but rather this test failure: https://ci.appveyor.com/project/behdad/harfbuzz/build/1.0.549/job/noyk4iaqnqtukbo0#L800. We should print the test-suite.log to stdout when make check fails. Trying this now.

**Comment by khaledhosny** [comment]
Looks like a rounding error or something (or bug in FreeType):
```
hb-shape fonts/sha1sum/87f85d17d26f1fe9ad28d7365101958edaefb967.ttf  --unicodes U+0980,U+0981
Actual:   [anjibeng=0+519|candrabindubeng=0+0]
Expected: [anjibeng=0+520|candrabindubeng=0+0]
```
