### ISSUE TITLE
Mark positioning on a decomposed glyph

### ISSUE THREAD

**Issue by typoman** [behdad/harfbuzz#558]
Let's say a glyph gets decomposed into three glyphs: baseLetter (with or without unicode), connection (without unicode), mark (with or without unicode). In this sequence the connection is a base glyph and has mark positioning. In CoreText the mark is positioned based on the connection but in Harfbuzz it gets positioned on the baseLetter still. I thought the logical behaviour should be the mark being placed on the glyph that comes before it but it seems harfbuzz is is trying to place the mark on the character that comes first. Is this desired behaviour because I was expecting same result as what CoreText does?

**Comment by behdad** [comment]
We do attach to first in sequence because that seems to be what Uniscribe does. Cc @nedley @PeterCon

**Comment by nedley** [comment]
Please [file a bug](http://bugreport.apple.com) with a sample font if you think there is a CoreText problem.

**Comment by typoman** [comment]
I still don't know if this is the CoreText problem until I find the reason behind why Uniscribe does it. This seems like an override of default behaviour which is causing problem for rendering of the font I'm developing.

**Comment by behdad** [comment]
There is no why.  There's what Uniscribe does, and that's it. HarfBuzz chooses to match it.  CoreText can choose to match or not.

Here's the HarfBuzz commit, with test sequence:
```
commit 7b84c536c10ab90ed96a033d88e9ad232d46c5b8
Author: Behdad Esfahbod <behdad@behdad.org>
Date:   Fri Jun 8 22:04:23 2012 -0400

    In MarkBase attachment, only attach to first of a MultipleSubst sequence
    
    This is apparently what Uniscribe does.  Test case is:
    
      SEEN FATHA TEH ALEF
    
    with Arabic Typesetting.  Originally reported by Khaled Hosny.
```

**Comment by typoman** [comment]
Thank you for explanation!

**Comment by behdad** [comment]
Bahman.  Please file an Apple bug.

**Comment by typoman** [comment]
Sure, I will also refer it to this thread, since I can't explain why it's a bug other than Uniscribe does it differently.

**Comment by nedley** [comment]
I see the other bug now, thanks for filing it.

**Comment by behdad** [comment]
Please keep me posted.  Thanks.
