### ISSUE TITLE
Bots failing

### ISSUE THREAD

**Issue by behdad** [behdad/harfbuzz#574]
Don't know what's wrong with them....

**Comment by ebraminio** [comment]
They are protesting apparantly :)

Can [this](https://ci.appveyor.com/project/behdad/harfbuzz/build/1.0.642/job/t1a686u8o8rcqr91#L837) an expected issue? "ERROR:test-set.c:49:test_not_empty: assertion failed (hb_set_get_population (s) != 0): (0 != 0)" be an issue somehow? Don't know about the code so not sure why this only happens on msys2 environment only and not a real *nix environment even.

**Comment by behdad** [comment]
Or how 0 != 0...

**Comment by khaledhosny** [comment]
Not all 0s are made equal.

**Comment by behdad** [comment]
O_o!

**Comment by ebraminio** [comment]
Replacing "g_assert_cmpint" to "g_assert_cmpuint" didn't fix it on my test. [This new glib change](https://github.com/GNOME/glib/commit/702b6af87cbb61bad64dcbef0be893f1560db018#diff-9e9b76615aa71e7f5e0c816ed68ae8eb) can be related apparently.

**Comment by behdad** [comment]
I *think* I found it.  `_hb_popcount64()` was failing on gcc if `sizeof(long) == 4`.

**Comment by ebraminio** [comment]
According to https://ci.appveyor.com/project/behdad/harfbuzz/build/1.0.646
