### ISSUE TITLE
PAGE_SIZE in hb-set-private.hh collides with Android NDK asm/page.h PAGE_SIZE macro

### ISSUE THREAD

**Issue by drott** [behdad/harfbuzz#576]
I suggest to add an #undef, compare
https://chromium-review.googlesource.com/c/chromium/src/+/718752/12/third_party/harfbuzz-ng/src/hb-set-private.hh#33

**Comment by ebraminio** [comment]
@drott and @behdad, can you help on reproducing this so we can test Android properly on hb CI?

If you issue this command:
`mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a -DANDROID_NATIVE_API_LEVEL=16  ..`

on a system with proper $ANDROID_NDK environment variable, an arm compatible binary will be built but I can't see this issue specifically. What do you suggest for reproducing this?

**Comment by drott** [comment]
Probably the Chromium freetype_harfbuzz target GN build pulled in some of the Android headers. If you have a Chromium build and prepare it to build Android targets, then acquire a preprocessed output for one of the failing files, you may be able to see where this is pulled from. 

I am not sure how the NDK is structured, but otherwise perhaps adding some forced global includes from the NDK may help checking this in CI.
