### ISSUE TITLE
unbreak on BSD where the major() function is defined

### ISSUE THREAD

**Issue by ajacoutot** [behdad/harfbuzz#577]
Hi.

The commit deed4a48d15d4a475f8695aa3269547adf63867a broke building harfbuzz on BSD systems.

`In file included from hb-set.cc:27:
./hb-set-private.hh:466:16: error: expected ')'
  unsigned int major (hb_codepoint_t g) const { return g / PAGE_SIZE; }
`

It's probably due to the fact that we have major(3) defined in sys/types.h.
See https://linux.die.net/man/3/major and https://man.openbsd.org/major
Fix is easy, let's just rename major into something less common. I didn't open a pull request because I'll leave it up to you to decide on the naming :-)
Thanks!

**Comment by ebraminio** [comment]
@ajacoutot, feel free to send a pull request for this also but other than that, is there any free CI service, like TravisCI/CircleCI/Jenkins for Linux/macOS or AppVeyor for Windows (or some in house you might have?) so we can test harfbuzz against freebsd also?

**Comment by ebraminio** [comment]
Our best bet is using a complicated qemu based solution it seems, [1](https://www.freebsdnews.com/2016/10/07/running-freebsd-travis-ci/), [2](http://erouault.blogspot.com/2016/09/running-freebsd-in-travis-ci.html), [3](https://github.com/rouault/gdal_coverage/blob/freebsd9.2/.travis.yml).

**Comment by behdad** [comment]
Thanks for the report. I'll rename.

**Comment by ajacoutot** [comment]
@ebraminio unfortunately I am not aware of any CI SaaS offering for BSD systems :-/
@behdad awesome, thanks for fixing!
Cheers guys.

**Comment by ebraminio** [comment]
@ajacoutot, hi there, #595 adds freebsd9 cross-build. I hope this can help preventing issues like this in future, I guess you can suggest to other projects also. It uses freebsd9 with gcc4, was "major" also defined?

**Comment by ajacoutot** [comment]
@ebraminio , hey ! Yes, major was also defined in FreeBSD. I believe it exists on all BSD :-)
Thanks.
