### ISSUE TITLE
hb_set_intersect appears to be broken in 1.6.2

### ISSUE THREAD

**Issue by jfkthame** [behdad/harfbuzz#579]
I'm seeing unexpected results from hb_set_intersect (often, but not invariably, returning an empty result, when the two sets did have some intersection).

This is breaking behavior in Firefox, where it is wanting to determine whether a given feature supports all the glyphs in a text run.

E.g.

    inputGlyphs: 886 887 888 889 890 891 892 893 894 895 1024 1152
    glyphsInRun: 889 1024
    intersection: (empty)

But:

    inputGlyphs: 886 887 888 889 890 891 892 893 894 895 1024 1152
    glyphsInRun: 887 888 889 1121
    intersection: 887 888 889 1121

For a given pair of sets, the result is consistent, but it's not obvious why the one case fails while the other succeeds.

**Comment by jfkthame** [comment]
(See https://bugzilla.mozilla.org/show_bug.cgi?id=1411005.)

**Comment by jfkthame** [comment]
> For a given pair of sets, the result is consistent, but it's not obvious why the one case fails while the other succeeds.

On second glance, neither result there looks correct, actually: in the second example, the "intersection" includes a GID that was not present in the inputGlyphs set. Oops!

**Comment by behdad** [comment]
Separately, I'm interested to learn more about how you use this stuff in Firefox. I know about the word cache usage, but this sounds like something different.

**Comment by behdad** [comment]
Humm.  I added a test for the samples you provide, but it's passing.

**Comment by behdad** [comment]
@jfkthame any chance you can debug this a bit?

**Comment by jfkthame** [comment]
See PR#582 for a test that fails (at least for me). Haven't tried to debug yet.

**Comment by jfkthame** [comment]
With the second commit in https://github.com/behdad/harfbuzz/pull/582, the added test now passes for me.

**Comment by jfkthame** [comment]
> Separately, I'm interested to learn more about how you use this stuff in Firefox. I know about the word cache usage, but this sounds like something different.

We use this when determining whether a feature such as superscript covers all the glyphs that are present in an element styled with `font-variant-position: super`. If so, we can render the font-variant style using the OpenType feature, but if not, we'll use a synthetic fallback for the whole run (because a mix of "real" superscripts and fake ones within a single element could look pretty bad).

**Comment by behdad** [comment]
> We use this when determining whether a feature such as superscript covers all the glyphs that are present in an element styled with font-variant-position: super. If so, we can render the font-variant style using the OpenType feature, but if not, we'll use a synthetic fallback for the whole run (because a mix of "real" superscripts and fake ones within a single element could look pretty bad).

Cool.  Thanks.  FYI @drott
