### ISSUE TITLE
Appveyor VS bots don't run tests

### ISSUE THREAD

**Issue by behdad** [behdad/harfbuzz#588]
Is it possible to fix this?  See eg:
https://ci.appveyor.com/project/behdad/harfbuzz/build/1.0.694

Thanks.

**Comment by ebraminio** [comment]
> Appveyor VS bots don't run tests

You've fixed it seems? Newer tries seem to run fine.

**Comment by ebraminio** [comment]
Aha, why the above ones do not run tests? Well, our cmake setup doesn't contain tests and given the fact test scripts are very unix-ish it is not trivial to add it seems.

**Comment by behdad** [comment]
> Aha, why the above ones do not run tests? Well, our cmake setup doesn't contain tests and given the fact test scripts are very unix-ish it is not trivial to add it seems.

Ok, got it.

**Comment by behdad** [comment]
Ok, let's call it working as intended for now then.

**Comment by ebraminio** [comment]
It would be nice to run of course but given the fact we want eventually migrate to meson, no lots of motivation here.

**Comment by khaledhosny** [comment]
I think cmake build should at least run the API tests, these shouldn’t require any external tools. Fpr the shaping tests, it shouldn’t be too hard to port the test runner to Python if that would make it either to run on Windows.
