### ISSUE TITLE
configure.ac says '--with-gobject' is 'default=auto' but '--with-gobject=no' is being passed instead.

### ISSUE THREAD

**Issue by luc14n0** [behdad/harfbuzz#607]
A commit long ago changed the passed value of `--with-gobject` from `=auto` to `=no`. Whether the change was intentional and the person forgot to set `default=no` or was a mistake. The help text says its default value is auto as well.

This came to my attention when inspecting the .spec file of the application and I noticed that gobject was being installed but wasn't being used at the build. And I wasn't using `--with-gobject`. Here's the parameter in question code:

```
AC_ARG_WITH(gobject,
	[AS_HELP_STRING([--with-gobject=@<:@yes/no/auto@:>@],
			[Use gobject @<:@default=auto@:>@])],,
[with_gobject=no])
```

**Comment by behdad** [comment]
Thanks.

**Comment by luc14n0** [comment]
You're welcome.
