### ISSUE TITLE
Add link to hosted docs

### ISSUE THREAD

**Issue by SimonSapin** [behdad/harfbuzz#608]
Hi. I’ve found docs hosted at https://behdad.github.io/harfbuzz/, but it took me a while. I’ve added a link at https://github.com/behdad/harfbuzz/wiki#user-guide. It would be nice to add one at https://www.freedesktop.org/wiki/Software/HarfBuzz/ too, but I don’t know how to do that.

**Comment by behdad** [comment]
Right.  I filed that also: https://github.com/behdad/harfbuzz/issues/546

**Comment by behdad** [comment]
Our whole website / docs thing needs a lot of love :(
