### ISSUE TITLE
Windows CLI tools crash on variation selector

### ISSUE THREAD

**Issue by dscorbett** [behdad/harfbuzz#613]
After downloading and unzipping harfbuzz-1.6.3-win32.zip, `hb-shape Maithili.otf --unicodes 30,fe00` crashes. This only happens on Windows. It also happens with hb-view. The particular font doesn’t matter. It happens with any of the 256 variation selectors, not including the Mongolian ones. It doesn’t matter whether the font supports the variation selector. It doesn’t matter whether you use `--unicodes`, `--text`, or `--text-file`. It doesn’t crash if the variation selector is the first character on a line of the input, such as `fe00` or `30,a,fe00`. It crashes after processing previous lines; e.g. `30,a,30,fe00,a,30` successfully outputs one shaped line before crashing.

**Comment by khaledhosny** [comment]
Does it also crash with `--font-funcs=ot`?

**Comment by dscorbett** [comment]
No.

**Comment by khaledhosny** [comment]
Probably a Freetype bug then, or an old version is used to build these binaries.

**Comment by behdad** [comment]
Yeah I think the freetype DLL I'm distributing is either old and doesn't have that function, or otherwise is messed up.  I can replace with a better one if someone sends me one.

**Comment by behdad** [comment]
Anyone?

**Comment by behdad** [comment]
I have a DLL I built, but I need someone on Windows to try it.  Am going to release 1.7.0 without this though.

**Comment by khaledhosny** [comment]
I can test on Windows.

**Comment by behdad** [comment]
I released 1.7.1 with newer FreeType DLL.  David, please test and reopen if still happens.  Thanks.

**Comment by dscorbett** [comment]
The new DLL fixed it. Thanks!
