### ISSUE TITLE
CJK Punctuation in vertical mode

### ISSUE THREAD

**Issue by drott** [behdad/harfbuzz#63]
I am facing some issues with glyph choice when using buffer direction TTB. (That's on HarfBuzz master)

```
./hb-view /usr/share/fonts/truetype/wqy/wqy-microhei.ttc --features=-vert,-vrt2 --font-size 20  --direction ttb "【2009 年 11 月 4 日美國加訊】，「不僅徹生態，遊戲。」" | display

./hb-view /usr/share/fonts/truetype/simsun/simsun.ttc --font-size 20  --direction ttb "【2009 年 11 月 4 日美國加訊】，「不僅徹生態，遊戲。」" | display
```

Where SimSun is available on Windows, WenQuanYi Micro Hei for example on Ubuntu.

![microhei_ttb](https://cloud.githubusercontent.com/assets/1021784/4560129/9bb47c20-4ef2-11e4-9521-6124dda79035.png)

![simsun_ttb](https://cloud.githubusercontent.com/assets/1021784/4560124/90c95966-4ef2-11e4-9b67-9968c2d549f0.png)

I've experimented with ```--features=+vert,+vrt2``` and ```--features=-vert,-vrt2``` but that didn't lead to any changes. Am I mising something?

**Comment by KrasnayaPloshchad** [comment]
How about Droid Sans Japanese, MotoyaLMaru, MotoyaLCedar and Noto Sans JP?

**Comment by drott** [comment]
Nice :+1:
