### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by ghost** [behdad/harfbuzz#67]
*** Building harfbuzz *** [1/38]
make -j 3
make  all-recursive
make[1]: Entering directory '/home/aveyond/jhbuild/checkout/harfbuzz'
Making all in src
make[2]: Entering directory '/home/aveyond/jhbuild/checkout/harfbuzz/src'
make[3]: Entering directory '/home/aveyond/jhbuild/checkout/harfbuzz/src/hb-ucdn'
make[3]: Leaving directory '/home/aveyond/jhbuild/checkout/harfbuzz/src/hb-ucdn'
make  all-recursive
make[3]: Entering directory '/home/aveyond/jhbuild/checkout/harfbuzz/src'
make[4]: Entering directory '/home/aveyond/jhbuild/checkout/harfbuzz/src'
  GEN      libharfbuzz.la
  GEN      harfbuzz-icu.pc
  GEN      harfbuzz.pc
/usr/bin/ld: .libs/libharfbuzz_la-hb-blob.o: relocation R_X86_64_32 against `hb_blob_destroy' can not be used when making a shared object; recompile with -fPIC
.libs/libharfbuzz_la-hb-blob.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:1097: recipe for target 'libharfbuzz.la' failed
make[4]: *** [libharfbuzz.la] Error 1
make[4]: Leaving directory '/home/aveyond/jhbuild/checkout/harfbuzz/src'
Makefile:1726: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/aveyond/jhbuild/checkout/harfbuzz/src'
Makefile:1018: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/aveyond/jhbuild/checkout/harfbuzz/src'
Makefile:478: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/aveyond/jhbuild/checkout/harfbuzz'
Makefile:409: recipe for target 'all' failed
make: *** [all] Error 2
*** Error during phase build of harfbuzz: ########## Error running make -j 3 *** [1/38]

Fedora 21 Beta

**Comment by behdad** [comment]
Toolchain issue.

**Comment by Urne** [comment]
what library/headers were missing? im running into the same issue...

**Comment by ErwanDouaille** [comment]
Same issue here, how did you fix it ?
