### ISSUE TITLE
[wish] Add "ot-dumb" shaper that only runs GSUB+GPOS but no special shaping

### ISSUE THREAD

**Issue by twardoch** [behdad/harfbuzz#73]
Behdad,

could you add an "ot-dumb" shaper that would only run the font-defined GSUB+GPOS features, but would not perform any script-specific shaping? 

That shaper would not perform any "intelligent" shaping, would not split the shaping process into stages (pre-shaping, shaping, post-shaping), would not apply any features by default (i.e. would treat all features as discretionary and off), and would apply all the GSUB then GPOS features at once, in font-defined features order. 

Such a shaper would be most useful for testing the features during font development and debugging.

**Comment by davelab6** [comment]
Perhaps when a vendor like Fontlab develops such a visual otl tool, it
could contribute this shaper to HB :)

**Comment by behdad** [comment]
I'll get to reply here properly.  Don't jump to many conclusions in the mean time :).  Cheers and happy new year everyone!

**Comment by behdad** [comment]
> I'm wondering maybe what @twardoch is asking for matches to what I'm seeking for. If this is different topic and I look as if hijacking this issue, please let me know and I'll open another issue.

Completely different issues, yes.


> I'm looking into using HarfBuzz for East Asian scripts with comparable performance as the code written specifically for East Asian scripts.

Then you should first profile the code to see *where* the extra time is being spent.  You'd be surprised.


> In my understanding, we could classify scripts into 3 categories:
> 1. Latin (sometimes liga, locl, etc., I'm not super expert here)
> 2. East Asian (Latin + vertical flow, etc)
> 3. Complex scripts (Latin + shaping, etc, I'm not expert at all here)

It's not really like that.  Text shaping is complex.  There's just varying levels.

> Currently, correct me if I'm wrong but IIUC, HarfBuzz always analyzes scripts and split runs as needed.

HarfBuzz doesn't do any splitting runs whatsoever.

> But for Latin/East Asian scripts, all what we need is to enable specific OpenType features and apply GSUB/GPOS.

That's all HarfBuzz will do in those situations.
 

> So I wish applications can disable features only needed for complex scripts and get better performance when they know we're handling Latin or East Asian scripts.

Features that do not exist in the font don't affect performance.  Features that don't apply to a certain script, don't affect performance.

@KonstantinRitt has argued before that turning liga and kern in Latin can result in drastic speedup.  That's true, but user can already disable those if desired.  That said, my stance has always been that if font developer put it in the font, they wanted it to be applied.

> Is this reasonable to consider,

I don't see any proposal in your message.

> and does this match to what @twardoch want?

No.

**Comment by behdad** [comment]
So, Adam.  Looks like what you want is basically to force disable all features.  You can already do that, by passing a long list to HarfBuzz.  I might consider a hacky way to disable them all, but then people will start abusing it because it "makes shaping much faster" and then we all lose.

For Latin and other "generic" scripts, HarfBuzz applies all features together anyway.

What I do want to add, and we have talked before, is ways to disable *other* features of the shaping.  That is, normalization, synthetic GDEF, fallback glyph positioning, fallback Arabic and Thai, etc.  That would be very useful for testing, but that's very different from what you are describing.

I'm actually going to work on a Python OpenType font debugger kind of thing at some point.  I think most of what you want can be done already.

**Comment by twardoch** [comment]
Yes, disabling non-canonic convenience functionality (normalization, fallback, synthesis), i.e. an "ot-pure" backend, would be the highest on my list.

This issue here is a bit different. It's more like "running 'arab' or 'dev2' features through the Latin shaper" — which is precisely what the default Adobe "non-World" composers do. Of course we at FontLab can hack around that a bit (e.g. temporarily copy the contents of a script branch into the "DFLT" script and then forcing HB to shape the "DFLT" script. I'm sure we'll figure out a way. 

The "ot-pure" backend (no convenience functionality) is much higher on my wish list.

**Comment by behdad** [comment]
If you pass a bogus hb_script_t to HarfBuzz, you'll be routed to generic shaper.

**Comment by twardoch** [comment]
Ok, cool.

**Comment by twardoch** [comment]
Ehmm... An API option "force generic shaper for all scripts", then? Otherwise we'd need to build a copy of the the OTL tables with bugus script names, which is hacky :)

(Along with "disable convenience preprocessing" as discussed above").

**Comment by behdad** [comment]
Humm.  It's a hack but should work: if you directly pass the OpenType script, it will get you what you want.  That is, instead of HB_SCRIPT_ARABIC, you would use ((hb_script_t) HB_TAG('a','r','a','b')).

**Comment by behdad** [comment]
The reason I don't like "force generic shaper for all scripts" is that it's wrong.  Has no use other than emulating broken software.  I don't want to expose APIs that can be misused by people who don't know much about fonts and text rendering (ie. typical software developers).

**Comment by twardoch** [comment]
((hb_script_t) HB_TAG('a','r','a','b')) will do "force generic" or "skip convenience"?

**Comment by behdad** [comment]
Will go through generic shaper, but still chooses the 'arab' OpenType Script lookups.

**Comment by behdad** [comment]
Disabling "enhanced" processing (normalization, fallback positioning, etc) is not currently possible.

**Comment by twardoch** [comment]
Thanks, super useful. 

Generally, I agree with your desire to provide "good" behavior. But the "force generic" mode is more than just emulating broken software. It's one of the more low-level / font debug functionalities, similar to a more comprehensive shaping reporting (not just in/out but for example a report on intermediate states after each phase or lookup), or the ability to run lookups one by one — both things we once discussed. 

I'm not arguing that you should invest your time into implementing those, because these functionalities are "only" of interest for ont developers and font tool developers, not mainstream end-users. 

I'd argue, however, that HB should and can serve a two audiences: on one hand, end-users and implementers of text layout apps, on the other, font developers and font tool developers. 

The Chrome Dev tools or Firebug for Firefox show that developers need more fine-grained control and want to use the same processor as the end-users (web browser or font layout engine), just on a different level of detail.

You're right that it should probably not be mixed in one API. Perhaps a separate "Developer API" could be designated, even as a stub which other developers (such as FontLab) would fill in with code. Alternatively, at this point, little code gems like the one you just provided work, too -- ideally if you'd be kind enough to let us know whether you intend to keep certain undocumented behaviors to work more-less unchanged, or notify the community here on Github if some "known trick" will cease to work after some intentionsl changes. 

Thanks!
A.

**Comment by behdad** [comment]
I like to provide a lower-level API at some point, but that has not been priority so far.  I'll see what I can do.  In fact, it might be possible to expose constructors to build custom hb_shape_plan_t's...  Again, need to know what exactly one would need before I can expose such APIs.

That said, I'll focus on getting the debug API I have in mind implemented and see how much that helps.

Re keeping undocumented behavior unchanged to the extent that *any* clients rely on it is the way I approach changes to HarfBuzz already.  We definitely can make you guys happy.

Cheers,
b

**Comment by kojiishi** [comment]
Thank you for your reply, Behdad.

> Then you should first profile the code to see where the
> extra time is being spent. You'd be surprised.

I admit that I don't have clear cut between our adopting code to HarfBuzz and HarfBuzz itself, and you're right that our adopting code splits the runs. What I haven't figure out is how/if we can pass runs without splitting.

> HarfBuzz doesn't do any splitting runs whatsoever.

Ok, thank you for the lecture. I'll then look into how to pass our runs without splitting and how I could control each code path in HarfBuzz. I'm a bit confused with this thread, but it sounds like you're saying it's already possible with existing APIs.

>> But for Latin/East Asian scripts, all what we need is to enable specific OpenType features and apply GSUB/GPOS.

> That's all HarfBuzz will do in those situations.

Ok, thank you again. Sounds like the issue is in our adopting code. I'll look into that.

**Comment by twardoch** [comment]
I've opened https://github.com/behdad/harfbuzz/issues/80 to track the "disable convenience functionality" request.
