### ISSUE TITLE
[wish] Pure OT shaping: disabling non-canonic convenience functionality (normalization, fallback, synthesis)

### ISSUE THREAD

**Issue by twardoch** [behdad/harfbuzz#80]
Introduce ways to disable functionalities of the "ot" shaping backend which are not canonical to OpenType Layout, including: 
- normalization
- synthetic GDEF
- fallback glyph positioning
- fallback Arabic and Thai

etc. 

Behdad already stated his intent to do this, and this is the issue to track it.

**Comment by behdad** [comment]
Technically synthesized GDEF is part of OpenType requirements.

**Comment by behdad** [comment]
In particular, in this page:

  http://www.microsoft.com/typography/otspec/GDEF.htm

There's this text:

"""If the font does not include a GlyphClassDef table, the client must define and maintain this information when using the GSUB and GPOS tables."""

**Comment by twardoch** [comment]
Good point. I'd leave it in, then. The other issues bother me more. For testing purposes, synth GDEF can be worked around very easily (by supplying an empty GlyphClassDef). The other behaviors are a bit more tricky to catch, and thus more misleading. Also, I guess they're the ones where HarfBuzz does "more" than other engines do.

**Comment by behdad** [comment]
Ok lets see what you can do without HarfBuzz as is:

Normalization can be fully disabled if you use hb_unicode_funcs_create(hb_unicode_funcs_get_default) and then set compose(), decompose(), and decompose_compatibility() callbacks that do nothing (return false / 0).

Fallback positioning can be disabled if you similarly use a font_funcs implementation that returns false for get_glyph_extents().  Also see hb_font_create_sub_font().  You don't need to modify your existing font_funcs, you can provide an overlay that disables get_glyph_extents(), similar to the unicode_funcs approach.

The fallback Thai shaping (ie. the shape-to-PUA) is automatically disabled if the font has a GSUB script for Thai.

The fallback Arabic shaping is automatically disabled if the font has at least one of init/medi/fini/isol.

I think I still want to implement a pure mode in the API, but this should unblock anyone needing that today.

**Comment by behdad** [comment]
So talking to Jonathan, we think we want to allow disabling these:

  * Fallback Arabic shaping,
  * fallback Thai shaping,
  * fallback positioning

on the grounds that these are neither part of OpenType, nor Unicode.  I'm leaning towards disabling them all together, with no fine-grained control.
