### ISSUE TITLE
"No libtoolize (libtool) found, please install it" on Mac OS X 10.10

### ISSUE THREAD

**Issue by twardoch** [behdad/harfbuzz#89]
When I run ```./autogen.sh```, I get: 

```
/autogen.sh
-n checking for ragel...
/usr/local/bin/ragel
-n checking for pkg-config...
/usr/local/bin/pkg-config
-n checking for libtoolize...
*** No libtoolize (libtool) found, please install it ***
```

autogen.sh seems to just to ```which libtoolize```. However, because Mac OS X does include an old version of libtool, the Homebrew environment installs "libtoolize" as "glibtoolize". I wonder if ./autogen.sh could be made aware of that and check for "glibtoolize" first.

**Comment by behdad** [comment]
Ouch, I should have known better.  Fixed.
