### ISSUE TITLE
ICU Hiragana and Katakana should both map to 'kana'

### ISSUE THREAD

**Issue by kojiishi** [behdad/harfbuzz#94]
According to OpenType specification for its script tags:
http://www.microsoft.com/typography/otspec/scripttags.htm

Both Hiragana and Katakana are mapped to a same OpenType script tag 'kana'. As of OpenType 1.6, this is the only case where multiple scripts need to map to single OpenType script tag.

This actually should be done in caller side, since collating scripts earlier help to split to less runs and allow ligatures across these scripts, but doing this in HB is also nice to do.

**Comment by behdad** [comment]
This is already how HarfBuzz works.

Doing on the caller side is not desired currently.  It might improve the kana experience, but it's a more general limitation of OpenType that is better not worked around this way.
